# This file contains an example BN for testing
import sorobn as sbn
import pandas as pd 

# first define network structure
net = sbn.BayesNet(
    ('Age', ['SocioEcon', 'RiskAversion', 'GoodStudent', 'SeniorTrain', 'DrivingSkill', 'MedCost']),
    ('SocioEcon', ['GoodStudent', 'RiskAversion','MakeModel', 'OtherCar', 'VehicleYear', 'HomeBase','AntiTheft']),
    ('RiskAversion', ['SeniorTrain', 'DrivHist', 'DrivQuality', 'MakeModel', 'VehicleYear','HomeBase', 'AntiTheft']),
    ('SeniorTrain', 'DrivingSkill'),
    ('HomeBase','Theft'),
    ('AntiTheft','Theft'),
    ('DrivingSkill',['DrivHist','DrivQuality']),
    ('DrivQuality','Accident'),
    ('MakeModel',['Airbag','Antilock','RuggedAuto','CarValue']),
    ('VehicleYear',['Airbag','Antilock','RuggedAuto','CarValue']),
    ('Mileage',['CarValue','Accident']),
    ('Airbag','Cushioning'),
    ('Antilock','Accident'),
    ('RuggedAuto',['Cushioning','OtherCarCost','ThisCarDam']),
    ('CarValue',['ThisCarCost','Theft']),
    ('Cushioning','MedCost'),
    ('Accident',['MedCost','ILiCost','OtherCarCost', 'ThisCarDam']),
    ('Theft','ThisCarCost'),
    ('OtherCarCost','PropCost'),
    ('ThisCarDam','ThisCarCost'),
    ('ThisCarCost','PropCost'),

)


# next define conditional probabilities
net.P['Age'] = pd.Series({'Adolescent': 0.2, 'Adult': 0.6, 'Senior': 0.2})
net.P['SocioEcon'] = pd.Series({

    ('Adolescent', 'Prole'): 0.4,
    ('Adolescent', 'Middle'): 0.4,
    ('Adolescent', 'UpperMiddle'): 0.19,
    ('Adolescent', 'Wealthy'): 0.01,
    ('Adult', 'Prole'): 0.4,
    ('Adult', 'Middle'): 0.4,
    ('Adult', 'UpperMiddle'): 0.19,
    ('Adult', 'Wealthy'): 0.01,
    ('Senior', 'Prole'): 0.5,
    ('Senior', 'Middle'): 0.2,
    ('Senior', 'UpperMiddle'): 0.29,
    ('Senior', 'Wealthy'): 0.01,
})

net.P['OtherCar'] = pd.Series({

    ('Prole', 'True'): 0.5,
    ('Prole', 'False'): 0.5,
    ('Middle', 'True'): 0.8,
    ('Middle', 'Faalse'): 0.2,
    ('UpperMiddle', 'True'): 0.9,
    ('UpperMiddle', 'False'): 0.1,
    ('Wealthy', 'True'): 0.95,
    ('Wealthy', 'Faalse'): 0.05,
})

net.P['GoodStudent'] = pd.Series({

    ('Adolescent', 'Prole', 'True'): 0.1,
    ('Adolescent', 'Prole', 'False'): 0.9,
    ('Adolescent', 'Middle', 'True'): 0.2,
    ('Adolescent', 'Middle', 'False'): 0.8,
    ('Adolescent', 'UpperMiddle', 'True'): 0.5,
    ('Adolescent', 'UpperMiddle', 'False'): 0.5,
    ('Adolescent', 'Wealthy', 'True'): 0.4,
    ('Adolescent', 'Wealthy', 'False'): 0.6,

    ('Adult', 'Prole', 'True'): 0.0,
    ('Adult', 'Prole', 'False'): 1.0,
    ('Adult', 'Middle', 'True'): 0.0,
    ('Adult', 'Middle', 'False'): 1.0,
    ('Adult', 'UpperMiddle', 'True'): 0.0,
    ('Adult', 'UpperMiddle', 'False'): 1.0,
    ('Adult', 'Wealthy', 'True'): 0.0,
    ('Adult', 'Wealthy', 'False'): 1.0,

    ('Senior', 'Prole', 'True'): 0.0,
    ('Senior', 'Prole', 'False'): 1.0,
    ('Senior', 'Middle', 'True'): 0.0,
    ('Senior', 'Middle', 'False'): 1.0,
    ('Senior', 'UpperMiddle', 'True'): 0.0,
    ('Senior', 'UpperMiddle', 'False'): 1.0,
    ('Senior', 'Wealthy', 'True'): 0.0,
    ('Senior', 'Wealthy', 'False'): 1.0,
})
net.P['RiskAversion'] = pd.Series({

    ('Adolescent', 'Prole', 'Psychopath'): 0.02,
    ('Adolescent', 'Prole', 'Adventurous'): 0.58,
    ('Adolescent', 'Prole', 'Normal'): 0.3,
    ('Adolescent', 'Prole', 'Cautious'): 0.1, 
    ('Adolescent', 'Middle','Psychopath'): 0.02,
    ('Adolescent', 'Middle','Adventurous'): 0.38,
    ('Adolescent', 'Middle','Normal'): 0.5,
    ('Adolescent', 'Middle','Cautious'): 0.1, 
    ('Adolescent', 'UpperMiddle','Psychopath'): 0.02,
    ('Adolescent', 'UpperMiddle','Adventurous'): 0.48,
    ('Adolescent', 'UpperMiddle','Normal'): 0.40,
    ('Adolescent', 'UpperMiddle','Cautious'): 0.10,
    ('Adolescent', 'Wealthy', 'Psychopath'): 0.02,
    ('Adolescent', 'Wealthy', 'Adventurous'): 0.58,
    ('Adolescent', 'Wealthy', 'Normal'): 0.3,
    ('Adolescent', 'Wealthy', 'Cautious'): 0.1,

    ('Adult', 'Prole','Psychopath'): 0.015,
    ('Adult', 'Prole','Adventurous'): 0.285,
    ('Adult', 'Prole','Normal'): 0.5,
    ('Adult', 'Prole','Cautious'): 0.2, 
    ('Adult', 'Middle','Psychopath'): 0.015,
    ('Adult', 'Middle','Adventurous'): 0.185,
    ('Adult', 'Middle','Normal'): 0.6,
    ('Adult', 'Middle','Cautious'): 0.2,
    ('Adult', 'UpperMiddle','Psychopath'): 0.015,
    ('Adult', 'UpperMiddle','Adventurous'): 0.285,
    ('Adult', 'UpperMiddle','Normal'): 0.50,
    ('Adult', 'UpperMiddle','Cautious'): 0.20,
    ('Adult', 'Wealthy', 'Psychopath'): 0.015,
    ('Adult', 'Wealthy', 'Adventurous'): 0.285,
    ('Adult', 'Wealthy', 'Normal'): 0.4,
    ('Adult', 'Wealthy', 'Cautious'): 0.3,

    ('Senior', 'Prole', 'Psychopath'): 0.01,
    ('Senior', 'Prole', 'Adventurous'): 0.09,
    ('Senior', 'Prole', 'Normal'): 0.4,
    ('Senior', 'Prole', 'Cautious'): 0.5, #good
    ('Senior', 'Middle','Psychopath'): 0.01,
    ('Senior', 'Middle','Adventurous'): 0.04,
    ('Senior', 'Middle','Normal'): 0.35,
    ('Senior', 'Middle','Cautious'): 0.60,
    ('Senior', 'UpperMiddle','Psychopath'): 0.01,
    ('Senior', 'UpperMiddle','Adventurous'): 0.09,
    ('Senior', 'UpperMiddle','Normal'): 0.40,
    ('Senior', 'UpperMiddle','Cautious'): 0.50,
    ('Senior', 'Wealthy', 'Psychopath'): 0.01,
    ('Senior', 'Wealthy', 'Adventurous'): 0.09,
    ('Senior', 'Wealthy', 'Normal'): 0.4,
    ('Senior', 'Wealthy', 'Cautious'): 0.5,
})

net.P['SeniorTrain'] = pd.Series({

    ('Adolescent','Psychopath','True'): 0.0,
    ('Adolescent','Psychopath','False'): 1.0,
    ('Adult','Psychopath','True'): 0.0,
    ('Adult','Psychopath','False'): 1.0,
    ('Senior','Psychopath','True'): 0.000001,
    ('Senior','Psychopath','False'): 0.999999,

    ('Adolescent','Adventurous','True'): 0.0,
    ('Adolescent','Adventurous','False'): 1.0,
    ('Adult','Adventurous','True'): 0.0,
    ('Adult','Adventurous','False'): 1.0,
    ('Senior','Adventurous','True'): 0.000001,
    ('Senior','Adventurous','False'): 0.999999,


    ('Adolescent','Normal','True'): 0.0,
    ('Adolescent','Normal','False'): 1.0,
    ('Adult','Normal','True'): 0.0,
    ('Adult','Normal','False'): 1.0,
    ('Senior','Normal','True'): 0.3,
    ('Senior','Normal','False'): 0.7,

    ('Adolescent','Cautious','True'): 0.0,
    ('Adolescent','Cautious','False'): 1.0,
    ('Adult','Cautious','True'): 0.0,
    ('Adult','Cautious','False'): 1.0,
    ('Senior','Cautious','True'): 0.9,
    ('Senior','Cautious','False'): 0.1,
})

net.P['HomeBase'] = pd.Series({

    ('Psychopath', 'Prole', 'Secure') : 0.000001,
    ('Psychopath', 'Prole', 'City') : 0.8,
    ('Psychopath', 'Prole', 'Suburb') : 0.049999,
    ('Psychopath', 'Prole', 'Rural') : 0.15,

    ('Adventurous', 'Prole', 'Secure') : 0.000001,
    ('Adventurous', 'Prole', 'City') : 0.8,
    ('Adventurous', 'Prole', 'Suburb') : 0.05,
    ('Adventurous', 'Prole', 'Rural') : 0.149999,

    ('Normal', 'Prole', 'Secure') : 0.000001,
    ('Normal', 'Prole', 'City') : 0.8,
    ('Normal', 'Prole', 'Suburb') : 0.05,
    ('Normal', 'Prole', 'Rural') : 0.149999,

    ('Cautious', 'Prole', 'Secure') : 0.000001,
    ('Cautious', 'Prole', 'City') : 0.8,
    ('Cautious', 'Prole', 'Suburb') : 0.05,
    ('Cautious', 'Prole', 'Rural') : 0.149999,

    ('Psychopath', 'Middle', 'Secure') : 0.15,
    ('Psychopath', 'Middle', 'City') : 0.8,
    ('Psychopath', 'Middle', 'Suburb') : 0.04,
    ('Psychopath', 'Middle', 'Rural') : 0.01,

    ('Adventurous', 'Middle', 'Secure') : 0.01,
    ('Adventurous', 'Middle', 'City') : 0.25,
    ('Adventurous', 'Middle', 'Suburb') : 0.6,
    ('Adventurous', 'Middle', 'Rural') : 0.14,

    ('Normal', 'Middle', 'Secure') : 0.299999,
    ('Normal', 'Middle', 'City') : 0.000001,
    ('Normal', 'Middle', 'Suburb') : 0.6,
    ('Normal', 'Middle', 'Rural') : 0.1,

    ('Cautious', 'Middle', 'Secure') : 0.95,
    ('Cautious', 'Middle', 'City') : 0.000001,
    ('Cautious', 'Middle', 'Suburb') : 0.024445,
    ('Cautious', 'Middle', 'Rural') : 0.025554,

    
    ('Psychopath', 'UpperMiddle', 'Secure') : 0.35,
    ('Psychopath', 'UpperMiddle', 'City') : 0.6,
    ('Psychopath', 'UpperMiddle', 'Suburb') : 0.04,
    ('Psychopath', 'UpperMiddle', 'Rural') : 0.01,

    ('Adventurous', 'UpperMiddle', 'Secure') : 0.2,
    ('Adventurous', 'UpperMiddle', 'City') : 0.4,
    ('Adventurous', 'UpperMiddle', 'Suburb') : 0.3,
    ('Adventurous', 'UpperMiddle', 'Rural') : 0.1,

    ('Normal', 'UpperMiddle', 'Secure') : 0.5,
    ('Normal', 'UpperMiddle', 'City') : 0.000001,
    ('Normal', 'UpperMiddle', 'Suburb') : 0.4,
    ('Normal', 'UpperMiddle', 'Rural') : 0.099999,

    ('Cautious', 'UpperMiddle', 'Secure') : 0.999997,
    ('Cautious', 'UpperMiddle', 'City') : 0.000001,
    ('Cautious', 'UpperMiddle', 'Suburb') : 0.000001,
    ('Cautious', 'UpperMiddle', 'Rural') : 0.000001,

    ('Psychopath', 'Wealthy', 'Secure') : 0.489999,
    ('Psychopath', 'Wealthy', 'City') : 0.5,
    ('Psychopath', 'Wealthy', 'Suburb') : 0.000001,
    ('Psychopath', 'Wealthy', 'Rural') : 0.010000,

    ('Adventurous', 'Wealthy', 'Secure') : 0.950000,
    ('Adventurous', 'Wealthy', 'City') : 0.000001,
    ('Adventurous', 'Wealthy', 'Suburb') : 0.000001,
    ('Adventurous', 'Wealthy', 'Rural') : 0.489999,

    ('Normal', 'Wealthy', 'Secure') : 0.850000,
    ('Normal', 'Wealthy', 'City') : 0.000001,
    ('Normal', 'Wealthy', 'Suburb') : 0.001000,
    ('Normal', 'Wealthy', 'Rural') : 0.148999,

    ('Cautious', 'Wealthy', 'Secure') : 0.999997,
    ('Cautious', 'Wealthy', 'City') : 0.000001,
    ('Cautious', 'Wealthy', 'Suburb') : 0.000001,
    ('Cautious', 'Wealthy', 'Rural') : 0.000001,
})

net.P['AntiTheft'] = pd.Series({

    ('Psychopath', 'Prole', 'True') : 0.000001,
    ('Psychopath', 'Prole', 'False') : 0.999999,
    ('Adventurous', 'Prole', 'True') : 0.000001,
    ('Adventurous', 'Prole', 'False') : 0.999999,
    ('Normal', 'Prole', 'True') : 0.1,
    ('Normal', 'Prole', 'False') : 0.9,
    ('Cautious', 'Prole', 'True') : 0.95,
    ('Cautious', 'Prole', 'False') : 0.05,

    ('Psychopath', 'Middle', 'True') : 0.000001,
    ('Psychopath', 'Middle', 'False') : 0.999999,
    ('Adventurous', 'Middle', 'True') : 0.000001,
    ('Adventurous', 'Middle', 'False') : 0.999999,
    ('Normal', 'Middle', 'True') : 0.3,
    ('Normal', 'Middle', 'False') : 0.7,
    ('Cautious', 'Middle', 'True') : 0.999999,
    ('Cautious', 'Middle', 'False') : 0.000001,

    ('Psychopath', 'UpperMiddle', 'True') : 0.05,
    ('Psychopath', 'UpperMiddle', 'False') : 0.95,
    ('Adventurous', 'UpperMiddle', 'True') : 0.2,
    ('Adventurous', 'UpperMiddle', 'False') : 0.8,
    ('Normal', 'UpperMiddle', 'True') : 0.9,
    ('Normal', 'UpperMiddle', 'False') : 0.1,
    ('Cautious', 'UpperMiddle', 'True') : 0.999999,
    ('Cautious', 'UpperMiddle', 'False') : 0.000001,

    ('Psychopath', 'Wealthy', 'True') : 0.5,
    ('Psychopath', 'Wealthy', 'False') : 0.5,
    ('Adventurous', 'Wealthy', 'True') : 0.5,
    ('Adventurous', 'Wealthy', 'False') : 0.5,
    ('Normal', 'Wealthy', 'True') : 0.8,
    ('Normal', 'Wealthy', 'False') : 0.2,
    ('Cautious', 'Wealthy', 'True') : 0.999999,
    ('Cautious', 'Wealthy', 'False') : 0.000001,
})

net.P['DrivingSkill'] = pd.Series({

    ('Adolescent','True', 'Substandard'): 0.5,
    ('Adolescent','True', 'Normal'): 0.45,
    ('Adolescent','True', 'Expert'): 0.05,
    ('Adult','True', 'Substandard'): 0.3,
    ('Adult','True', 'Normal'): 0.6,
    ('Adult','True', 'Expert'): 0.1,
    ('Senior','True', 'Substandard'): 0.1,
    ('Senior','True', 'Normal'): 0.6,
    ('Senior','True', 'Expert'): 0.3,

    ('Adolescent','False', 'Substandard'): 0.5,
    ('Adolescent','False', 'Normal'): 0.45,
    ('Adolescent','False', 'Expert'): 0.05,
    ('Adult','False', 'Substandard'): 0.3,
    ('Adult','False', 'Normal'): 0.6,
    ('Adult','False', 'Expert'): 0.1,
    ('Senior','False', 'Substandard'): 0.4,
    ('Senior','False', 'Normal'): 0.5,
    ('Senior','False', 'Expert'): 0.1,
})


net.P['DrivQuality'] = pd.Series({

    ('Substandard', 'Psychopath', 'Poor'): 1.0,
    ('Substandard', 'Psychopath', 'Normal'): 0.0,
    ('Substandard', 'Psychopath', 'Excellent'): 0.0,
    ('Normal', 'Psychopath', 'Poor'): 0.5,
    ('Normal', 'Psychopath', 'Normal'): 0.2,
    ('Normal', 'Psychopath', 'Excellent'): 0.3,
    ('Expert', 'Psychopath', 'Poor'): 0.3,
    ('Expert', 'Psychopath', 'Normal'): 0.2,
    ('Expert', 'Psychopath', 'Excellent'): 0.5,

    ('Substandard', 'Adventurous', 'Poor'): 1.0,
    ('Substandard', 'Adventurous', 'Normal'): 0.0,
    ('Substandard', 'Adventurous', 'Excellent'): 0.0,
    ('Normal', 'Adventurous', 'Poor'): 0.3,
    ('Normal', 'Adventurous', 'Normal'): 0.4,
    ('Normal', 'Adventurous', 'Excellent'): 0.3,
    ('Expert', 'Adventurous', 'Poor'): 0.01,
    ('Expert', 'Adventurous', 'Normal'): 0.98,
    ('Expert', 'Adventurous', 'Excellent'): 0.01,

    ('Substandard', 'Normal', 'Poor'): 1.0,
    ('Substandard', 'Normal', 'Normal'): 0.0,
    ('Substandard', 'Normal', 'Excellent'): 0.0,
    ('Normal', 'Normal', 'Poor'): 0.0,
    ('Normal', 'Normal', 'Normal'): 1.0,
    ('Normal', 'Normal', 'Excellent'): 0.0,
    ('Expert', 'Normal', 'Poor'): 0.0,
    ('Expert', 'Normal', 'Normal'): 0.0,
    ('Expert', 'Normal', 'Excellent'): 1.0,

    ('Substandard', 'Cautious', 'Poor'): 1.0,
    ('Substandard', 'Cautious', 'Normal'): 0.0,
    ('Substandard', 'Cautious', 'Excellent'): 0.0,
    ('Normal', 'Cautious', 'Poor'): 0.0,
    ('Normal', 'Cautious', 'Normal'): 0.8,
    ('Normal', 'Cautious', 'Excellent'): 0.2,
    ('Expert', 'Cautious', 'Poor'): 0.9,
    ('Expert', 'Cautious', 'Normal'): 0.0,
    ('Expert', 'Cautious', 'Excellent'): 1.0,
})

net.P['MakeModel'] = pd.Series({

    ('Psychopath', 'Prole', 'SportsCar') : 0.1,
    ('Psychopath', 'Prole', 'Economy') : 0.7,
    ('Psychopath', 'Prole', 'FamilySedan') : 0.2,
    ('Psychopath', 'Prole', 'Luxury') : 0.0,
    ('Psychopath', 'Prole', 'SuperLuxury') : 0.0,

    ('Psychopath', 'Middle', 'SportsCar') : 0.15,
    ('Psychopath', 'Middle', 'Economy') : 0.20,
    ('Psychopath', 'Middle', 'FamilySedan') : 0.65,
    ('Psychopath', 'Middle', 'Luxury') : 0.0,
    ('Psychopath', 'Middle', 'SuperLuxury') : 0.0,

    ('Psychopath', 'UpperMiddle', 'SportsCar') : 0.20,
    ('Psychopath', 'UpperMiddle', 'Economy') : 0.05,
    ('Psychopath', 'UpperMiddle', 'FamilySedan') : 0.30,
    ('Psychopath', 'UpperMiddle', 'Luxury') : 0.45,
    ('Psychopath', 'UpperMiddle', 'SuperLuxury') : 0.0,

    ('Psychopath', 'Wealthy', 'SportsCar') : 0.30,
    ('Psychopath', 'Wealthy', 'Economy') : 0.01,
    ('Psychopath', 'Wealthy', 'FamilySedan') : 0.09,
    ('Psychopath', 'Wealthy', 'Luxury') : 0.40,
    ('Psychopath', 'Wealthy', 'SuperLuxury') : 0.20,


    ('Adventurous', 'Prole', 'SportsCar') : 0.1,
    ('Adventurous', 'Prole', 'Economy') : 0.7,
    ('Adventurous', 'Prole', 'FamilySedan') : 0.2,
    ('Adventurous', 'Prole', 'Luxury') : 0.0,
    ('Adventurous', 'Prole', 'SuperLuxury') : 0.0,

    ('Adventurous', 'Middle', 'SportsCar') : 0.15,
    ('Adventurous', 'Middle', 'Economy') : 0.20,
    ('Adventurous', 'Middle', 'FamilySedan') : 0.65,
    ('Adventurous', 'Middle', 'Luxury') : 0.0,
    ('Adventurous', 'Middle', 'SuperLuxury') : 0.0,

    ('Adventurous', 'UpperMiddle', 'SportsCar') : 0.20,
    ('Adventurous', 'UpperMiddle', 'Economy') : 0.05,
    ('Adventurous', 'UpperMiddle', 'FamilySedan') : 0.30,
    ('Adventurous', 'UpperMiddle', 'Luxury') : 0.45,
    ('Adventurous', 'UpperMiddle', 'SuperLuxury') : 0.0,

    ('Adventurous', 'Wealthy', 'SportsCar') : 0.30,
    ('Adventurous', 'Wealthy', 'Economy') : 0.01,
    ('Adventurous', 'Wealthy', 'FamilySedan') : 0.09,
    ('Adventurous', 'Wealthy', 'Luxury') : 0.40,
    ('Adventurous', 'Wealthy', 'SuperLuxury') : 0.20,

    ('Normal', 'Prole', 'SportsCar') : 0.1,
    ('Normal', 'Prole', 'Economy') : 0.7,
    ('Normal', 'Prole', 'FamilySedan') : 0.2,
    ('Normal', 'Prole', 'Luxury') : 0.0,
    ('Normal', 'Prole', 'SuperLuxury') : 0.0,

    ('Normal', 'Middle', 'SportsCar') : 0.15,
    ('Normal', 'Middle', 'Economy') : 0.20,
    ('Normal', 'Middle', 'FamilySedan') : 0.65,
    ('Normal', 'Middle', 'Luxury') : 0.0,
    ('Normal', 'Middle', 'SuperLuxury') : 0.0,

    ('Normal', 'UpperMiddle', 'SportsCar') : 0.20,
    ('Normal', 'UpperMiddle', 'Economy') : 0.05,
    ('Normal', 'UpperMiddle', 'FamilySedan') : 0.30,
    ('Normal', 'UpperMiddle', 'Luxury') : 0.45,
    ('Normal', 'UpperMiddle', 'SuperLuxury') : 0.0,

    ('Normal', 'Wealthy', 'SportsCar') : 0.30,
    ('Normal', 'Wealthy', 'Economy') : 0.01,
    ('Normal', 'Wealthy', 'FamilySedan') : 0.09,
    ('Normal', 'Wealthy', 'Luxury') : 0.40,
    ('Normal', 'Wealthy', 'SuperLuxury') : 0.20,
    
    ('Cautious', 'Prole', 'SportsCar') : 0.1,
    ('Cautious', 'Prole', 'Economy') : 0.7,
    ('Cautious', 'Prole', 'FamilySedan') : 0.2,
    ('Cautious', 'Prole', 'Luxury') : 0.0,
    ('Cautious', 'Prole', 'SuperLuxury') : 0.0,

    ('Cautious', 'Middle', 'SportsCar') : 0.15,
    ('Cautious', 'Middle', 'Economy') : 0.20,
    ('Cautious', 'Middle', 'FamilySedan') : 0.65,
    ('Cautious', 'Middle', 'Luxury') : 0.0,
    ('Cautious', 'Middle', 'SuperLuxury') : 0.0,

    ('Cautious', 'UpperMiddle', 'SportsCar') : 0.20,
    ('Cautious', 'UpperMiddle', 'Economy') : 0.05,
    ('Cautious', 'UpperMiddle', 'FamilySedan') : 0.30,
    ('Cautious', 'UpperMiddle', 'Luxury') : 0.45,
    ('Cautious', 'UpperMiddle', 'SuperLuxury') : 0.0,

    ('Cautious', 'Wealthy', 'SportsCar') : 0.30,
    ('Cautious', 'Wealthy', 'Economy') : 0.01,
    ('Cautious', 'Wealthy', 'FamilySedan') : 0.09,
    ('Cautious', 'Wealthy', 'Luxury') : 0.40,
    ('Cautious', 'Wealthy', 'SuperLuxury') : 0.20,
})

net.P['VehicleYear'] = pd.Series({

    ('Psychopath', 'Prole', 'Current') : 0.15,
    ('Psychopath', 'Prole', 'Older') : 0.85,
    ('Psychopath', 'Middle', 'Current') : 0.3,
    ('Psychopath', 'Middle', 'Older') : 0.7,
    ('Psychopath', 'UpperMiddle', 'Current') : 0.8,
    ('Psychopath', 'UpperMiddle', 'Older') : 0.2,
    ('Psychopath', 'Wealthy', 'Current') : 0.9,
    ('Psychopath', 'Wealthy', 'Older') : 0.1,

    ('Adventurous', 'Prole', 'Current') : 0.15,
    ('Adventurous', 'Prole', 'Older') : 0.85,
    ('Adventurous', 'Middle', 'Current') : 0.3,
    ('Adventurous', 'Middle', 'Older') : 0.7,
    ('Adventurous', 'UpperMiddle', 'Current') : 0.8,
    ('Adventurous', 'UpperMiddle', 'Older') : 0.2,
    ('Adventurous', 'Wealthy', 'Current') : 0.9,
    ('Adventurous', 'Wealthy', 'Older') : 0.1,

    ('Normal', 'Prole', 'Current') : 0.15,
    ('Normal', 'Prole', 'Older') : 0.85,
    ('Normal', 'Middle', 'Current') : 0.3,
    ('Normal', 'Middle', 'Older') : 0.7,
    ('Normal', 'UpperMiddle', 'Current') : 0.8,
    ('Normal', 'UpperMiddle', 'Older') : 0.2,
    ('Normal', 'Wealthy', 'Current') : 0.9,
    ('Normal', 'Wealthy', 'Older') : 0.1,

    ('Cautious', 'Prole', 'Current') : 0.15,
    ('Cautious', 'Prole', 'Older') : 0.85,
    ('Cautious', 'Middle', 'Current') : 0.3,
    ('Cautious', 'Middle', 'Older') : 0.7,
    ('Cautious', 'UpperMiddle', 'Current') : 0.8,
    ('Cautious', 'UpperMiddle', 'Older') : 0.2,
    ('Cautious', 'Wealthy', 'Current') : 0.9,
    ('Cautious', 'Wealthy', 'Older') : 0.1,
})

net.P['Mileage'] = pd.Series({'FiveThou': 0.1, 'TwentyThou': 0.4, 'FiftyThou': 0.4, 'Domino': 0.1})

net.P['Airbag'] = pd.Series({

    ('SportsCar', 'Current', 'True') : 1.0,
    ('SportsCar', 'Current', 'False') : 0.0,
    ('Economy', 'Current', 'True') : 1.0,
    ('Economy', 'Current', 'False') : 0.0,
    ('FamilySedan', 'Current', 'True') : 1.0,
    ('FamilySedan', 'Current', 'False') : 0.0,
    ('Luxury', 'Current', 'True') : 1.0,
    ('Luxury', 'Current', 'False') : 0.0,
    ('SuperLuxury', 'Current','True') : 1.0,
    ('SuperLuxury', 'Current', 'False') : 0.0,

    ('SportsCar', 'Older', 'True') : 0.1,
    ('SportsCar', 'Older', 'False') : 0.9,
    ('Economy', 'Older', 'True') : 0.05,
    ('Economy', 'Older', 'False') : 0.95,
    ('FamilySedan', 'Older', 'True') : 0.2,
    ('FamilySedan', 'Older', 'False') : 0.8,
    ('Luxury', 'Older', 'True') : 0.6,
    ('Luxury', 'Older', 'False') : 0.4,
    ('SuperLuxury', 'Older','True') : 0.1,
    ('SuperLuxury', 'Older', 'False') : 0.9,

})


net.P['Antilock'] = pd.Series({

    ('SportsCar', 'Current', 'True') : 0.9,
    ('SportsCar', 'Current', 'False') : 0.1,
    ('Economy', 'Current', 'True') : 0.001,
    ('Economy', 'Current', 'False') : 0.999,
    ('FamilySedan', 'Current', 'True') : 0.4,
    ('FamilySedan', 'Current', 'False') : 0.6,
    ('Luxury', 'Current', 'True') : 0.99,
    ('Luxury', 'Current', 'False') : 0.01,
    ('SuperLuxury', 'Current','True') : 0.99,
    ('SuperLuxury', 'Current', 'False') : 0.01,

    ('SportsCar', 'Older', 'True') : 0.1,
    ('SportsCar', 'Older', 'False') : 0.9,
    ('Economy', 'Older', 'True') : 0.0,
    ('Economy', 'Older', 'False') : 1.0,
    ('FamilySedan', 'Older', 'True') : 0.0,
    ('FamilySedan', 'Older', 'False') : 1.0,
    ('Luxury', 'Older', 'True') : 0.3,
    ('Luxury', 'Older', 'False') : 0.7,
    ('SuperLuxury', 'Older','True') : 0.15,
    ('SuperLuxury', 'Older', 'False') : 0.85,

})


net.P['RuggedAuto'] = pd.Series({

    ('SportsCar', 'Current', 'EggShell') : 0.95,
    ('SportsCar', 'Current', 'Football') : 0.04,
    ('SportsCar', 'Current', 'Tank') : 0.01,
    ('Economy', 'Current', 'EggShell') : 0.5,
    ('Economy', 'Current', 'Football') : 0.5,
    ('Economy', 'Current', 'Tank') : 0.0,
    ('FamilySedan', 'Current', 'EggShell') : 0.2,
    ('FamilySedan', 'Current', 'Football') : 0.6,
    ('FamilySedan', 'Current', 'Tank') : 0.2,
    ('Luxury', 'Current', 'EggShell') : 0.1,
    ('Luxury', 'Current', 'Football') : 0.6,
    ('Luxury', 'Current', 'Tank') : 0.3,
    ('SuperLuxury', 'Current','EggShell') : 0.05,
    ('SuperLuxury', 'Current', 'Football') : 0.55,
    ('SuperLuxury', 'Current', 'Tank') : 0.4,

    ('SportsCar', 'Older', 'EggShell') : 0.95,
    ('SportsCar', 'Older', 'Football') : 0.04,
    ('SportsCar', 'Older', 'Tank') : 0.01,
    ('Economy', 'Older', 'EggShell') : 0.9,
    ('Economy', 'Older', 'Football') : 0.1,
    ('Economy', 'Older', 'Tank') : 0.0,
    ('FamilySedan', 'Older', 'EggShell') : 0.05,
    ('FamilySedan', 'Older', 'Football') : 0.55,
    ('FamilySedan', 'Older', 'Tank') : 0.4,
    ('Luxury', 'Older', 'EggShell') : 0.1,
    ('Luxury', 'Older', 'Football') : 0.6,
    ('Luxury', 'Older', 'Tank') : 0.3,
    ('SuperLuxury', 'Older','EggShell') : 0.05,
    ('SuperLuxury', 'Older', 'Football') : 0.55,
    ('SuperLuxury', 'Older', 'Tank') : 0.4,

})

net.P['CarValue'] = pd.Series({
    
    ('SportsCar', 'FiveThou', 'Current', 'FiveThou') : 0.0,
    ('SportsCar', 'FiveThou', 'Current', 'TenThou') : 0.1,
    ('SportsCar', 'FiveThou', 'Current', 'TwentyThou') : 0.8,
    ('SportsCar', 'FiveThou', 'Current', 'FiftyThou') : 0.09,
    ('SportsCar', 'FiveThou', 'Current', 'Million') : 0.01,

    ('Economy', 'FiveThou', 'Current', 'FiveThou') : 0.1,
    ('Economy', 'FiveThou', 'Current', 'TenThou') : 0.8,
    ('Economy', 'FiveThou', 'Current', 'TwentyThou') : 0.1,
    ('Economy', 'FiveThou', 'Current', 'FiftyThou') : 0.0,
    ('Economy', 'FiveThou', 'Current', 'Million') : 0.0,

    ('FamilySedan', 'FiveThou', 'Current', 'FiveThou') : 0.0,
    ('FamilySedan', 'FiveThou', 'Current', 'TenThou') : 0.1,
    ('FamilySedan', 'FiveThou', 'Current', 'TwentyThou') : 0.9,
    ('FamilySedan', 'FiveThou', 'Current', 'FiftyThou') : 0.0,
    ('FamilySedan', 'FiveThou', 'Current', 'Million') : 0.0,

    ('Luxury', 'FiveThou', 'Current', 'FiveThou') : 0.0,
    ('Luxury', 'FiveThou', 'Current', 'TenThou') : 0.0,
    ('Luxury', 'FiveThou', 'Current', 'TwentyThou') : 0.0,
    ('Luxury', 'FiveThou', 'Current', 'FiftyThou') : 1.0,
    ('Luxury', 'FiveThou', 'Current', 'Million') : 0.0,

    ('SuperLuxury', 'FiveThou', 'Current', 'FiveThou') : 0.0,
    ('SuperLuxury', 'FiveThou', 'Current', 'TenThou') : 0.0,
    ('SuperLuxury', 'FiveThou', 'Current', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'FiveThou', 'Current', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'FiveThou', 'Current', 'Million') : 1.0,


    ('SportsCar', 'FiveThou', 'Older', 'FiveThou') : 0.03,
    ('SportsCar', 'FiveThou', 'Older', 'TenThou') : 0.3,
    ('SportsCar', 'FiveThou', 'Older', 'TwentyThou') : 0.6,
    ('SportsCar', 'FiveThou', 'Older', 'FiftyThou') : 0.06,
    ('SportsCar', 'FiveThou', 'Older', 'Million') : 0.01,

    ('Economy', 'FiveThou', 'Older', 'FiveThou') : 0.25,
    ('Economy', 'FiveThou', 'Older', 'TenThou') : 0.7,
    ('Economy', 'FiveThou', 'Older', 'TwentyThou') : 0.05,
    ('Economy', 'FiveThou', 'Older', 'FiftyThou') : 0.0,
    ('Economy', 'FiveThou', 'Older', 'Million') : 0.0,

    ('FamilySedan', 'FiveThou', 'Older', 'FiveThou') : 0.2,
    ('FamilySedan', 'FiveThou', 'Older', 'TenThou') : 0.3,
    ('FamilySedan', 'FiveThou', 'Older', 'TwentyThou') : 0.5,
    ('FamilySedan', 'FiveThou', 'Older', 'FiftyThou') : 0.0,
    ('FamilySedan', 'FiveThou', 'Older', 'Million') : 0.0,

    ('Luxury', 'FiveThou', 'Older', 'FiveThou') : 0.01,
    ('Luxury', 'FiveThou', 'Older', 'TenThou') : 0.09,
    ('Luxury', 'FiveThou', 'Older', 'TwentyThou') : 0.20,
    ('Luxury', 'FiveThou', 'Older', 'FiftyThou') : 0.70,
    ('Luxury', 'FiveThou', 'Older', 'Million') : 0.0,

    ('SuperLuxury', 'FiveThou', 'Older', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'FiveThou', 'Older', 'TenThou') : 0.000001,
    ('SuperLuxury', 'FiveThou', 'Older', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'FiveThou', 'Older', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'FiveThou', 'Older', 'Million') : 0.999996,


    ('SportsCar', 'TwentyThou', 'Current', 'FiveThou') : 0.0,
    ('SportsCar', 'TwentyThou', 'Current', 'TenThou') : 0.1,
    ('SportsCar', 'TwentyThou', 'Current', 'TwentyThou') : 0.8,
    ('SportsCar', 'TwentyThou', 'Current', 'FiftyThou') : 0.09,
    ('SportsCar', 'TwentyThou', 'Current', 'Million') : 0.01,

    ('Economy', 'TwentyThou', 'Current', 'FiveThou') : 0.1,
    ('Economy', 'TwentyThou', 'Current', 'TenThou') : 0.8,
    ('Economy', 'TwentyThou', 'Current', 'TwentyThou') : 0.1,
    ('Economy', 'TwentyThou', 'Current', 'FiftyThou') : 0.0,
    ('Economy', 'TwentyThou', 'Current', 'Million') : 0.0,

    ('FamilySedan', 'TwentyThou', 'Current', 'FiveThou') : 0.0,
    ('FamilySedan', 'TwentyThou', 'Current', 'TenThou') : 0.1,
    ('FamilySedan', 'TwentyThou', 'Current', 'TwentyThou') : 0.9,
    ('FamilySedan', 'TwentyThou', 'Current', 'FiftyThou') : 0.0,
    ('FamilySedan', 'TwentyThou', 'Current', 'Million') : 0.0,

    ('Luxury', 'TwentyThou', 'Current', 'FiveThou') : 0.0,
    ('Luxury', 'TwentyThou', 'Current', 'TenThou') : 0.0,
    ('Luxury', 'TwentyThou', 'Current', 'TwentyThou') : 0.0,
    ('Luxury', 'TwentyThou', 'Current', 'FiftyThou') : 1.0,
    ('Luxury', 'TwentyThou', 'Current', 'Million') : 0.0,

    ('SuperLuxury', 'TwentyThou', 'Current', 'FiveThou') : 0.0,
    ('SuperLuxury', 'TwentyThou', 'Current', 'TenThou') : 0.0,
    ('SuperLuxury', 'TwentyThou', 'Current', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'TwentyThou', 'Current', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'TwentyThou', 'Current', 'Million') : 1.0,


    ('SportsCar', 'TwentyThou', 'Older', 'FiveThou') : 0.16,
    ('SportsCar', 'TwentyThou', 'Older', 'TenThou') : 0.5,
    ('SportsCar', 'TwentyThou', 'Older', 'TwentyThou') : 0.3,
    ('SportsCar', 'TwentyThou', 'Older', 'FiftyThou') : 0.03,
    ('SportsCar', 'TwentyThou', 'Older', 'Million') : 0.01,

    ('Economy', 'TwentyThou', 'Older', 'FiveThou') : 0.7,
    ('Economy', 'TwentyThou', 'Older', 'TenThou') : 0.2999,
    ('Economy', 'TwentyThou', 'Older', 'TwentyThou') : 0.0001,
    ('Economy', 'TwentyThou', 'Older', 'FiftyThou') : 0.0,
    ('Economy', 'TwentyThou', 'Older', 'Million') : 0.0,

    ('FamilySedan', 'TwentyThou', 'Older', 'FiveThou') : 0.5,
    ('FamilySedan', 'TwentyThou', 'Older', 'TenThou') : 0.3,
    ('FamilySedan', 'TwentyThou', 'Older', 'TwentyThou') : 0.2,
    ('FamilySedan', 'TwentyThou', 'Older', 'FiftyThou') : 0.0,
    ('FamilySedan', 'TwentyThou', 'Older', 'Million') : 0.0,

    ('Luxury', 'TwentyThou', 'Older', 'FiveThou') : 0.05,
    ('Luxury', 'TwentyThou', 'Older', 'TenThou') : 0.15,
    ('Luxury', 'TwentyThou', 'Older', 'TwentyThou') : 0.30,
    ('Luxury', 'TwentyThou', 'Older', 'FiftyThou') : 0.50,
    ('Luxury', 'TwentyThou', 'Older', 'Million') : 0.0,

    ('SuperLuxury', 'TwentyThou', 'Older', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'TwentyThou', 'Older', 'TenThou') : 0.000001,
    ('SuperLuxury', 'TwentyThou', 'Older', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'TwentyThou', 'Older', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'TwentyThou', 'Older', 'Million') : 0.999996,

    ('SportsCar', 'FiftyThou', 'Current', 'FiveThou') : 0.0,
    ('SportsCar', 'FiftyThou', 'Current', 'TenThou') : 0.1,
    ('SportsCar', 'FiftyThou', 'Current', 'TwentyThou') : 0.8,
    ('SportsCar', 'FiftyThou', 'Current', 'FiftyThou') : 0.09,
    ('SportsCar', 'FiftyThou', 'Current', 'Million') : 0.01,

    ('Economy', 'FiftyThou', 'Current', 'FiveThou') : 0.1,
    ('Economy', 'FiftyThou', 'Current', 'TenThou') : 0.8,
    ('Economy', 'FiftyThou', 'Current', 'TwentyThou') : 0.1,
    ('Economy', 'FiftyThou', 'Current', 'FiftyThou') : 0.0,
    ('Economy', 'FiftyThou', 'Current', 'Million') : 0.0,

    ('FamilySedan', 'FiftyThou', 'Current', 'FiveThou') : 0.0,
    ('FamilySedan', 'FiftyThou', 'Current', 'TenThou') : 0.1,
    ('FamilySedan', 'FiftyThou', 'Current', 'TwentyThou') : 0.9,
    ('FamilySedan', 'FiftyThou', 'Current', 'FiftyThou') : 0.0,
    ('FamilySedan', 'FiftyThou', 'Current', 'Million') : 0.0,

    ('Luxury', 'FiftyThou', 'Current', 'FiveThou') : 0.0,
    ('Luxury', 'FiftyThou', 'Current', 'TenThou') : 0.0,
    ('Luxury', 'FiftyThou', 'Current', 'TwentyThou') : 0.0,
    ('Luxury', 'FiftyThou', 'Current', 'FiftyThou') : 1.0,
    ('Luxury', 'FiftyThou', 'Current', 'Million') : 0.0,

    ('SuperLuxury', 'FiftyThou', 'Current', 'FiveThou') : 0.0,
    ('SuperLuxury', 'FiftyThou', 'Current', 'TenThou') : 0.0,
    ('SuperLuxury', 'FiftyThou', 'Current', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'FiftyThou', 'Current', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'FiftyThou', 'Current', 'Million') : 1.0,


    ('SportsCar', 'FiftyThou', 'Older', 'FiveThou') : 0.4,
    ('SportsCar', 'FiftyThou', 'Older', 'TenThou') : 0.47,
    ('SportsCar', 'FiftyThou', 'Older', 'TwentyThou') : 0.10,
    ('SportsCar', 'FiftyThou', 'Older', 'FiftyThou') : 0.02,
    ('SportsCar', 'FiftyThou', 'Older', 'Million') : 0.01,

    ('Economy', 'FiftyThou', 'Older', 'FiveThou') : 0.990000,
    ('Economy', 'FiftyThou', 'Older', 'TenThou') : 0.009999,
    ('Economy', 'FiftyThou', 'Older', 'TwentyThou') : 0.000001,
    ('Economy', 'FiftyThou', 'Older', 'FiftyThou') : 0.0,
    ('Economy', 'FiftyThou', 'Older', 'Million') : 0.0,

    ('FamilySedan', 'FiftyThou', 'Older', 'FiveThou') : 0.7,
    ('FamilySedan', 'FiftyThou', 'Older', 'TenThou') : 0.2,
    ('FamilySedan', 'FiftyThou', 'Older', 'TwentyThou') : 0.1,
    ('FamilySedan', 'FiftyThou', 'Older', 'FiftyThou') : 0.0,
    ('FamilySedan', 'FiftyThou', 'Older', 'Million') : 0.0,

    ('Luxury', 'FiftyThou', 'Older', 'FiveThou') : 0.1,
    ('Luxury', 'FiftyThou', 'Older', 'TenThou') : 0.3,
    ('Luxury', 'FiftyThou', 'Older', 'TwentyThou') : 0.3,
    ('Luxury', 'FiftyThou', 'Older', 'FiftyThou') : 0.3,
    ('Luxury', 'FiftyThou', 'Older', 'Million') : 0.0,

    ('SuperLuxury', 'FiftyThou', 'Older', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'FiftyThou', 'Older', 'TenThou') : 0.000001,
    ('SuperLuxury', 'FiftyThou', 'Older', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'FiftyThou', 'Older', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'FiftyThou', 'Older', 'Million') : 0.999996,


    ('SportsCar', 'Domino', 'Current', 'FiveThou') : 0.0,
    ('SportsCar', 'Domino', 'Current', 'TenThou') : 0.1,
    ('SportsCar', 'Domino', 'Current', 'TwentyThou') : 0.8,
    ('SportsCar', 'Domino', 'Current', 'FiftyThou') : 0.09,
    ('SportsCar', 'Domino', 'Current', 'Million') : 0.01,

    ('Economy', 'Domino', 'Current', 'FiveThou') : 0.1,
    ('Economy', 'Domino', 'Current', 'TenThou') : 0.8,
    ('Economy', 'Domino', 'Current', 'TwentyThou') : 0.1,
    ('Economy', 'Domino', 'Current', 'FiftyThou') : 0.0,
    ('Economy', 'Domino', 'Current', 'Million') : 0.0,

    ('FamilySedan', 'Domino', 'Current', 'FiveThou') : 0.0,
    ('FamilySedan', 'Domino', 'Current', 'TenThou') : 0.1,
    ('FamilySedan', 'Domino', 'Current', 'TwentyThou') : 0.9,
    ('FamilySedan', 'Domino', 'Current', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Domino', 'Current', 'Million') : 0.0,

    ('Luxury', 'Domino', 'Current', 'FiveThou') : 0.0,
    ('Luxury', 'Domino', 'Current', 'TenThou') : 0.0,
    ('Luxury', 'Domino', 'Current', 'TwentyThou') : 0.0,
    ('Luxury', 'Domino', 'Current', 'FiftyThou') : 1.0,
    ('Luxury', 'Domino', 'Current', 'Million') : 0.0,

    ('SuperLuxury', 'Domino', 'Current', 'FiveThou') : 0.0,
    ('SuperLuxury', 'Domino', 'Current', 'TenThou') : 0.0,
    ('SuperLuxury', 'Domino', 'Current', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'Domino', 'Current', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'Domino', 'Current', 'Million') : 1.0,

    ('SportsCar', 'Domino', 'Older', 'FiveThou') : 0.9,
    ('SportsCar', 'Domino', 'Older', 'TenThou') : 0.06,
    ('SportsCar', 'Domino', 'Older', 'TwentyThou') : 0.02,
    ('SportsCar', 'Domino', 'Older', 'FiftyThou') : 0.01,
    ('SportsCar', 'Domino', 'Older', 'Million') : 0.01,

    ('Economy', 'Domino', 'Older', 'FiveThou') : 0.999998,
    ('Economy', 'Domino', 'Older', 'TenThou') : 0.000001,
    ('Economy', 'Domino', 'Older', 'TwentyThou') : 0.000001,
    ('Economy', 'Domino', 'Older', 'FiftyThou') : 0.0,
    ('Economy', 'Domino', 'Older', 'Million') : 0.0,

    ('FamilySedan', 'Domino', 'Older', 'FiveThou') : 0.990000,
    ('FamilySedan', 'Domino', 'Older', 'TenThou') : 0.009999,
    ('FamilySedan', 'Domino', 'Older', 'TwentyThou') : 0.000001,
    ('FamilySedan', 'Domino', 'Older', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Domino', 'Older', 'Million') : 0.0,

    ('Luxury', 'Domino', 'Older', 'FiveThou') : 0.2,
    ('Luxury', 'Domino', 'Older', 'TenThou') : 0.2,
    ('Luxury', 'Domino', 'Older', 'TwentyThou') : 0.3,
    ('Luxury', 'Domino', 'Older', 'FiftyThou') : 0.3,
    ('Luxury', 'Domino', 'Older', 'Million') : 0.0,

    ('SuperLuxury', 'Domino', 'Older', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'Domino', 'Older', 'TenThou') : 0.000001,
    ('SuperLuxury', 'Domino', 'Older', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'Domino', 'Older', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'Domino', 'Older', 'Million') : 0.999996,
})

net.P['Cushioning'] = pd.Series({
    ('True', 'EggShell', 'Poor') : 0.5,
    ('True', 'EggShell', 'Fair') : 0.3,
    ('True', 'EggShell', 'Good') : 0.2,
    ('True', 'EggShell', 'Excellent') : 0.0,
    ('True', 'Football', 'Poor') : 0.0,
    ('True', 'Football', 'Fair') : 0.1,
    ('True', 'Football', 'Good') : 0.6,
    ('True', 'Football', 'Excellent') : 0.3,
    ('True', 'Tank', 'Poor') : 0.0,
    ('True', 'Tank', 'Fair') : 0.0,
    ('True', 'Tank', 'Good') : 0.0,
    ('True', 'Tank', 'Excellent') : 1.0,

    ('False', 'EggShell', 'Poor') : 0.7,
    ('False', 'EggShell', 'Fair') : 0.3,
    ('False', 'EggShell', 'Good') : 0.0,
    ('False', 'EggShell', 'Excellent') : 0.0,
    ('False', 'Football', 'Poor') : 0.1,
    ('False', 'Football', 'Fair') : 0.6,
    ('False', 'Football', 'Good') : 0.3,
    ('False', 'Football', 'Excellent') : 0.0,
    ('False', 'Tank', 'Poor') : 0.0,
    ('False', 'Tank', 'Fair') : 0.0,
    ('False', 'Tank', 'Good') : 0.7,
    ('False', 'Tank', 'Excellent') : 0.3,

})

net.P['Accident'] = pd.Series({
    
    ('True','Poor', 'FiveThou', 'None') : 0.7,
    ('True','Poor', 'FiveThou', 'Mild') : 0.2,
    ('True','Poor', 'FiveThou', 'Moderate') : 0.07,
    ('True','Poor', 'FiveThou', 'Severe') : 0.03,
    ('False','Poor', 'FiveThou', 'None') : 0.6,
    ('False','Poor', 'FiveThou', 'Mild') : 0.2,
    ('False','Poor', 'FiveThou', 'Moderate') : 0.1,
    ('False','Poor', 'FiveThou', 'Severe') : 0.1,
    ('True','Poor', 'TwentyThou', 'None') : 0.4,
    ('True','Poor', 'TwentyThou', 'Mild') : 0.3,
    ('True','Poor', 'TwentyThou', 'Moderate') : 0.2,
    ('True','Poor', 'TwentyThou', 'Severe') : 0.1,
    ('False','Poor', 'TwentyThou', 'None') : 0.3,
    ('False','Poor', 'TwentyThou', 'Mild') : 0.2,
    ('False','Poor', 'TwentyThou', 'Moderate') : 0.2,
    ('False','Poor', 'TwentyThou', 'Severe') : 0.3,
    ('True','Poor', 'FiftyThou', 'None') : 0.3,
    ('True','Poor', 'FiftyThou', 'Mild') : 0.3,
    ('True','Poor', 'FiftyThou', 'Moderate') : 0.2,
    ('True','Poor', 'FiftyThou', 'Severe') : 0.2,
    ('False','Poor', 'FiftyThou', 'None') : 0.2,
    ('False','Poor', 'FiftyThou', 'Mild') : 0.2,
    ('False','Poor', 'FiftyThou', 'Moderate') : 0.2,
    ('False','Poor', 'FiftyThou', 'Severe') : 0.4,
    ('True','Poor', 'Domino', 'None') : 0.2,
    ('True','Poor', 'Domino', 'Mild') : 0.2,
    ('True','Poor', 'Domino', 'Moderate') : 0.3,
    ('True','Poor', 'Domino', 'Severe') : 0.3,
    ('False','Poor', 'Domino', 'None') : 0.1,
    ('False','Poor', 'Domino', 'Mild') : 0.1,
    ('False','Poor', 'Domino', 'Moderate') : 0.3,
    ('False','Poor', 'Domino', 'Severe') : 0.5,


    ('True','Normal', 'FiveThou', 'None') : 0.990,
    ('True','Normal', 'FiveThou', 'Mild') : 0.007,
    ('True','Normal', 'FiveThou', 'Moderate') : 0.002,
    ('True','Normal', 'FiveThou', 'Severe') : 0.001,
    ('False','Normal', 'FiveThou', 'None') : 0.980,
    ('False','Normal', 'FiveThou', 'Mild') : 0.01,
    ('False','Normal', 'FiveThou', 'Moderate') : 0.005,
    ('False','Normal', 'FiveThou', 'Severe') : 0.005,
    ('True','Normal', 'TwentyThou', 'None') : 0.980,
    ('True','Normal', 'TwentyThou', 'Mild') : 0.01,
    ('True','Normal', 'TwentyThou', 'Moderate') : 0.05,
    ('True','Normal', 'TwentyThou', 'Severe') : 0.05,
    ('False','Normal', 'TwentyThou', 'None') : 0.960,
    ('False','Normal', 'TwentyThou', 'Mild') : 0.020,
    ('False','Normal', 'TwentyThou', 'Moderate') : 0.015,
    ('False','Normal', 'TwentyThou', 'Severe') : 0.005,
    ('True','Normal', 'FiftyThou', 'None') : 0.970,
    ('True','Normal', 'FiftyThou', 'Mild') : 0.020,
    ('True','Normal', 'FiftyThou', 'Moderate') : 0.007,
    ('True','Normal', 'FiftyThou', 'Severe') : 0.003,
    ('False','Normal', 'FiftyThou', 'None') : 0.950,
    ('False','Normal', 'FiftyThou', 'Mild') : 0.030,
    ('False','Normal', 'FiftyThou', 'Moderate') : 0.015,
    ('False','Normal', 'FiftyThou', 'Severe') : 0.005,
    ('True','Normal', 'Domino', 'None') : 0.95,
    ('True','Normal', 'Domino', 'Mild') : 0.03,
    ('True','Normal', 'Domino', 'Moderate') : 0.01,
    ('True','Normal', 'Domino', 'Severe') : 0.01,
    ('False','Normal', 'Domino', 'None') : 0.94,
    ('False','Normal', 'Domino', 'Mild') : 0.03,
    ('False','Normal', 'Domino', 'Moderate') : 0.02,
    ('False','Normal', 'Domino', 'Severe') : 0.01,


    ('True','Excellent', 'FiveThou', 'None') : 0.999,
    ('True','Excellent', 'FiveThou', 'Mild') : 0.0007,
    ('True','Excellent', 'FiveThou', 'Moderate') : 0.0002,
    ('True','Excellent', 'FiveThou', 'Severe') : 0.0001,
    ('False','Excellent', 'FiveThou', 'None') : 0.995,
    ('False','Excellent', 'FiveThou', 'Mild') : 0.003,
    ('False','Excellent', 'FiveThou', 'Moderate') : 0.001,
    ('False','Excellent', 'FiveThou', 'Severe') : 0.001,
    ('True','Excellent', 'TwentyThou', 'None') : 0.995,
    ('True','Excellent', 'TwentyThou', 'Mild') : 0.003,
    ('True','Excellent', 'TwentyThou', 'Moderate') : 0.001,
    ('True','Excellent', 'TwentyThou', 'Severe') : 0.001,
    ('False','Excellent', 'TwentyThou', 'None') : 0.990,
    ('False','Excellent', 'TwentyThou', 'Mild') : 0.007,
    ('False','Excellent', 'TwentyThou', 'Moderate') : 0.002,
    ('False','Excellent', 'TwentyThou', 'Severe') : 0.001,
    ('True','Excellent', 'FiftyThou', 'None') : 0.990,
    ('True','Excellent', 'FiftyThou', 'Mild') : 0.007,
    ('True','Excellent', 'FiftyThou', 'Moderate') : 0.002,
    ('True','Excellent', 'FiftyThou', 'Severe') : 0.001,
    ('False','Excellent', 'FiftyThou', 'None') : 0.980,
    ('False','Excellent', 'FiftyThou', 'Mild') : 0.010,
    ('False','Excellent', 'FiftyThou', 'Moderate') : 0.005,
    ('False','Excellent', 'FiftyThou', 'Severe') : 0.005,
    ('True','Excellent', 'Domino', 'None') : 0.985,
    ('True','Excellent', 'Domino', 'Mild') : 0.010,
    ('True','Excellent', 'Domino', 'Moderate') : 0.003,
    ('True','Excellent', 'Domino', 'Severe') : 0.002,
    ('False','Excellent', 'Domino', 'None') : 0.980,
    ('False','Excellent', 'Domino', 'Mild') : 0.010,
    ('False','Excellent', 'Domino', 'Moderate') : 0.007,
    ('False','Excellent', 'Domino', 'Severe') : 0.003,
})

net.P['Theft'] = pd.Series({

    ('True', 'FiveThou', 'Secure', 'True') : 0.000001,
    ('True', 'FiveThou', 'Secure', 'False') : 0.999999,
    ('False', 'FiveThou', 'Secure', 'True') : 0.000001,
    ('False', 'FiveThou', 'Secure', 'False') : 0.999999,
    ('True', 'FiveThou', 'City', 'True') : 0.0005,
    ('True', 'FiveThou', 'City', 'False') : 0.9995,
    ('False', 'FiveThou', 'City', 'True') : 0.001,
    ('False', 'FiveThou', 'City', 'False') : 0.999,
    ('True', 'FiveThou', 'Suburb', 'True') : 0.00001,
    ('True', 'FiveThou', 'Suburb', 'False') : 0.99999,
    ('False', 'FiveThou', 'Suburb', 'True') : 0.00001,
    ('False', 'FiveThou', 'Suburb', 'False') : 0.99999,
    ('True', 'FiveThou', 'Rural', 'True') : 0.00001,
    ('True', 'FiveThou', 'Rural', 'False') : 0.99999,
    ('False', 'FiveThou', 'Rural', 'True') : 0.00001,
    ('False', 'FiveThou', 'Rural', 'False') : 0.99999,

    ('True', 'TenThou', 'Secure', 'True') : 0.000002,
    ('True', 'TenThou', 'Secure', 'False') : 0.999998,
    ('False', 'TenThou', 'Secure', 'True') : 0.000002,
    ('False', 'TenThou', 'Secure', 'False') : 0.999998,
    ('True', 'TenThou', 'City', 'True') : 0.002,
    ('True', 'TenThou', 'City', 'False') : 0.998,
    ('False', 'TenThou', 'City', 'True') : 0.005,
    ('False', 'TenThou', 'City', 'False') : 0.995,
    ('True', 'TenThou', 'Suburb', 'True') : 0.0001,
    ('True', 'TenThou', 'Suburb', 'False') : 0.9999,
    ('False', 'TenThou', 'Suburb', 'True') : 0.0002,
    ('False', 'TenThou', 'Suburb', 'False') : 0.9998,
    ('True', 'TenThou', 'Rural', 'True') : 0.00002,
    ('True', 'TenThou', 'Rural', 'False') : 0.99998,
    ('False', 'TenThou', 'Rural', 'True') : 0.0001,
    ('False', 'TenThou', 'Rural', 'False') : 0.9999,

    ('True', 'TwentyThou', 'Secure', 'True') : 0.000003,
    ('True', 'TwentyThou', 'Secure', 'False') : 0.999997,
    ('False', 'TwentyThou', 'Secure', 'True') : 0.000003,
    ('False', 'TwentyThou', 'Secure', 'False') : 0.999997,
    ('True', 'TwentyThou', 'City', 'True') : 0.005,
    ('True', 'TwentyThou', 'City', 'False') : 0.995,
    ('False', 'TwentyThou', 'City', 'True') : 0.01,
    ('False', 'TwentyThou', 'City', 'False') : 0.99,
    ('True', 'TwentyThou', 'Suburb', 'True') : 0.0003,
    ('True', 'TwentyThou', 'Suburb', 'False') : 0.9997,
    ('False', 'TwentyThou', 'Suburb', 'True') : 0.0005,
    ('False', 'TwentyThou', 'Suburb', 'False') : 0.9995,
    ('True', 'TwentyThou', 'Rural', 'True') : 0.00005,
    ('True', 'TwentyThou', 'Rural', 'False') : 0.99995,
    ('False', 'TwentyThou', 'Rural', 'True') : 0.0002,
    ('False', 'TwentyThou', 'Rural', 'False') : 0.9998,

    ('True', 'FiftyThou', 'Secure', 'True') : 0.000002,
    ('True', 'FiftyThou', 'Secure', 'False') : 0.999998,
    ('False', 'FiftyThou', 'Secure', 'True') : 0.000002,
    ('False', 'FiftyThou', 'Secure', 'False') : 0.999998,
    ('True', 'FiftyThou', 'City', 'True') : 0.005,
    ('True', 'FiftyThou', 'City', 'False') : 0.995,
    ('False', 'FiftyThou', 'City', 'True') : 0.01,
    ('False', 'FiftyThou', 'City', 'False') : 0.99,
    ('True', 'FiftyThou', 'Suburb', 'True') : 0.0003,
    ('True', 'FiftyThou', 'Suburb', 'False') : 0.9997,
    ('False', 'FiftyThou', 'Suburb', 'True') : 0.0005,
    ('False', 'FiftyThou', 'Suburb', 'False') : 0.9995,
    ('True', 'FiftyThou', 'Rural', 'True') : 0.00005,
    ('True', 'FiftyThou', 'Rural', 'False') : 0.99995,
    ('False', 'FiftyThou', 'Rural', 'True') : 0.0002,
    ('False', 'FiftyThou', 'Rural', 'False') : 0.9998,

    ('True', 'Million', 'Secure', 'True') : 0.000001,
    ('True', 'Million', 'Secure', 'False') : 0.999999,
    ('False', 'Million', 'Secure', 'True') : 0.000001,
    ('False', 'Million', 'Secure', 'False') : 0.999999,
    ('True', 'Million', 'City', 'True') : 0.000001,
    ('True', 'Million', 'City', 'False') : 0.999999,
    ('False', 'Million', 'City', 'True') : 0.000001,
    ('False', 'Million', 'City', 'False') : 0.999999,
    ('True', 'Million', 'Suburb', 'True') : 0.000001,
    ('True', 'Million', 'Suburb', 'False') : 0.999999,
    ('False', 'Million', 'Suburb', 'True') : 0.000001,
    ('False', 'Million', 'Suburb', 'False') : 0.999999,
    ('True', 'Million', 'Rural', 'True') : 0.000001,
    ('True', 'Million', 'Rural', 'False') : 0.999999,
    ('False', 'Million', 'Rural', 'True') : 0.000001,
    ('False', 'Million', 'Rural', 'False') : 0.999999,

})

net.P['OtherCarCost'] = pd.Series({
   
    ('None', 'EggShell', 'Thousand') : 1.0,
    ('None', 'EggShell', 'TenThou') : 0.0,
    ('None', 'EggShell', 'HundredThou') : 0.0,
    ('None', 'EggShell', 'Million') : 0.0,
    ('Mild', 'EggShell', 'Thousand') : 0.99000,
    ('Mild', 'EggShell', 'TenThou') : 0.00500,
    ('Mild', 'EggShell', 'HundredThou') : 0.00499,
    ('Mild', 'EggShell', 'Million') : 0.00001,
    ('Moderate', 'EggShell', 'Thousand') : 0.60000,
    ('Moderate', 'EggShell', 'TenThou') : 0.20000,
    ('Moderate', 'EggShell', 'HundredThou') : 0.19998,
    ('Moderate', 'EggShell', 'Million') : 0.00002,
    ('Severe', 'EggShell', 'Thousand') : 0.20000,
    ('Severe', 'EggShell', 'TenThou') : 0.40000,
    ('Severe', 'EggShell', 'HundredThou') : 0.39996,
    ('Severe', 'EggShell', 'Million') : 0.00004,

    ('None', 'Football', 'Thousand') : 1.0,
    ('None', 'Football', 'TenThou') : 0.0,
    ('None', 'Football', 'HundredThou') : 0.0,
    ('None', 'Football', 'Million') : 0.0,
    ('Mild', 'Football', 'Thousand') : 0.98,
    ('Mild', 'Football', 'TenThou') : 0.01,
    ('Mild', 'Football', 'HundredThou') : 0.01,
    ('Mild', 'Football', 'Million') : 0.0,
    ('Moderate', 'Football', 'Thousand') : 0.50000,
    ('Moderate', 'Football', 'TenThou') : 0.20000,
    ('Moderate', 'Football', 'HundredThou') : 0.29997,
    ('Moderate', 'Football', 'Million') : 0.00003,
    ('Severe', 'Football', 'Thousand') : 0.1,
    ('Severe', 'Football', 'TenThou') : 0.5,
    ('Severe', 'Football', 'HundredThou') : 0.39994,
    ('Severe', 'Football', 'Million') : 0.00006,

    ('None', 'Tank', 'Thousand') : 1.0,
    ('None', 'Tank', 'TenThou') : 0.0,
    ('None', 'Tank', 'HundredThou') : 0.0,
    ('None', 'Tank', 'Million') : 0.0,
    ('Mild', 'Tank', 'Thousand') : 0.95000,
    ('Mild', 'Tank', 'TenThou') : 0.03,
    ('Mild', 'Tank', 'HundredThou') : 0.01998,
    ('Mild', 'Tank', 'Million') : 0.00002,
    ('Moderate', 'Tank', 'Thousand') : 0.40000,
    ('Moderate', 'Tank', 'TenThou') : 0.30000,
    ('Moderate', 'Tank', 'HundredThou') : 0.29996,
    ('Moderate', 'Tank', 'Million') : 0.00004,
    ('Severe', 'Tank', 'Thousand') : 0.0050,
    ('Severe', 'Tank', 'TenThou') : 0.5500,
    ('Severe', 'Tank', 'HundredThou') : 0.4449,
    ('Severe', 'Tank', 'Million') : 0.0001,
})


net.P['ThisCarDam'] = pd.Series({

    ('None', 'EggShell', 'None') : 1.0,
    ('None', 'EggShell', 'Mild') : 0.0,
    ('None', 'EggShell', 'Moderate') : 0.0,
    ('None', 'EggShell', 'Severe') : 0.0,
    ('Mild', 'EggShell', 'None') : 0.001,
    ('Mild', 'EggShell', 'Mild') : 0.900,
    ('Mild', 'EggShell', 'Moderate') : 0.098,
    ('Mild', 'EggShell', 'Severe') : 0.001,
    ('Moderate', 'EggShell', 'None') : 0.000001,
    ('Moderate', 'EggShell', 'Mild') : 0.000999,
    ('Moderate', 'EggShell', 'Moderate') : 0.700000,
    ('Moderate', 'EggShell', 'Severe') : 0.299000,
    ('Severe', 'EggShell', 'None') : 0.000001,
    ('Severe', 'EggShell', 'Mild') : 0.000999,
    ('Severe', 'EggShell', 'Moderate') : 0.700000,
    ('Severe', 'EggShell', 'Severe') : 0.299000,

    ('None', 'Football', 'None') : 1.0,
    ('None', 'Football', 'Mild') : 0.0,
    ('None', 'Football', 'Moderate') : 0.0,
    ('None', 'Football', 'Severe') : 0.0,
    ('Mild', 'Football', 'None') : 0.200000,
    ('Mild', 'Football', 'Mild') : 0.750000,
    ('Mild', 'Football', 'Moderate') : 0.049999,
    ('Mild', 'Football', 'Severe') : 0.000001,
    ('Moderate', 'Football', 'None') : 0.001,
    ('Moderate', 'Football', 'Mild') : 0.099,
    ('Moderate', 'Football', 'Moderate') : 0.800,
    ('Moderate', 'Football', 'Severe') : 0.100,
    ('Severe', 'Football', 'None') : 0.000001,
    ('Severe', 'Football', 'Mild') : 0.000999,
    ('Severe', 'Football', 'Moderate') : 0.009000,
    ('Severe', 'Football', 'Severe') : 0.990000,

    ('None', 'Tank', 'None') : 1.0,
    ('None', 'Tank', 'Mild') : 0.0,
    ('None', 'Tank', 'Moderate') : 0.0,
    ('None', 'Tank', 'Severe') : 0.0,
    ('Mild', 'Tank', 'None') : 0.700000,
    ('Mild', 'Tank', 'Mild') : 0.290000,
    ('Mild', 'Tank', 'Moderate') : 0.009999,
    ('Mild', 'Tank', 'Severe') : 0.000001,
    ('Moderate', 'Tank', 'None') : 0.05,
    ('Moderate', 'Tank', 'Mild') : 0.6,
    ('Moderate', 'Tank', 'Moderate') : 0.3,
    ('Moderate', 'Tank', 'Severe') : 0.05,
    ('Severe', 'Tank', 'None') : 0.05,
    ('Severe', 'Tank', 'Mild') : 0.2,
    ('Severe', 'Tank', 'Moderate') : 0.2,
    ('Severe', 'Tank', 'Severe') : 0.55,
})

net.P['ThisCarCost'] = pd.Series({
    ('FiveThou', 'True', 'None', 'Thousand') : 0.2,
    ('FiveThou', 'True', 'None', 'TenThou') : 0.8,
    ('FiveThou', 'True', 'None', 'HundredThou') : 0.0,
    ('FiveThou', 'True', 'None', 'Million') : 0.0,
    ('FiveThou', 'True', 'Mild',  'Thousand') : 0.15,
    ('FiveThou', 'True', 'Mild',  'TenThou') : 0.85,
    ('FiveThou', 'True', 'Mild',  'HundredThou') : 0.0,
    ('FiveThou', 'True', 'Mild',  'Million') : 0.0,
    ('FiveThou', 'True','Moderate',  'Thousand') : 0.05,
    ('FiveThou', 'True','Moderate',  'TenThou') : 0.95,
    ('FiveThou', 'True','Moderate',  'HundredThou') : 0.0,
    ('FiveThou', 'True','Moderate',  'Million') : 0.0,
    ( 'FiveThou', 'True','Severe', 'Thousand') : 0.03,
    ( 'FiveThou', 'True','Severe', 'TenThou') : 0.97,
    ( 'FiveThou', 'True','Severe', 'HundredThou') : 0.0,
    ( 'FiveThou', 'True','Severe', 'Million') : 0.0,
    ('TenThou', 'True', 'None', 'Thousand') : 0.05,
    ('TenThou', 'True', 'None', 'TenThou') : 0.95,
    ('TenThou', 'True', 'None', 'HundredThou') : 0.0,
    ('TenThou', 'True', 'None', 'Million') : 0.0,
    ( 'TenThou', 'True','Mild', 'Thousand') : 0.03,
    ( 'TenThou', 'True','Mild', 'TenThou') : 0.97,
    ( 'TenThou', 'True','Mild', 'HundredThou') : 0.0,
    ( 'TenThou', 'True','Mild', 'Million') : 0.0,
    ('TenThou', 'True','Moderate',  'Thousand') : 0.01,
    ('TenThou', 'True','Moderate',  'TenThou') : 0.99,
    ('TenThou', 'True','Moderate',  'HundredThou') : 0.0,
    ('TenThou', 'True','Moderate',  'Million') : 0.0,
    ( 'TenThou', 'True','Severe', 'Thousand') : 0.000001,
    ( 'TenThou', 'True','Severe', 'TenThou') : 0.999999,
    ( 'TenThou', 'True','Severe', 'HundredThou') : 0.0,
    ( 'TenThou', 'True','Severe', 'Million') : 0.0,
    ( 'TwentyThou', 'True','None', 'Thousand') : 0.04,
    ( 'TwentyThou', 'True','None', 'TenThou') : 0.01,
    ( 'TwentyThou', 'True','None', 'HundredThou') : 0.95,
    ( 'TwentyThou', 'True','None', 'Million') : 0.0,
    ( 'TwentyThou', 'True','Mild', 'Thousand') : 0.03,
    ( 'TwentyThou', 'True','Mild', 'TenThou') : 0.02,
    ( 'TwentyThou', 'True','Mild', 'HundredThou') : 0.95,
    ( 'TwentyThou', 'True','Mild', 'Million') : 0.0,
    ('TwentyThou', 'True','Moderate',  'Thousand') : 0.001,
    ('TwentyThou', 'True','Moderate',  'TenThou') : 0.001,
    ('TwentyThou', 'True','Moderate',  'HundredThou') : 0.998,
    ('TwentyThou', 'True','Moderate',  'Million') : 0.0,
    ( 'TwentyThou', 'True', 'Severe', 'Thousand') : 0.000001,
    ( 'TwentyThou', 'True', 'Severe', 'TenThou') : 0.000001,
    ( 'TwentyThou', 'True', 'Severe', 'HundredThou') : 0.999998,
    ( 'TwentyThou', 'True', 'Severe', 'Million') : 0.0,
    ('FiftyThou', 'True', 'None',  'Thousand') : 0.04,
    ('FiftyThou', 'True', 'None',  'TenThou') : 0.01,
    ('FiftyThou', 'True', 'None',  'HundredThou') : 0.95,
    ('FiftyThou', 'True', 'None',  'Million') : 0.0,
    ( 'FiftyThou', 'True','Mild', 'Thousand') : 0.03,
    ( 'FiftyThou', 'True','Mild', 'TenThou') : 0.02,
    ( 'FiftyThou', 'True','Mild', 'HundredThou') : 0.95,
    ( 'FiftyThou', 'True','Mild', 'Million') : 0.0,
    ('FiftyThou', 'True','Moderate',  'Thousand') : 0.001,
    ('FiftyThou', 'True','Moderate',  'TenThou') : 0.001,
    ('FiftyThou', 'True','Moderate',  'HundredThou') : 0.998,
    ('FiftyThou', 'True','Moderate',  'Million') : 0.0,
    ( 'FiftyThou', 'True','Severe', 'Thousand') : 0.000001,
    ( 'FiftyThou', 'True','Severe', 'TenThou') : 0.000001,
    ( 'FiftyThou', 'True','Severe', 'HundredThou') : 0.999998,
    ( 'FiftyThou', 'True','Severe', 'Million') : 0.0,
    ('Million', 'True', 'None',  'Thousand') : 0.04,
    ('Million', 'True', 'None',  'TenThou') : 0.01,
    ('Million', 'True', 'None',  'HundredThou') : 0.2,
    ('Million', 'True', 'None',  'Million') : 0.75,
    ('Million', 'True', 'Mild',  'Thousand') : 0.02,
    ('Million', 'True', 'Mild',  'TenThou') : 0.03,
    ('Million', 'True', 'Mild',  'HundredThou') : 0.25,
    ('Million', 'True', 'Mild',  'Million') : 0.7,
    ( 'Million', 'True','Moderate', 'Thousand') : 0.001,
    ( 'Million', 'True','Moderate', 'TenThou') : 0.001,
    ( 'Million', 'True','Moderate', 'HundredThou') : 0.018,
    ( 'Million', 'True','Moderate', 'Million') : 0.980,
    ( 'Million', 'True','Severe', 'Thousand') : 0.000001,
    ( 'Million', 'True','Severe', 'TenThou') : 0.000001,
    ( 'Million', 'True','Severe', 'HundredThou') : 0.009998,
    ( 'Million', 'True','Severe', 'Million') : 0.990000,

    ('FiveThou', 'False','None',  'Thousand') : 1.0,
    ('FiveThou', 'False','None',  'TenThou') : 0.0,
    ('FiveThou', 'False','None',  'HundredThou') : 0.0,
    ('FiveThou', 'False','None',  'Million') : 0.0,
    ( 'FiveThou', 'False','Mild', 'Thousand') : 0.95,
    ( 'FiveThou', 'False','Mild', 'TenThou') : 0.05,
    ( 'FiveThou', 'False','Mild', 'HundredThou') : 0.0,
    ( 'FiveThou', 'False','Mild', 'Million') : 0.0,
    ('FiveThou', 'False','Moderate',  'Thousand') : 0.25,
    ('FiveThou', 'False','Moderate',  'TenThou') : 0.75,
    ('FiveThou', 'False','Moderate',  'HundredThou') : 0.0,
    ('FiveThou', 'False','Moderate',  'Million') : 0.0,
    ('FiveThou', 'False','Severe',  'Thousand') : 0.05,
    ('FiveThou', 'False','Severe',  'TenThou') : 0.95,
    ('FiveThou', 'False','Severe',  'HundredThou') : 0.0,
    ('FiveThou', 'False','Severe',  'Million') : 0.0,
    ( 'TenThou', 'False', 'None', 'Thousand') : 1.0,
    ( 'TenThou', 'False', 'None', 'TenThou') : 0.0,
    ( 'TenThou', 'False', 'None', 'HundredThou') : 0.0,
    ( 'TenThou', 'False', 'None', 'Million') : 0.0,
    ( 'TenThou', 'False','Mild', 'Thousand') : 0.95,
    ( 'TenThou', 'False','Mild', 'TenThou') : 0.05,
    ( 'TenThou', 'False','Mild', 'HundredThou') : 0.0,
    ( 'TenThou', 'False','Mild', 'Million') : 0.0,
    ('TenThou', 'False','Moderate',  'Thousand') : 0.15,
    ('TenThou', 'False','Moderate',  'TenThou') : 0.85,
    ('TenThou', 'False','Moderate',  'HundredThou') : 0.0,
    ('TenThou', 'False','Moderate',  'Million') : 0.0,
    ( 'TenThou', 'False','Severe', 'Thousand') : 0.01,
    ( 'TenThou', 'False','Severe', 'TenThou') : 0.99,
    ( 'TenThou', 'False','Severe', 'HundredThou') : 0.0,
    ( 'TenThou', 'False','Severe', 'Million') : 0.0,
    ('TwentyThou', 'False','None',  'Thousand') : 1.0,
    ('TwentyThou', 'False','None',  'TenThou') : 0.0,
    ('TwentyThou', 'False','None',  'HundredThou') : 0.0,
    ('TwentyThou', 'False','None',  'Million') : 0.0,
    ('TwentyThou', 'False','Mild',  'Thousand') : 0.99,
    ('TwentyThou', 'False','Mild',  'TenThou') : 0.01,
    ('TwentyThou', 'False','Mild',  'HundredThou') : 0.0,
    ('TwentyThou', 'False','Mild',  'Million') : 0.0,
    ('TwentyThou', 'False','Moderate',  'Thousand') : 0.01,
    ('TwentyThou', 'False','Moderate',  'TenThou') : 0.01,
    ('TwentyThou', 'False','Moderate',  'HundredThou') : 0.98,
    ('TwentyThou', 'False','Moderate',  'Million') : 0.0,
    ( 'TwentyThou', 'False','Severe', 'Thousand') : 0.005,
    ( 'TwentyThou', 'False','Severe', 'TenThou') : 0.005,
    ( 'TwentyThou', 'False','Severe', 'HundredThou') : 0.990,
    ( 'TwentyThou', 'False','Severe', 'Million') : 0.0,
    ('FiftyThou', 'False','None',  'Thousand') : 1.0,
    ('FiftyThou', 'False','None',  'TenThou') : 0.0,
    ('FiftyThou', 'False','None',  'HundredThou') : 0.0,
    ('FiftyThou', 'False','None',  'Million') : 0.0,
    ( 'FiftyThou', 'False','Mild', 'Thousand') : 0.99,
    ( 'FiftyThou', 'False','Mild', 'TenThou') : 0.01,
    ( 'FiftyThou', 'False','Mild', 'HundredThou') : 0.0,
    ( 'FiftyThou', 'False','Mild', 'Million') : 0.0,
    ( 'FiftyThou', 'False','Moderate', 'Thousand') : 0.005,
    ( 'FiftyThou', 'False','Moderate', 'TenThou') : 0.005,
    ( 'FiftyThou', 'False','Moderate', 'HundredThou') : 0.990,
    ( 'FiftyThou', 'False','Moderate', 'Million') : 0.0,
    ('FiftyThou', 'False', 'Severe', 'Thousand') : 0.001,
    ('FiftyThou', 'False', 'Severe', 'TenThou') : 0.001,
    ('FiftyThou', 'False', 'Severe', 'HundredThou') : 0.998,
    ('FiftyThou', 'False', 'Severe', 'Million') : 0.0,
    ('Million', 'False','None',  'Thousand') : 1.0,
    ('Million', 'False','None',  'TenThou') : 0.0,
    ('Million', 'False','None',  'HundredThou') : 0.0,
    ('Million', 'False','None',  'Million') : 0.0,
    ( 'Million', 'False','Mild', 'Thousand') : 0.98,
    ( 'Million', 'False','Mild', 'TenThou') : 0.01,
    ( 'Million', 'False','Mild', 'HundredThou') : 0.01,
    ( 'Million', 'False','Mild', 'Million') : 0.0,
    ('Million', 'False','Moderate',  'Thousand') : 0.003,
    ('Million', 'False','Moderate',  'TenThou') : 0.003,
    ('Million', 'False','Moderate',  'HundredThou') : 0.044,
    ('Million', 'False','Moderate',  'Million') : 0.950,
    ( 'Million', 'False','Severe', 'Thousand') : 0.000001,
    ( 'Million', 'False','Severe', 'TenThou') : 0.000001,
    ( 'Million', 'False','Severe', 'HundredThou') : 0.029998,
    ( 'Million', 'False','Severe', 'Million') : 0.970000,

})


net.P['PropCost'] = pd.Series({

    ('Thousand', 'Thousand', 'Thousand'): 0.7,
    ('Thousand', 'Thousand', 'TenThou'): 0.3,
    ('Thousand', 'Thousand', 'HundredThou'): 0.0,
    ('Thousand', 'Thousand', 'Million'): 0.0,
    ('TenThou', 'Thousand', 'Thousand'): 0.0,
    ('TenThou', 'Thousand', 'TenThou'): 0.95,
    ('TenThou', 'Thousand', 'HundredThou'): 0.05,
    ('TenThou', 'Thousand', 'Million'): 0.0,
    ('HundredThou', 'Thousand', 'Thousand'): 0.0,
    ('HundredThou', 'Thousand', 'TenThou'): 0.0,
    ('HundredThou', 'Thousand', 'HundredThou'): 0.98,
    ('HundredThou', 'Thousand', 'Million'): 0.02,
    ('Million', 'Thousand', 'Thousand'): 0.0,
    ('Million', 'Thousand', 'TenThou'): 0.0,
    ('Million', 'Thousand', 'HundredThou'): 0.0,
    ('Million', 'Thousand', 'Million'): 1.0,

    ('Thousand', 'TenThou', 'Thousand'): 0.0,
    ('Thousand', 'TenThou', 'TenThou'): 0.95,
    ('Thousand', 'TenThou', 'HundredThou'): 0.05,
    ('Thousand', 'TenThou', 'Million'): 0.0,
    ('TenThou', 'TenThou', 'Thousand'): 0.0,
    ('TenThou', 'TenThou', 'TenThou'): 0.6,
    ('TenThou', 'TenThou', 'HundredThou'): 0.4,
    ('TenThou', 'TenThou', 'Million'): 0.0,
    ('HundredThou', 'TenThou', 'Thousand'): 0.0,
    ('HundredThou', 'TenThou', 'TenThou'): 0.0,
    ('HundredThou', 'TenThou', 'HundredThou'): 0.8,
    ('HundredThou', 'TenThou', 'Million'): 0.2,
    ('Million', 'TenThou', 'Thousand'): 0.0,
    ('Million', 'TenThou', 'TenThou'): 0.0,
    ('Million', 'TenThou', 'HundredThou'): 0.0,
    ('Million', 'TenThou', 'Million'): 1.0,

    ('Thousand', 'HundredThou', 'Thousand'): 0.0,
    ('Thousand', 'HundredThou', 'TenThou'): 0.0,
    ('Thousand', 'HundredThou', 'HundredThou'): 0.98,
    ('Thousand', 'HundredThou', 'Million'): 0.02,
    ('TenThou', 'HundredThou', 'Thousand'): 0.0,
    ('TenThou', 'HundredThou', 'TenThou'): 0.0,
    ('TenThou', 'HundredThou', 'HundredThou'): 0.95,
    ('TenThou', 'HundredThou', 'Million'): 0.05,
    ('HundredThou', 'HundredThou', 'Thousand'): 0.0,
    ('HundredThou', 'HundredThou', 'TenThou'): 0.0,
    ('HundredThou', 'HundredThou', 'HundredThou'): 0.6,
    ('HundredThou', 'HundredThou', 'Million'): 0.4,
    ('Million', 'HundredThou', 'Thousand'): 0.0,
    ('Million', 'HundredThou', 'TenThou'): 0.0,
    ('Million', 'HundredThou', 'HundredThou'): 0.0,
    ('Million', 'HundredThou', 'Million'): 1.0,

    ('Thousand', 'Million', 'Thousand'): 0.0,
    ('Thousand', 'Million', 'TenThou'): 0.0,
    ('Thousand', 'Million', 'HundredThou'): 0.0,
    ('Thousand', 'Million', 'Million'): 1.0,
    ('TenThou', 'Million', 'Thousand'): 0.0,
    ('TenThou', 'Million', 'TenThou'): 0.0,
    ('TenThou', 'Million', 'HundredThou'): 0.0,
    ('TenThou', 'Million', 'Million'): 1.0,
    ('HundredThou', 'Million', 'Thousand'): 0.0,
    ('HundredThou', 'Million', 'TenThou'): 0.0,
    ('HundredThou', 'Million', 'HundredThou'): 0.0,
    ('HundredThou', 'Million', 'Million'): 1.0,
    ('Million', 'Million', 'Thousand'): 0.0,
    ('Million', 'Million', 'TenThou'): 0.0,
    ('Million', 'Million', 'HundredThou'): 0.0,
    ('Million', 'Million', 'Million'): 1.0,
})

net.P['MedCost'] = pd.Series({

    ('None', 'Adolescent', 'Poor', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Poor', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Poor', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Poor', 'Thousand'): 0.96,
    ('Mild', 'Adolescent', 'Poor', 'TenThou'): 0.03,
    ('Mild', 'Adolescent', 'Poor', 'HundredThou'): 0.009,
    ('Mild', 'Adolescent', 'Poor', 'Million'): 0.001,
    ('Moderate', 'Adolescent', 'Poor', 'Thousand'): 0.5,
    ('Moderate', 'Adolescent', 'Poor', 'TenThou'): 0.2,
    ('Moderate', 'Adolescent', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Adolescent', 'Poor', 'Million'): 0.1,
    ('Severe', 'Adolescent', 'Poor', 'Thousand'): 0.3,
    ('Severe', 'Adolescent', 'Poor', 'TenThou'): 0.3,
    ('Severe', 'Adolescent', 'Poor', 'HundredThou'): 0.2,
    ('Severe', 'Adolescent', 'Poor', 'Million'): 0.2,
    ('None', 'Adult', 'Poor', 'Thousand'): 1.0,
    ('None', 'Adult', 'Poor', 'TenThou'): 0.0,
    ('None', 'Adult', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Poor', 'Million'): 0.0,
    ('Mild', 'Adult', 'Poor', 'Thousand'): 0.96,
    ('Mild', 'Adult', 'Poor', 'TenThou'): 0.03,
    ('Mild', 'Adult', 'Poor', 'HundredThou'): 0.009,
    ('Mild', 'Adult', 'Poor', 'Million'): 0.001,
    ('Moderate', 'Adult', 'Poor', 'Thousand'): 0.5,
    ('Moderate', 'Adult', 'Poor', 'TenThou'): 0.2,
    ('Moderate', 'Adult', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Adult', 'Poor', 'Million'): 0.1,
    ('Severe', 'Adult', 'Poor', 'Thousand'): 0.3,
    ('Severe', 'Adult', 'Poor', 'TenThou'): 0.3,
    ('Severe', 'Adult', 'Poor', 'HundredThou'): 0.2,
    ('Severe', 'Adult', 'Poor', 'Million'): 0.2,
    ('None', 'Senior', 'Poor', 'Thousand'): 1.0,
    ('None', 'Senior', 'Poor', 'TenThou'): 0.0,
    ('None', 'Senior', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Poor', 'Million'): 0.0,
    ('Mild', 'Senior', 'Poor', 'Thousand'): 0.9,
    ('Mild', 'Senior', 'Poor', 'TenThou'): 0.07,
    ('Mild', 'Senior', 'Poor', 'HundredThou'): 0.02,
    ('Mild', 'Senior', 'Poor', 'Million'): 0.01,
    ('Moderate', 'Senior', 'Poor', 'Thousand'): 0.3,
    ('Moderate', 'Senior', 'Poor', 'TenThou'): 0.3,
    ('Moderate', 'Senior', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Senior', 'Poor', 'Million'): 0.2,
    ('Severe', 'Senior', 'Poor', 'Thousand'): 0.2,
    ('Severe', 'Senior', 'Poor', 'TenThou'): 0.2,
    ('Severe', 'Senior', 'Poor', 'HundredThou'): 0.3,
    ('Severe', 'Senior', 'Poor', 'Million'): 0.3,


    ('None', 'Adolescent', 'Excellent', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Excellent', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Excellent', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Excellent', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Excellent', 'Thousand'): 0.999000,
    ('Mild', 'Adolescent', 'Excellent', 'TenThou'): 0.00099,
    ('Mild', 'Adolescent', 'Excellent', 'HundredThou'): 0.000009,
    ('Mild', 'Adolescent', 'Excellent', 'Million'): 0.000001,
    ('Moderate', 'Adolescent', 'Excellent', 'Thousand'): 0.990,
    ('Moderate', 'Adolescent', 'Excellent', 'TenThou'): 0.007,
    ('Moderate', 'Adolescent', 'Excellent', 'HundredThou'): 0.002,
    ('Moderate', 'Adolescent', 'Excellent', 'Million'): 0.001,
    ('Severe', 'Adolescent', 'Excellent', 'Thousand'): 0.95,
    ('Severe', 'Adolescent', 'Excellent', 'TenThou'): 0.03,
    ('Severe', 'Adolescent', 'Excellent', 'HundredThou'): 0.01,
    ('Severe', 'Adolescent', 'Excellent', 'Million'): 0.01,
    ('None', 'Adult', 'Excellent', 'Thousand'): 1.0,
    ('None', 'Adult', 'Excellent', 'TenThou'): 0.0,
    ('None', 'Adult', 'Excellent', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Excellent', 'Million'): 0.0,
    ('Mild', 'Adult', 'Excellent', 'Thousand'): 0.999000,
    ('Mild', 'Adult', 'Excellent', 'TenThou'): 0.000990,
    ('Mild', 'Adult', 'Excellent', 'HundredThou'): 0.000009,
    ('Mild', 'Adult', 'Excellent', 'Million'): 0.000001,
    ('Moderate', 'Adult', 'Excellent', 'Thousand'): 0.990,
    ('Moderate', 'Adult', 'Excellent', 'TenThou'): 0.007,
    ('Moderate', 'Adult', 'Excellent', 'HundredThou'): 0.002,
    ('Moderate', 'Adult', 'Excellent', 'Million'): 0.001,
    ('Severe', 'Adult', 'Excellent', 'Thousand'): 0.95,
    ('Severe', 'Adult', 'Excellent', 'TenThou'): 0.03,
    ('Severe', 'Adult', 'Excellent', 'HundredThou'): 0.01,
    ('Severe', 'Adult', 'Excellent', 'Million'): 0.01,
    ('None', 'Senior', 'Excellent', 'Thousand'): 1.0,
    ('None', 'Senior', 'Excellent', 'TenThou'): 0.0,
    ('None', 'Senior', 'Excellent', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Excellent', 'Million'): 0.0,
    ('Mild', 'Senior', 'Excellent', 'Thousand'): 0.99,
    ('Mild', 'Senior', 'Excellent', 'TenThou'): 0.007,
    ('Mild', 'Senior', 'Excellent', 'HundredThou'): 0.002,
    ('Mild', 'Senior', 'Excellent', 'Million'): 0.001,
    ('Moderate', 'Senior', 'Excellent', 'Thousand'): 0.95,
    ('Moderate', 'Senior', 'Excellent', 'TenThou'): 0.03,
    ('Moderate', 'Senior', 'Excellent', 'HundredThou'): 0.01,
    ('Moderate', 'Senior', 'Excellent', 'Million'): 0.01,
    ('Severe', 'Senior', 'Excellent', 'Thousand'): 0.90,
    ('Severe', 'Senior', 'Excellent', 'TenThou'): 0.05,
    ('Severe', 'Senior', 'Excellent', 'HundredThou'): 0.03,
    ('Severe', 'Senior', 'Excellent', 'Million'): 0.02,

    ('None', 'Adolescent', 'Fair', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Fair', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Fair', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Fair', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Fair', 'Thousand'): 0.98,
    ('Mild', 'Adolescent', 'Fair', 'TenThou'): 0.019,
    ('Mild', 'Adolescent', 'Fair', 'HundredThou'): 0.0009,
    ('Mild', 'Adolescent', 'Fair', 'Million'): 0.0001,
    ('Moderate', 'Adolescent', 'Fair', 'Thousand'): 0.80,
    ('Moderate', 'Adolescent', 'Fair', 'TenThou'): 0.15,
    ('Moderate', 'Adolescent', 'Fair', 'HundredThou'): 0.03,
    ('Moderate', 'Adolescent', 'Fair', 'Million'): 0.02,
    ('Severe', 'Adolescent', 'Fair', 'Thousand'): 0.5,
    ('Severe', 'Adolescent', 'Fair', 'TenThou'): 0.2,
    ('Severe', 'Adolescent', 'Fair', 'HundredThou'): 0.2,
    ('Severe', 'Adolescent', 'Fair', 'Million'): 0.1,
    ('None', 'Adult', 'Fair', 'Thousand'): 1.0,
    ('None', 'Adult', 'Fair', 'TenThou'): 0.0,
    ('None', 'Adult', 'Fair', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Fair', 'Million'): 0.0,
    ('Mild', 'Adult', 'Fair', 'Thousand'): 0.98,
    ('Mild', 'Adult', 'Fair', 'TenThou'): 0.019,
    ('Mild', 'Adult', 'Fair', 'HundredThou'): 0.0009,
    ('Mild', 'Adult', 'Fair', 'Million'): 0.0001,
    ('Moderate', 'Adult', 'Fair', 'Thousand'): 0.8,
    ('Moderate', 'Adult', 'Fair', 'TenThou'): 0.15,
    ('Moderate', 'Adult', 'Fair', 'HundredThou'): 0.03,
    ('Moderate', 'Adult', 'Fair', 'Million'): 0.02,
    ('Severe', 'Adult', 'Fair', 'Thousand'): 0.5,
    ('Severe', 'Adult', 'Fair', 'TenThou'): 0.2,
    ('Severe', 'Adult', 'Fair', 'HundredThou'): 0.2,
    ('Severe', 'Adult', 'Fair', 'Million'): 0.1,
    ('None', 'Senior', 'Fair', 'Thousand'): 1.0,
    ('None', 'Senior', 'Fair', 'TenThou'): 0.0,
    ('None', 'Senior', 'Fair', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Fair', 'Million'): 0.0,
    ('Mild', 'Senior', 'Fair', 'Thousand'): 0.950,
    ('Mild', 'Senior', 'Fair', 'TenThou'): 0.040,
    ('Mild', 'Senior', 'Fair', 'HundredThou'): 0.0007,
    ('Mild', 'Senior', 'Fair', 'Million'): 0.003,
    ('Moderate', 'Senior', 'Fair', 'Thousand'): 0.5,
    ('Moderate', 'Senior', 'Fair', 'TenThou'): 0.2,
    ('Moderate', 'Senior', 'Fair', 'HundredThou'): 0.2,
    ('Moderate', 'Senior', 'Fair', 'Million'): 0.1,
    ('Severe', 'Senior', 'Fair', 'Thousand'): 0.3,
    ('Severe', 'Senior', 'Fair', 'TenThou'): 0.3,
    ('Severe', 'Senior', 'Fair', 'HundredThou'): 0.2,
    ('Severe', 'Senior', 'Fair', 'Million'): 0.2,

    ('None', 'Adolescent', 'Good', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Good', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Good', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Good', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Good', 'Thousand'): 0.99,
    ('Mild', 'Adolescent', 'Good', 'TenThou'): 0.0099,
    ('Mild', 'Adolescent', 'Good', 'HundredThou'): 0.00009,
    ('Mild', 'Adolescent', 'Good', 'Million'): 0.00001,
    ('Moderate', 'Adolescent', 'Good', 'Thousand'): 0.95,
    ('Moderate', 'Adolescent', 'Good', 'TenThou'): 0.02,
    ('Moderate', 'Adolescent', 'Good', 'HundredThou'): 0.02,
    ('Moderate', 'Adolescent', 'Good', 'Million'): 0.01,
    ('Severe', 'Adolescent', 'Good', 'Thousand'): 0.9,
    ('Severe', 'Adolescent', 'Good', 'TenThou'): 0.07,
    ('Severe', 'Adolescent', 'Good', 'HundredThou'): 0.02,
    ('Severe', 'Adolescent', 'Good', 'Million'): 0.01,
    ('None', 'Adult', 'Good', 'Thousand'): 1.0,
    ('None', 'Adult', 'Good', 'TenThou'): 0.0,
    ('None', 'Adult', 'Good', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Good', 'Million'): 0.0,
    ('Mild', 'Adult', 'Good', 'Thousand'): 0.99,
    ('Mild', 'Adult', 'Good', 'TenThou'): 0.0099,
    ('Mild', 'Adult', 'Good', 'HundredThou'): 0.00009,
    ('Mild', 'Adult', 'Good', 'Million'): 0.00001,
    ('Moderate', 'Adult', 'Good', 'Thousand'): 0.95,
    ('Moderate', 'Adult', 'Good', 'TenThou'): 0.02,
    ('Moderate', 'Adult', 'Good', 'HundredThou'): 0.02,
    ('Moderate', 'Adult', 'Good', 'Million'): 0.01,
    ('Severe', 'Adult', 'Good', 'Thousand'): 0.9,
    ('Severe', 'Adult', 'Good', 'TenThou'): 0.07,
    ('Severe', 'Adult', 'Good', 'HundredThou'): 0.02,
    ('Severe', 'Adult', 'Good', 'Million'): 0.01,
    ('None', 'Senior', 'Good', 'Thousand'): 1.0,
    ('None', 'Senior', 'Good', 'TenThou'): 0.0,
    ('None', 'Senior', 'Good', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Good', 'Million'): 0.0,
    ('Mild', 'Senior', 'Good', 'Thousand'): 0.97,
    ('Mild', 'Senior', 'Good', 'TenThou'): 0.025,
    ('Mild', 'Senior', 'Good', 'HundredThou'): 0.003,
    ('Mild', 'Senior', 'Good', 'Million'): 0.002,
    ('Moderate', 'Senior', 'Good', 'Thousand'): 0.9,
    ('Moderate', 'Senior', 'Good', 'TenThou'): 0.07,
    ('Moderate', 'Senior', 'Good', 'HundredThou'): 0.02,
    ('Moderate', 'Senior', 'Good', 'Million'): 0.01,
    ('Severe', 'Senior', 'Good', 'Thousand'): 0.6,
    ('Severe', 'Senior', 'Good', 'TenThou'): 0.3,
    ('Severe', 'Senior', 'Good', 'HundredThou'): 0.07,
    ('Severe', 'Senior', 'Good', 'Million'): 0.03,
})

net.P['ILiCost'] = pd.Series({

    ('None', 'Thousand'): 1.0,
    ('None', 'TenThou'): 0.0,
    ('None', 'HundredThou'): 0.0,
    ('None', 'Million'): 0.0,

    ('Mild', 'Thousand'): 0.999000,
    ('Mild', 'TenThou'): 0.000998,
    ('Mild', 'HundredThou'): 0.000001,
    ('Mild', 'Million'): 0.000001,

    ('Moderate', 'Thousand'): 0.9,
    ('Moderate', 'TenThou'): 0.05,
    ('Moderate', 'HundredThou'): 0.03,
    ('Moderate', 'Million'): 0.02,

    ('Severe', 'Thousand'): 0.8,
    ('Severe', 'TenThou'): 0.1,
    ('Severe', 'HundredThou'): 0.06,
    ('Severe', 'Million'): 0.04,

})

net.P['DrivHist'] = pd.Series({

    ('Substandard', 'Psychopath', 'Zero'): 0.001,
    ('Substandard', 'Psychopath', 'One'): 0.0004,
    ('Substandard', 'Psychopath', 'Many'): 0.995,
    ('Normal', 'Psychopath', 'Zero'): 0.1,
    ('Normal', 'Psychopath', 'One'): 0.3,
    ('Normal', 'Psychopath', 'Many'): 0.6,
    ('Expert', 'Psychopath', 'Zero'): 0.3,
    ('Expert', 'Psychopath', 'One'): 0.3,
    ('Expert', 'Psychopath', 'Many'): 0.4,

    ('Substandard', 'Adventurous', 'Zero'): 0.002,
    ('Substandard', 'Adventurous', 'One'): 0.008,
    ('Substandard', 'Adventurous', 'Many'): 0.990,
    ('Normal', 'Adventurous', 'Zero'): 0.5,
    ('Normal', 'Adventurous', 'One'): 0.3,
    ('Normal', 'Adventurous', 'Many'): 0.2,
    ('Expert', 'Adventurous', 'Zero'): 0.6,
    ('Expert', 'Adventurous', 'One'): 0.3,
    ('Expert', 'Adventurous', 'Many'): 0.1,

    ('Substandard', 'Normal', 'Zero'): 0.03,
    ('Substandard', 'Normal', 'One'): 0.15,
    ('Substandard', 'Normal', 'Many'): 0.82,
    ('Normal', 'Normal', 'Zero'): 0.9,
    ('Normal', 'Normal', 'One'): 0.07,
    ('Normal', 'Normal', 'Many'): 0.03,
    ('Expert', 'Normal', 'Zero'): 0.990000,
    ('Expert', 'Normal', 'One'): 0.009999,
    ('Expert', 'Normal', 'Many'): 0.000001,

    ('Substandard', 'Cautious', 'Zero'): 0.3,
    ('Substandard', 'Cautious', 'One'): 0.3,
    ('Substandard', 'Cautious', 'Many'): 0.4,
    ('Normal', 'Cautious', 'Zero'): 0.95,
    ('Normal', 'Cautious', 'One'): 0.04,
    ('Normal', 'Cautious', 'Many'): 0.01,
    ('Expert', 'Cautious', 'Zero'): 0.999998,
    ('Expert', 'Cautious', 'One'): 0.000001,
    ('Expert', 'Cautious', 'Many'): 0.000001,
})


Insurance_Network = net