# This file contains an example BN for testing
import sorobn as sbn
import pandas as pd 

# first define network structure
net = sbn.BayesNet(
    ('Age', ['SocioEcon', 'RiskAversion', 'GoodStudent', 'SeniorTrain', 'DrivingSkill', 'MedCost']),
    ('SocioEcon', ['GoodStudent', 'RiskAversion','MakeModel', 'OtherCar', 'VehicleYear', 'HomeBase','AntiTheft']),
    ('RiskAversion', ['SeniorTrain', 'DrivHist', 'DrivQuality', 'MakeModel', 'VehicleYear','HomeBase', 'AntiTheft']),
    ('SeniorTrain', 'DrivingSkill'),
    ('HomeBase','Theft'),
    ('AntiTheft','Theft'),
    ('DrivingSkill',['DrivHist','DrivQuality']),
    ('DrivQuality','Accident'),
    ('MakeModel',['Airbag','Antilock','RuggedAuto','CarValue']),
    ('VehicleYear',['Airbag','Antilock','RuggedAuto','CarValue']),
    ('Mileage',['CarValue','Accident']),
    ('Airbag','Cushioning'),
    ('Antilock','Accident'),
    ('RuggedAuto',['Cushioning','OtherCarCost','ThisCarDam']),
    ('CarValue',['ThisCarCost','Theft']),
    ('Cushioning','MedCost'),
    ('Accident',['MedCost','ILiCost','OtherCarCost', 'ThisCarDam']),
    ('Theft','ThisCarCost'),
    ('OtherCarCost','PropCost'),
    ('ThisCarDam','ThisCarCost'),
    ('ThisCarCost','PropCost'),

)


# next define conditional probabilities
net.P['Age'] = pd.Series({'Adolescent': 0.2, 'Adult': 0.6, 'Senior': 0.2})
net.P['SocioEcon'] = pd.Series({
    #(Age, SE)
    ('Adolescent', 'Prole'): 0.4,
    ('Adolescent', 'Middle'): 0.4,
    ('Adolescent', 'UpperMiddle'): 0.19,
    ('Adolescent', 'Wealthy'): 0.01,
    ('Adult', 'Prole'): 0.4,
    ('Adult', 'Middle'): 0.4,
    ('Adult', 'UpperMiddle'): 0.19,
    ('Adult', 'Wealthy'): 0.01,
    ('Senior', 'Prole'): 0.5,
    ('Senior', 'Middle'): 0.2,
    ('Senior', 'UpperMiddle'): 0.29,
    ('Senior', 'Wealthy'): 0.01,
})

net.P['OtherCar'] = pd.Series({
    #SE, OtherCar
    ('Prole', 'True'): 0.5,
    ('Prole', 'False'): 0.5,
    ('Middle', 'True'): 0.8,
    ('Middle', 'Faalse'): 0.2,
    ('UpperMiddle', 'True'): 0.9,
    ('UpperMiddle', 'False'): 0.1,
    ('Wealthy', 'True'): 0.95,
    ('Wealthy', 'Faalse'): 0.05,
})

net.P['GoodStudent'] = pd.Series({
    # SE, AGe
    ('Prole', 'Adolescent', 'True'): 0.1,
    ('Prole', 'Adolescent', 'False'): 0.9,
    ('Middle', 'Adolescent', 'True'): 0.2,
    ('Middle', 'Adolescent', 'False'): 0.8,
    ('UpperMiddle', 'Adolescent', 'True'): 0.5,
    ('UpperMiddle', 'Adolescent', 'False'): 0.5,
    ('Wealthy', 'Adolescent', 'True'): 0.4,
    ('Wealthy', 'Adolescent', 'False'): 0.6,

    ('Prole', 'Adult', 'True'): 0.0,
    ('Prole', 'Adult', 'False'): 1.0,
    ('Middle', 'Adult', 'True'): 0.0,
    ('Middle', 'Adult', 'False'): 1.0,
    ('UpperMiddle', 'Adult', 'True'): 0.0,
    ('UpperMiddle', 'Adult', 'False'): 1.0,
    ('Wealthy', 'Adult', 'True'): 0.0,
    ('Wealthy', 'Adult', 'False'): 1.0,

    ('Prole', 'Senior', 'True'): 0.0,
    ('Prole', 'Senior', 'False'): 1.0,
    ('Middle', 'Senior', 'True'): 0.0,
    ('Middle', 'Senior', 'False'): 1.0,
    ('UpperMiddle', 'Senior', 'True'): 0.0,
    ('UpperMiddle', 'Senior', 'False'): 1.0,
    ('Wealthy', 'Senior', 'True'): 0.0,
    ('Wealthy', 'Senior', 'False'): 1.0,
})
net.P['RiskAversion'] = pd.Series({
    #(Age, SE, RA)
    ('Adolescent', 'Prole', 'Psychopath'): 0.02,
    ('Adolescent', 'Prole', 'Adventurous'): 0.58,
    ('Adolescent', 'Prole', 'Normal'): 0.3,
    ('Adolescent', 'Prole', 'Cautious'): 0.1, 
    ('Adolescent', 'Middle','Psychopath'): 0.02,
    ('Adolescent', 'Middle','Adventurous'): 0.38,
    ('Adolescent', 'Middle','Normal'): 0.5,
    ('Adolescent', 'Middle','Cautious'): 0.1, 
    ('Adolescent', 'UpperMiddle','Psychopatah'): 0.02,
    ('Adolescent', 'UpperMiddle','Adventurous'): 0.48,
    ('Adolescent', 'UpperMiddle','Normal'): 0.40,
    ('Adolescent', 'UpperMiddle','Cautious'): 0.10,
    ('Adolescent', 'Wealthy', 'Psychopath'): 0.02,
    ('Adolescent', 'Wealthy', 'Adventurous'): 0.58,
    ('Adolescent', 'Wealthy', 'Normal'): 0.3,
    ('Adolescent', 'Wealthy', 'Cautious'): 0.1,

    ('Adult', 'Prole','Psychopath'): 0.015,
    ('Adult', 'Prole','Adventurous'): 0.285,
    ('Adult', 'Prole','Normal'): 0.5,
    ('Adult', 'Prole','Cautious'): 0.2, 
    ('Adult', 'Middle','Psychopath'): 0.015,
    ('Adult', 'Middle','Adventurous'): 0.185,
    ('Adult', 'Middle','Normal'): 0.6,
    ('Adult', 'Middle','Cautious'): 0.2,
    ('Adult', 'UpperMiddle','Psychopatah'): 0.015,
    ('Adult', 'UpperMiddle','Adventurous'): 0.285,
    ('Adult', 'UpperMiddle','Normal'): 0.50,
    ('Adult', 'UpperMiddle','Cautious'): 0.20,
    ('Adult', 'Wealthy', 'Psychopath'): 0.015,
    ('Adult', 'Wealthy', 'Adventurous'): 0.285,
    ('Adult', 'Wealthy', 'Normal'): 0.4,
    ('Adult', 'Wealthy', 'Cautious'): 0.3,

    ('Senior', 'Prole', 'Psychopath'): 0.01,
    ('Senior', 'Prole', 'Adventurous'): 0.09,
    ('Senior', 'Prole', 'Normal'): 0.4,
    ('Senior', 'Prole', 'Cautious'): 0.5, #good
    ('Senior', 'Middle','Psychopath'): 0.01,
    ('Senior', 'Middle','Adventurous'): 0.04,
    ('Senior', 'Middle','Normal'): 0.35,
    ('Senior', 'Middle','Cautious'): 0.60,
    ('Senior', 'UpperMiddle','Psychopatah'): 0.01,
    ('Senior', 'UpperMiddle','Adventurous'): 0.09,
    ('Senior', 'UpperMiddle','Normal'): 0.40,
    ('Senior', 'UpperMiddle','Cautious'): 0.50,
    ('Senior', 'Wealthy', 'Psychopath'): 0.01,
    ('Senior', 'Wealthy', 'Adventurous'): 0.09,
    ('Senior', 'Wealthy', 'Normal'): 0.4,
    ('Senior', 'Wealthy', 'Cautious'): 0.5,
})

net.P['SeniorTrain'] = pd.Series({
    # Age, RA, ST
    ('Adolescent','Psychopath','True'): 0.0,
    ('Adolescent','Psychopath','False'): 1.0,
    ('Adult','Psychopath','True'): 0.0,
    ('Adult','Psychopath','False'): 1.0,
    ('Senior','Psychopath','True'): 0.000001,
    ('Senior','Psychopath','False'): 0.999999,

    ('Adolescent','Adventurous','True'): 0.0,
    ('Adolescent','Adventurous','False'): 1.0,
    ('Adult','Adventurous','True'): 0.0,
    ('Adult','Adventurous','False'): 1.0,
    ('Senior','Adventurous','True'): 0.000001,
    ('Senior','Adventurous','False'): 0.999999,


    ('Adolescent','Normal','True'): 0.0,
    ('Adolescent','Normal','False'): 1.0,
    ('Adult','Normal','True'): 0.0,
    ('Adult','Normal','False'): 1.0,
    ('Senior','Normal','True'): 0.3,
    ('Senior','Normal','False'): 0.7,

    ('Adolescent','Cautious','True'): 0.0,
    ('Adolescent','Cautious','False'): 1.0,
    ('Adult','Cautious','True'): 0.0,
    ('Adult','Cautious','False'): 1.0,
    ('Senior','Cautious','True'): 0.9,
    ('Senior','Cautious','False'): 0.1,
})

net.P['HomeBase'] = pd.Series({
    # RA, SE, HB
    ('Psychopath', 'Prole', 'Secure') : 0.000001,
    ('Psychopath', 'Prole', 'City') : 0.8,
    ('Psychopath', 'Prole', 'Suburb') : 0.049999,
    ('Psychopath', 'Prole', 'Rural') : 0.15,

    ('Adventurous', 'Prole', 'Secure') : 0.000001,
    ('Adventurous', 'Prole', 'City') : 0.8,
    ('Adventurous', 'Prole', 'Suburb') : 0.05,
    ('Adventurous', 'Prole', 'Rural') : 0.149999,

    ('Normal', 'Prole', 'Secure') : 0.000001,
    ('Normal', 'Prole', 'City') : 0.8,
    ('Normal', 'Prole', 'Suburb') : 0.05,
    ('Normal', 'Prole', 'Rural') : 0.149999,

    ('Cautious', 'Prole', 'Secure') : 0.000001,
    ('Cautious', 'Prole', 'City') : 0.8,
    ('Cautious', 'Prole', 'Suburb') : 0.05,
    ('Cautious', 'Prole', 'Rural') : 0.149999,

    ('Psychopath', 'Middle', 'Secure') : 0.15,
    ('Psychopath', 'Middle', 'City') : 0.8,
    ('Psychopath', 'Middle', 'Suburb') : 0.04,
    ('Psychopath', 'Middle', 'Rural') : 0.01,

    ('Adventurous', 'Middle', 'Secure') : 0.01,
    ('Adventurous', 'Middle', 'City') : 0.25,
    ('Adventurous', 'Middle', 'Suburb') : 0.6,
    ('Adventurous', 'Middle', 'Rural') : 0.14,

    ('Normal', 'Middle', 'Secure') : 0.299999,
    ('Normal', 'Middle', 'City') : 0.000001,
    ('Normal', 'Middle', 'Suburb') : 0.6,
    ('Normal', 'Middle', 'Rural') : 0.1,

    ('Cautious', 'Middle', 'Secure') : 0.95,
    ('Cautious', 'Middle', 'City') : 0.000001,
    ('Cautious', 'Middle', 'Suburb') : 0.024445,
    ('Cautious', 'Middle', 'Rural') : 0.025554,

    
    ('Psychopath', 'UpperMiddle', 'Secure') : 0.35,
    ('Psychopath', 'UpperMiddle', 'City') : 0.6,
    ('Psychopath', 'UpperMiddle', 'Suburb') : 0.04,
    ('Psychopath', 'UpperMiddle', 'Rural') : 0.01,

    ('Adventurous', 'UpperMiddle', 'Secure') : 0.2,
    ('Adventurous', 'UpperMiddle', 'City') : 0.4,
    ('Adventurous', 'UpperMiddle', 'Suburb') : 0.3,
    ('Adventurous', 'UpperMiddle', 'Rural') : 0.1,

    ('Normal', 'UpperMiddle', 'Secure') : 0.5,
    ('Normal', 'UpperMiddle', 'City') : 0.000001,
    ('Normal', 'UpperMiddle', 'Suburb') : 0.4,
    ('Normal', 'UpperMiddle', 'Rural') : 0.099999,

    ('Cautious', 'UpperMiddle', 'Secure') : 0.999997,
    ('Cautious', 'UpperMiddle', 'City') : 0.000001,
    ('Cautious', 'UpperMiddle', 'Suburb') : 0.000001,
    ('Cautious', 'UpperMiddle', 'Rural') : 0.000001,

    ('Psychopath', 'Wealthy', 'Secure') : 0.489999,
    ('Psychopath', 'Wealthy', 'City') : 0.5,
    ('Psychopath', 'Wealthy', 'Suburb') : 0.000001,
    ('Psychopath', 'Wealthy', 'Rural') : 0.010000,

    ('Adventurous', 'Wealthy', 'Secure') : 0.950000,
    ('Adventurous', 'Wealthy', 'City') : 0.000001,
    ('Adventurous', 'Wealthy', 'Suburb') : 0.000001,
    ('Adventurous', 'Wealthy', 'Rural') : 0.489999,

    ('Normal', 'Wealthy', 'Secure') : 0.850000,
    ('Normal', 'Wealthy', 'City') : 0.000001,
    ('Normal', 'Wealthy', 'Suburb') : 0.001000,
    ('Normal', 'Wealthy', 'Rural') : 0.148999,

    ('Cautious', 'Wealthy', 'Secure') : 0.999997,
    ('Cautious', 'Wealthy', 'City') : 0.000001,
    ('Cautious', 'Wealthy', 'Suburb') : 0.000001,
    ('Cautious', 'Wealthy', 'Rural') : 0.000001,
})

net.P['AntiTheft'] = pd.Series({
    # RA, SE, AT
    ('Psychopath', 'Prole', 'True') : 0.000001,
    ('Psychopath', 'Prole', 'False') : 0.999999,
    ('Adventurous', 'Prole', 'True') : 0.000001,
    ('Adventurous', 'Prole', 'False') : 0.999999,
    ('Normal', 'Prole', 'True') : 0.1,
    ('Normal', 'Prole', 'False') : 0.9,
    ('Cautious', 'Prole', 'True') : 0.95,
    ('Cautious', 'Prole', 'False') : 0.05,

    ('Psychopath', 'Middle', 'True') : 0.000001,
    ('Psychopath', 'Middle', 'False') : 0.999999,
    ('Adventurous', 'Middle', 'True') : 0.000001,
    ('Adventurous', 'Middle', 'False') : 0.999999,
    ('Normal', 'Middle', 'True') : 0.3,
    ('Normal', 'Middle', 'False') : 0.7,
    ('Cautious', 'Middle', 'True') : 0.999999,
    ('Cautious', 'Middle', 'False') : 0.000001,

    ('Psychopath', 'UpperMiddle', 'True') : 0.05,
    ('Psychopath', 'UpperMiddle', 'False') : 0.95,
    ('Adventurous', 'UpperMiddle', 'True') : 0.2,
    ('Adventurous', 'UpperMiddle', 'False') : 0.8,
    ('Normal', 'UpperMiddle', 'True') : 0.9,
    ('Normal', 'UpperMiddle', 'False') : 0.1,
    ('Cautious', 'UpperMiddle', 'True') : 0.999999,
    ('Cautious', 'UpperMiddle', 'False') : 0.000001,

    ('Psychopath', 'Wealthy', 'True') : 0.5,
    ('Psychopath', 'Wealthy', 'False') : 0.5,
    ('Adventurous', 'Wealthy', 'True') : 0.5,
    ('Adventurous', 'Wealthy', 'False') : 0.5,
    ('Normal', 'Wealthy', 'True') : 0.8,
    ('Normal', 'Wealthy', 'False') : 0.2,
    ('Cautious', 'Wealthy', 'True') : 0.999999,
    ('Cautious', 'Wealthy', 'False') : 0.000001,
})

net.P['DrivingSkill'] = pd.Series({
    # Age, #ST, #DS
    ('Adolescent','True', 'Substandard'): 0.5,
    ('Adolescent','True', 'Normal'): 0.45,
    ('Adolescent','True', 'Expert'): 0.05,
    ('Adult','True', 'Substandard'): 0.3,
    ('Adult','True', 'Normal'): 0.6,
    ('Adult','True', 'Expert'): 0.1,
    ('Senior','True', 'Substandard'): 0.1,
    ('Senior','True', 'Normal'): 0.6,
    ('Senior','True', 'Expert'): 0.3,

    ('Adolescent','False', 'Substandard'): 0.5,
    ('Adolescent','False', 'Normal'): 0.45,
    ('Adolescent','False', 'Expert'): 0.05,
    ('Adult','False', 'Substandard'): 0.3,
    ('Adult','False', 'Normal'): 0.6,
    ('Adult','False', 'Expert'): 0.1,
    ('Senior','False', 'Substandard'): 0.4,
    ('Senior','False', 'Normal'): 0.5,
    ('Senior','False', 'Expert'): 0.1,
})


net.P['DrivQuality'] = pd.Series({
    # Skill, #RA, #DQ
    ('Substandard', 'Psychopath', 'Poor'): 1.0,
    ('Substandard', 'Psychopath', 'Normal'): 0.0,
    ('Substandard', 'Psychopath', 'Excellent'): 0.0,
    ('Normal', 'Psychopath', 'Poor'): 0.5,
    ('Normal', 'Psychopath', 'Normal'): 0.2,
    ('Normal', 'Psychopath', 'Excellent'): 0.3,
    ('Expert', 'Psychopath', 'Poor'): 0.3,
    ('Expert', 'Psychopath', 'Normal'): 0.2,
    ('Expert', 'Psychopath', 'Excellent'): 0.5,

    ('Substandard', 'Adventurous', 'Poor'): 1.0,
    ('Substandard', 'Adventurous', 'Normal'): 0.0,
    ('Substandard', 'Adventurous', 'Excellent'): 0.0,
    ('Normal', 'Adventurous', 'Poor'): 0.3,
    ('Normal', 'Adventurous', 'Normal'): 0.4,
    ('Normal', 'Adventurous', 'Excellent'): 0.3,
    ('Expert', 'Adventurous', 'Poor'): 0.01,
    ('Expert', 'Adventurous', 'Normal'): 0.98,
    ('Expert', 'Adventurous', 'Excellent'): 0.01,

    ('Substandard', 'Normal', 'Poor'): 1.0,
    ('Substandard', 'Normal', 'Normal'): 0.0,
    ('Substandard', 'Normal', 'Excellent'): 0.0,
    ('Normal', 'Normal', 'Poor'): 0.0,
    ('Normal', 'Normal', 'Normal'): 1.0,
    ('Normal', 'Normal', 'Excellent'): 0.0,
    ('Expert', 'Normal', 'Poor'): 0.0,
    ('Expert', 'Normal', 'Normal'): 0.0,
    ('Expert', 'Normal', 'Excellent'): 1.0,

    ('Substandard', 'Cautious', 'Poor'): 1.0,
    ('Substandard', 'Cautious', 'Normal'): 0.0,
    ('Substandard', 'Cautious', 'Excellent'): 0.0,
    ('Normal', 'Cautious', 'Poor'): 0.0,
    ('Normal', 'Cautious', 'Normal'): 0.8,
    ('Normal', 'Cautious', 'Excellent'): 0.2,
    ('Expert', 'Cautious', 'Poor'): 0.9,
    ('Expert', 'Cautious', 'Normal'): 0.0,
    ('Expert', 'Cautious', 'Excellent'): 1.0,
})

net.P['MakeModel'] = pd.Series({
    #SE, RA, MM
    ('Prole', 'Psychopath', 'SportsCar') : 0.1,
    ('Prole', 'Psychopath', 'Economy') : 0.7,
    ('Prole', 'Psychopath', 'FamilySedan') : 0.2,
    ('Prole', 'Psychopath', 'Luxury') : 0.0,
    ('Prole', 'Psychopath', 'SuperLuxury') : 0.0,

    ('Middle', 'Psychopath', 'SportsCar') : 0.15,
    ('Middle', 'Psychopath', 'Economy') : 0.20,
    ('Middle', 'Psychopath', 'FamilySedan') : 0.65,
    ('Middle', 'Psychopath', 'Luxury') : 0.0,
    ('Middle', 'Psychopath', 'SuperLuxury') : 0.0,

    ('UpperMiddle', 'Psychopath', 'SportsCar') : 0.20,
    ('UpperMiddle', 'Psychopath', 'Economy') : 0.05,
    ('UpperMiddle', 'Psychopath', 'FamilySedan') : 0.30,
    ('UpperMiddle', 'Psychopath', 'Luxury') : 0.45,
    ('UpperMiddle', 'Psychopath', 'SuperLuxury') : 0.0,

    ('Wealthy', 'Psychopath', 'SportsCar') : 0.30,
    ('Wealthy', 'Psychopath', 'Economy') : 0.01,
    ('Wealthy', 'Psychopath', 'FamilySedan') : 0.09,
    ('Wealthy', 'Psychopath', 'Luxury') : 0.40,
    ('Wealthy', 'Psychopath', 'SuperLuxury') : 0.20,


    ('Prole', 'Adventurous', 'SportsCar') : 0.1,
    ('Prole', 'Adventurous', 'Economy') : 0.7,
    ('Prole', 'Adventurous', 'FamilySedan') : 0.2,
    ('Prole', 'Adventurous', 'Luxury') : 0.0,
    ('Prole', 'Adventurous', 'SuperLuxury') : 0.0,

    ('Middle', 'Adventurous', 'SportsCar') : 0.15,
    ('Middle', 'Adventurous', 'Economy') : 0.20,
    ('Middle', 'Adventurous', 'FamilySedan') : 0.65,
    ('Middle', 'Adventurous', 'Luxury') : 0.0,
    ('Middle', 'Adventurous', 'SuperLuxury') : 0.0,

    ('UpperMiddle', 'Adventurous', 'SportsCar') : 0.20,
    ('UpperMiddle', 'Adventurous', 'Economy') : 0.05,
    ('UpperMiddle', 'Adventurous', 'FamilySedan') : 0.30,
    ('UpperMiddle', 'Adventurous', 'Luxury') : 0.45,
    ('UpperMiddle', 'Adventurous', 'SuperLuxury') : 0.0,

    ('Wealthy', 'Adventurous', 'SportsCar') : 0.30,
    ('Wealthy', 'Adventurous', 'Economy') : 0.01,
    ('Wealthy', 'Adventurous', 'FamilySedan') : 0.09,
    ('Wealthy', 'Adventurous', 'Luxury') : 0.40,
    ('Wealthy', 'Adventurous', 'SuperLuxury') : 0.20,

    ('Prole', 'Normal', 'SportsCar') : 0.1,
    ('Prole', 'Normal', 'Economy') : 0.7,
    ('Prole', 'Normal', 'FamilySedan') : 0.2,
    ('Prole', 'Normal', 'Luxury') : 0.0,
    ('Prole', 'Normal', 'SuperLuxury') : 0.0,

    ('Middle', 'Normal', 'SportsCar') : 0.15,
    ('Middle', 'Normal', 'Economy') : 0.20,
    ('Middle', 'Normal', 'FamilySedan') : 0.65,
    ('Middle', 'Normal', 'Luxury') : 0.0,
    ('Middle', 'Normal', 'SuperLuxury') : 0.0,

    ('UpperMiddle', 'Normal', 'SportsCar') : 0.20,
    ('UpperMiddle', 'Normal', 'Economy') : 0.05,
    ('UpperMiddle', 'Normal', 'FamilySedan') : 0.30,
    ('UpperMiddle', 'Normal', 'Luxury') : 0.45,
    ('UpperMiddle', 'Normal', 'SuperLuxury') : 0.0,

    ('Wealthy', 'Normal', 'SportsCar') : 0.30,
    ('Wealthy', 'Normal', 'Economy') : 0.01,
    ('Wealthy', 'Normal', 'FamilySedan') : 0.09,
    ('Wealthy', 'Normal', 'Luxury') : 0.40,
    ('Wealthy', 'Normal', 'SuperLuxury') : 0.20,
    
    ('Prole', 'Cautious', 'SportsCar') : 0.1,
    ('Prole', 'Cautious', 'Economy') : 0.7,
    ('Prole', 'Cautious', 'FamilySedan') : 0.2,
    ('Prole', 'Cautious', 'Luxury') : 0.0,
    ('Prole', 'Cautious', 'SuperLuxury') : 0.0,

    ('Middle', 'Cautious', 'SportsCar') : 0.15,
    ('Middle', 'Cautious', 'Economy') : 0.20,
    ('Middle', 'Cautious', 'FamilySedan') : 0.65,
    ('Middle', 'Cautious', 'Luxury') : 0.0,
    ('Middle', 'Cautious', 'SuperLuxury') : 0.0,

    ('UpperMiddle', 'Cautious', 'SportsCar') : 0.20,
    ('UpperMiddle', 'Cautious', 'Economy') : 0.05,
    ('UpperMiddle', 'Cautious', 'FamilySedan') : 0.30,
    ('UpperMiddle', 'Cautious', 'Luxury') : 0.45,
    ('UpperMiddle', 'Cautious', 'SuperLuxury') : 0.0,

    ('Wealthy', 'Cautious', 'SportsCar') : 0.30,
    ('Wealthy', 'Cautious', 'Economy') : 0.01,
    ('Wealthy', 'Cautious', 'FamilySedan') : 0.09,
    ('Wealthy', 'Cautious', 'Luxury') : 0.40,
    ('Wealthy', 'Cautious', 'SuperLuxury') : 0.20,
})

net.P['VehicleYear'] = pd.Series({
    #SE, RA, VY
    ('Prole', 'Psychopath', 'Current') : 0.15,
    ('Prole', 'Psychopath', 'Older') : 0.85,
    ('Middle', 'Psychopath', 'Current') : 0.3,
    ('Middle', 'Psychopath', 'Older') : 0.7,
    ('UpperMiddle', 'Psychopath', 'Current') : 0.8,
    ('UpperMiddle', 'Psychopath', 'Older') : 0.2,
    ('Wealthy', 'Psychopath', 'Current') : 0.9,
    ('Wealthy', 'Psychopath', 'Older') : 0.1,

    ('Prole', 'Adventurous', 'Current') : 0.15,
    ('Prole', 'Adventurous', 'Older') : 0.85,
    ('Middle', 'Adventurous', 'Current') : 0.3,
    ('Middle', 'Adventurous', 'Older') : 0.7,
    ('UpperMiddle', 'Adventurous', 'Current') : 0.8,
    ('UpperMiddle', 'Adventurous', 'Older') : 0.2,
    ('Wealthy', 'Adventurous', 'Current') : 0.9,
    ('Wealthy', 'Adventurous', 'Older') : 0.1,

    ('Prole', 'Normal', 'Current') : 0.15,
    ('Prole', 'Normal', 'Older') : 0.85,
    ('Middle', 'Normal', 'Current') : 0.3,
    ('Middle', 'Normal', 'Older') : 0.7,
    ('UpperMiddle', 'Normal', 'Current') : 0.8,
    ('UpperMiddle', 'Normal', 'Older') : 0.2,
    ('Wealthy', 'Normal', 'Current') : 0.9,
    ('Wealthy', 'Normal', 'Older') : 0.1,

    ('Prole', 'Cautious', 'Current') : 0.15,
    ('Prole', 'Cautious', 'Older') : 0.85,
    ('Middle', 'Cautious', 'Current') : 0.3,
    ('Middle', 'Cautious', 'Older') : 0.7,
    ('UpperMiddle', 'Cautious', 'Current') : 0.8,
    ('UpperMiddle', 'Cautious', 'Older') : 0.2,
    ('Wealthy', 'Cautious', 'Current') : 0.9,
    ('Wealthy', 'Cautious', 'Older') : 0.1,
})

net.P['Mileage'] = pd.Series({'FiveThou': 0.1, 'TwentyThou': 0.4, 'FiftyThou': 0.4, 'Domino': 0.1})

net.P['Airbag'] = pd.Series({
    #MM, VY, AB
    ('SportsCar', 'Current', 'True') : 1.0,
    ('SportsCar', 'Current', 'False') : 0.0,
    ('Economy', 'Current', 'True') : 1.0,
    ('Economy', 'Current', 'False') : 0.0,
    ('FamilySedan', 'Current', 'True') : 1.0,
    ('FamilySedan', 'Current', 'False') : 0.0,
    ('Luxury', 'Current', 'True') : 1.0,
    ('Luxury', 'Current', 'False') : 0.0,
    ('SuperLuxury', 'Current','True') : 1.0,
    ('SuperLuxury', 'Current', 'False') : 0.0,

    ('SportsCar', 'Older', 'True') : 0.1,
    ('SportsCar', 'Older', 'False') : 0.9,
    ('Economy', 'Older', 'True') : 0.05,
    ('Economy', 'Older', 'False') : 0.95,
    ('FamilySedan', 'Older', 'True') : 0.2,
    ('FamilySedan', 'Older', 'False') : 0.8,
    ('Luxury', 'Older', 'True') : 0.6,
    ('Luxury', 'Older', 'False') : 0.4,
    ('SuperLuxury', 'Older','True') : 0.1,
    ('SuperLuxury', 'Older', 'False') : 0.9,

})


net.P['Antilock'] = pd.Series({
    #MM, VY, Al
    ('SportsCar', 'Current', 'True') : 0.9,
    ('SportsCar', 'Current', 'False') : 0.1,
    ('Economy', 'Current', 'True') : 0.001,
    ('Economy', 'Current', 'False') : 0.999,
    ('FamilySedan', 'Current', 'True') : 0.4,
    ('FamilySedan', 'Current', 'False') : 0.6,
    ('Luxury', 'Current', 'True') : 0.99,
    ('Luxury', 'Current', 'False') : 0.01,
    ('SuperLuxury', 'Current','True') : 0.99,
    ('SuperLuxury', 'Current', 'False') : 0.01,

    ('SportsCar', 'Older', 'True') : 0.1,
    ('SportsCar', 'Older', 'False') : 0.9,
    ('Economy', 'Older', 'True') : 0.0,
    ('Economy', 'Older', 'False') : 1.0,
    ('FamilySedan', 'Older', 'True') : 0.0,
    ('FamilySedan', 'Older', 'False') : 1.0,
    ('Luxury', 'Older', 'True') : 0.3,
    ('Luxury', 'Older', 'False') : 0.7,
    ('SuperLuxury', 'Older','True') : 0.15,
    ('SuperLuxury', 'Older', 'False') : 0.85,

})


net.P['RuggedAuto'] = pd.Series({
    #MM, VY, RGA
    ('SportsCar', 'Current', 'EggShell') : 0.95,
    ('SportsCar', 'Current', 'Football') : 0.04,
    ('SportsCar', 'Current', 'Tank') : 0.01,
    ('Economy', 'Current', 'EggShell') : 0.5,
    ('Economy', 'Current', 'Football') : 0.5,
    ('Economy', 'Current', 'Tank') : 0.0,
    ('FamilySedan', 'Current', 'EggShell') : 0.2,
    ('FamilySedan', 'Current', 'Football') : 0.6,
    ('FamilySedan', 'Current', 'Tank') : 0.2,
    ('Luxury', 'Current', 'EggShell') : 0.1,
    ('Luxury', 'Current', 'Football') : 0.6,
    ('Luxury', 'Current', 'Tank') : 0.3,
    ('SuperLuxury', 'Current','EggShell') : 0.05,
    ('SuperLuxury', 'Current', 'Football') : 0.55,
    ('SuperLuxury', 'Current', 'Tank') : 0.4,

    ('SportsCar', 'Older', 'EggShell') : 0.95,
    ('SportsCar', 'Older', 'Football') : 0.04,
    ('SportsCar', 'Older', 'Tank') : 0.01,
    ('Economy', 'Older', 'EggShell') : 0.9,
    ('Economy', 'Older', 'Football') : 0.1,
    ('Economy', 'Older', 'Tank') : 0.0,
    ('FamilySedan', 'Older', 'EggShell') : 0.05,
    ('FamilySedan', 'Older', 'Football') : 0.55,
    ('FamilySedan', 'Older', 'Tank') : 0.4,
    ('Luxury', 'Older', 'EggShell') : 0.1,
    ('Luxury', 'Older', 'Football') : 0.6,
    ('Luxury', 'Older', 'Tank') : 0.3,
    ('SuperLuxury', 'Older','EggShell') : 0.05,
    ('SuperLuxury', 'Older', 'Football') : 0.55,
    ('SuperLuxury', 'Older', 'Tank') : 0.4,

})

net.P['CarValue'] = pd.Series({
    # MM, #VY, #M ('FiveThou': 0.1, 'TwentyThou': 0.4, 'FiftyThou': 0.4, 'Domino': 0.1}))
    ('SportsCar', 'Current', 'FiveThou', 'FiveThou') : 0.0,
    ('SportsCar', 'Current', 'FiveThou', 'TenThou') : 0.1,
    ('SportsCar', 'Current', 'FiveThou', 'TwentyThou') : 0.8,
    ('SportsCar', 'Current', 'FiveThou', 'FiftyThou') : 0.09,
    ('SportsCar', 'Current', 'FiveThou', 'Million') : 0.01,

    ('Economy', 'Current', 'FiveThou', 'FiveThou') : 0.1,
    ('Economy', 'Current', 'FiveThou', 'TenThou') : 0.8,
    ('Economy', 'Current', 'FiveThou', 'TwentyThou') : 0.1,
    ('Economy', 'Current', 'FiveThou', 'FiftyThou') : 0.0,
    ('Economy', 'Current', 'FiveThou', 'Million') : 0.0,

    ('FamilySedan', 'Current', 'FiveThou', 'FiveThou') : 0.0,
    ('FamilySedan', 'Current', 'FiveThou', 'TenThou') : 0.1,
    ('FamilySedan', 'Current', 'FiveThou', 'TwentyThou') : 0.9,
    ('FamilySedan', 'Current', 'FiveThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Current', 'FiveThou', 'Million') : 0.0,

    ('Luxury', 'Current', 'FiveThou', 'FiveThou') : 0.0,
    ('Luxury', 'Current', 'FiveThou', 'TenThou') : 0.0,
    ('Luxury', 'Current', 'FiveThou', 'TwentyThou') : 0.0,
    ('Luxury', 'Current', 'FiveThou', 'FiftyThou') : 1.0,
    ('Luxury', 'Current', 'FiveThou', 'Million') : 0.0,

    ('SuperLuxury', 'Current', 'FiveThou', 'FiveThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiveThou', 'TenThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiveThou', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiveThou', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiveThou', 'Million') : 1.0,


    ('SportsCar', 'Older', 'FiveThou', 'FiveThou') : 0.03,
    ('SportsCar', 'Older', 'FiveThou', 'TenThou') : 0.3,
    ('SportsCar', 'Older', 'FiveThou', 'TwentyThou') : 0.6,
    ('SportsCar', 'Older', 'FiveThou', 'FiftyThou') : 0.06,
    ('SportsCar', 'Older', 'FiveThou', 'Million') : 0.01,

    ('Economy', 'Older', 'FiveThou', 'FiveThou') : 0.25,
    ('Economy', 'Older', 'FiveThou', 'TenThou') : 0.7,
    ('Economy', 'Older', 'FiveThou', 'TwentyThou') : 0.05,
    ('Economy', 'Older', 'FiveThou', 'FiftyThou') : 0.0,
    ('Economy', 'Older', 'FiveThou', 'Million') : 0.0,

    ('FamilySedan', 'Older', 'FiveThou', 'FiveThou') : 0.2,
    ('FamilySedan', 'Older', 'FiveThou', 'TenThou') : 0.3,
    ('FamilySedan', 'Older', 'FiveThou', 'TwentyThou') : 0.5,
    ('FamilySedan', 'Older', 'FiveThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Older', 'FiveThou', 'Million') : 0.0,

    ('Luxury', 'Older', 'FiveThou', 'FiveThou') : 0.01,
    ('Luxury', 'Older', 'FiveThou', 'TenThou') : 0.09,
    ('Luxury', 'Older', 'FiveThou', 'TwentyThou') : 0.20,
    ('Luxury', 'Older', 'FiveThou', 'FiftyThou') : 0.70,
    ('Luxury', 'Older', 'FiveThou', 'Million') : 0.0,

    ('SuperLuxury', 'Older', 'FiveThou', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiveThou', 'TenThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiveThou', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiveThou', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiveThou', 'Million') : 0.999996,


    ('SportsCar', 'Current', 'TwentyThou', 'FiveThou') : 0.0,
    ('SportsCar', 'Current', 'TwentyThou', 'TenThou') : 0.1,
    ('SportsCar', 'Current', 'TwentyThou', 'TwentyThou') : 0.8,
    ('SportsCar', 'Current', 'TwentyThou', 'FiftyThou') : 0.09,
    ('SportsCar', 'Current', 'TwentyThou', 'Million') : 0.01,

    ('Economy', 'Current', 'TwentyThou', 'FiveThou') : 0.1,
    ('Economy', 'Current', 'TwentyThou', 'TenThou') : 0.8,
    ('Economy', 'Current', 'TwentyThou', 'TwentyThou') : 0.1,
    ('Economy', 'Current', 'TwentyThou', 'FiftyThou') : 0.0,
    ('Economy', 'Current', 'TwentyThou', 'Million') : 0.0,

    ('FamilySedan', 'Current', 'TwentyThou', 'FiveThou') : 0.0,
    ('FamilySedan', 'Current', 'TwentyThou', 'TenThou') : 0.1,
    ('FamilySedan', 'Current', 'TwentyThou', 'TwentyThou') : 0.9,
    ('FamilySedan', 'Current', 'TwentyThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Current', 'TwentyThou', 'Million') : 0.0,

    ('Luxury', 'Current', 'TwentyThou', 'FiveThou') : 0.0,
    ('Luxury', 'Current', 'TwentyThou', 'TenThou') : 0.0,
    ('Luxury', 'Current', 'TwentyThou', 'TwentyThou') : 0.0,
    ('Luxury', 'Current', 'TwentyThou', 'FiftyThou') : 1.0,
    ('Luxury', 'Current', 'TwentyThou', 'Million') : 0.0,

    ('SuperLuxury', 'Current', 'TwentyThou', 'FiveThou') : 0.0,
    ('SuperLuxury', 'Current', 'TwentyThou', 'TenThou') : 0.0,
    ('SuperLuxury', 'Current', 'TwentyThou', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'Current', 'TwentyThou', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'Current', 'TwentyThou', 'Million') : 1.0,


    ('SportsCar', 'Older', 'TwentyThou', 'FiveThou') : 0.16,
    ('SportsCar', 'Older', 'TwentyThou', 'TenThou') : 0.5,
    ('SportsCar', 'Older', 'TwentyThou', 'TwentyThou') : 0.3,
    ('SportsCar', 'Older', 'TwentyThou', 'FiftyThou') : 0.03,
    ('SportsCar', 'Older', 'TwentyThou', 'Million') : 0.01,

    ('Economy', 'Older', 'TwentyThou', 'FiveThou') : 0.7,
    ('Economy', 'Older', 'TwentyThou', 'TenThou') : 0.2999,
    ('Economy', 'Older', 'TwentyThou', 'TwentyThou') : 0.0001,
    ('Economy', 'Older', 'TwentyThou', 'FiftyThou') : 0.0,
    ('Economy', 'Older', 'TwentyThou', 'Million') : 0.0,

    ('FamilySedan', 'Older', 'TwentyThou', 'FiveThou') : 0.5,
    ('FamilySedan', 'Older', 'TwentyThou', 'TenThou') : 0.3,
    ('FamilySedan', 'Older', 'TwentyThou', 'TwentyThou') : 0.2,
    ('FamilySedan', 'Older', 'TwentyThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Older', 'TwentyThou', 'Million') : 0.0,

    ('Luxury', 'Older', 'TwentyThou', 'FiveThou') : 0.05,
    ('Luxury', 'Older', 'TwentyThou', 'TenThou') : 0.15,
    ('Luxury', 'Older', 'TwentyThou', 'TwentyThou') : 0.30,
    ('Luxury', 'Older', 'TwentyThou', 'FiftyThou') : 0.50,
    ('Luxury', 'Older', 'TwentyThou', 'Million') : 0.0,

    ('SuperLuxury', 'Older', 'TwentyThou', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'Older', 'TwentyThou', 'TenThou') : 0.000001,
    ('SuperLuxury', 'Older', 'TwentyThou', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'TwentyThou', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'TwentyThou', 'Million') : 0.999996,

    ('SportsCar', 'Current', 'FiftyThou', 'FiveThou') : 0.0,
    ('SportsCar', 'Current', 'FiftyThou', 'TenThou') : 0.1,
    ('SportsCar', 'Current', 'FiftyThou', 'TwentyThou') : 0.8,
    ('SportsCar', 'Current', 'FiftyThou', 'FiftyThou') : 0.09,
    ('SportsCar', 'Current', 'FiftyThou', 'Million') : 0.01,

    ('Economy', 'Current', 'FiftyThou', 'FiveThou') : 0.1,
    ('Economy', 'Current', 'FiftyThou', 'TenThou') : 0.8,
    ('Economy', 'Current', 'FiftyThou', 'TwentyThou') : 0.1,
    ('Economy', 'Current', 'FiftyThou', 'FiftyThou') : 0.0,
    ('Economy', 'Current', 'FiftyThou', 'Million') : 0.0,

    ('FamilySedan', 'Current', 'FiftyThou', 'FiveThou') : 0.0,
    ('FamilySedan', 'Current', 'FiftyThou', 'TenThou') : 0.1,
    ('FamilySedan', 'Current', 'FiftyThou', 'TwentyThou') : 0.9,
    ('FamilySedan', 'Current', 'FiftyThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Current', 'FiftyThou', 'Million') : 0.0,

    ('Luxury', 'Current', 'FiftyThou', 'FiveThou') : 0.0,
    ('Luxury', 'Current', 'FiftyThou', 'TenThou') : 0.0,
    ('Luxury', 'Current', 'FiftyThou', 'TwentyThou') : 0.0,
    ('Luxury', 'Current', 'FiftyThou', 'FiftyThou') : 1.0,
    ('Luxury', 'Current', 'FiftyThou', 'Million') : 0.0,

    ('SuperLuxury', 'Current', 'FiftyThou', 'FiveThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiftyThou', 'TenThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiftyThou', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiftyThou', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'Current', 'FiftyThou', 'Million') : 1.0,


    ('SportsCar', 'Older', 'FiftyThou', 'FiveThou') : 0.4,
    ('SportsCar', 'Older', 'FiftyThou', 'TenThou') : 0.47,
    ('SportsCar', 'Older', 'FiftyThou', 'TwentyThou') : 0.10,
    ('SportsCar', 'Older', 'FiftyThou', 'FiftyThou') : 0.02,
    ('SportsCar', 'Older', 'FiftyThou', 'Million') : 0.01,

    ('Economy', 'Older', 'FiftyThou', 'FiveThou') : 0.990000,
    ('Economy', 'Older', 'FiftyThou', 'TenThou') : 0.009999,
    ('Economy', 'Older', 'FiftyThou', 'TwentyThou') : 0.000001,
    ('Economy', 'Older', 'FiftyThou', 'FiftyThou') : 0.0,
    ('Economy', 'Older', 'FiftyThou', 'Million') : 0.0,

    ('FamilySedan', 'Older', 'FiftyThou', 'FiveThou') : 0.7,
    ('FamilySedan', 'Older', 'FiftyThou', 'TenThou') : 0.2,
    ('FamilySedan', 'Older', 'FiftyThou', 'TwentyThou') : 0.1,
    ('FamilySedan', 'Older', 'FiftyThou', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Older', 'FiftyThou', 'Million') : 0.0,

    ('Luxury', 'Older', 'FiftyThou', 'FiveThou') : 0.1,
    ('Luxury', 'Older', 'FiftyThou', 'TenThou') : 0.3,
    ('Luxury', 'Older', 'FiftyThou', 'TwentyThou') : 0.3,
    ('Luxury', 'Older', 'FiftyThou', 'FiftyThou') : 0.3,
    ('Luxury', 'Older', 'FiftyThou', 'Million') : 0.0,

    ('SuperLuxury', 'Older', 'FiftyThou', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiftyThou', 'TenThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiftyThou', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiftyThou', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'FiftyThou', 'Million') : 0.999996,


    ('SportsCar', 'Current', 'Domino', 'FiveThou') : 0.0,
    ('SportsCar', 'Current', 'Domino', 'TenThou') : 0.1,
    ('SportsCar', 'Current', 'Domino', 'TwentyThou') : 0.8,
    ('SportsCar', 'Current', 'Domino', 'FiftyThou') : 0.09,
    ('SportsCar', 'Current', 'Domino', 'Million') : 0.01,

    ('Economy', 'Current', 'Domino', 'FiveThou') : 0.1,
    ('Economy', 'Current', 'Domino', 'TenThou') : 0.8,
    ('Economy', 'Current', 'Domino', 'TwentyThou') : 0.1,
    ('Economy', 'Current', 'Domino', 'FiftyThou') : 0.0,
    ('Economy', 'Current', 'Domino', 'Million') : 0.0,

    ('FamilySedan', 'Current', 'Domino', 'FiveThou') : 0.0,
    ('FamilySedan', 'Current', 'Domino', 'TenThou') : 0.1,
    ('FamilySedan', 'Current', 'Domino', 'TwentyThou') : 0.9,
    ('FamilySedan', 'Current', 'Domino', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Current', 'Domino', 'Million') : 0.0,

    ('Luxury', 'Current', 'Domino', 'FiveThou') : 0.0,
    ('Luxury', 'Current', 'Domino', 'TenThou') : 0.0,
    ('Luxury', 'Current', 'Domino', 'TwentyThou') : 0.0,
    ('Luxury', 'Current', 'Domino', 'FiftyThou') : 1.0,
    ('Luxury', 'Current', 'Domino', 'Million') : 0.0,

    ('SuperLuxury', 'Current', 'Domino', 'FiveThou') : 0.0,
    ('SuperLuxury', 'Current', 'Domino', 'TenThou') : 0.0,
    ('SuperLuxury', 'Current', 'Domino', 'TwentyThou') : 0.0,
    ('SuperLuxury', 'Current', 'Domino', 'FiftyThou') : 0.0,
    ('SuperLuxury', 'Current', 'Domino', 'Million') : 1.0,

    ('SportsCar', 'Older', 'Domino', 'FiveThou') : 0.9,
    ('SportsCar', 'Older', 'Domino', 'TenThou') : 0.06,
    ('SportsCar', 'Older', 'Domino', 'TwentyThou') : 0.02,
    ('SportsCar', 'Older', 'Domino', 'FiftyThou') : 0.01,
    ('SportsCar', 'Older', 'Domino', 'Million') : 0.01,

    ('Economy', 'Older', 'Domino', 'FiveThou') : 0.999998,
    ('Economy', 'Older', 'Domino', 'TenThou') : 0.000001,
    ('Economy', 'Older', 'Domino', 'TwentyThou') : 0.000001,
    ('Economy', 'Older', 'Domino', 'FiftyThou') : 0.0,
    ('Economy', 'Older', 'Domino', 'Million') : 0.0,

    ('FamilySedan', 'Older', 'Domino', 'FiveThou') : 0.990000,
    ('FamilySedan', 'Older', 'Domino', 'TenThou') : 0.009999,
    ('FamilySedan', 'Older', 'Domino', 'TwentyThou') : 0.000001,
    ('FamilySedan', 'Older', 'Domino', 'FiftyThou') : 0.0,
    ('FamilySedan', 'Older', 'Domino', 'Million') : 0.0,

    ('Luxury', 'Older', 'Domino', 'FiveThou') : 0.2,
    ('Luxury', 'Older', 'Domino', 'TenThou') : 0.2,
    ('Luxury', 'Older', 'Domino', 'TwentyThou') : 0.3,
    ('Luxury', 'Older', 'Domino', 'FiftyThou') : 0.3,
    ('Luxury', 'Older', 'Domino', 'Million') : 0.0,

    ('SuperLuxury', 'Older', 'Domino', 'FiveThou') : 0.000001,
    ('SuperLuxury', 'Older', 'Domino', 'TenThou') : 0.000001,
    ('SuperLuxury', 'Older', 'Domino', 'TwentyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'Domino', 'FiftyThou') : 0.000001,
    ('SuperLuxury', 'Older', 'Domino', 'Million') : 0.999996,
})

net.P['Cushioning'] = pd.Series({
    #RA, AB, C
    ('Eggshell', 'True', 'Poor') : 0.5,
    ('Eggshell', 'True', 'Fair') : 0.3,
    ('Eggshell', 'True', 'Good') : 0.2,
    ('Eggshell', 'True', 'Excellent') : 0.0,
    ('Football', 'True', 'Poor') : 0.0,
    ('Football', 'True', 'Fair') : 0.1,
    ('Football', 'True', 'Good') : 0.6,
    ('Football', 'True', 'Excellent') : 0.3,
    ('Tank', 'True', 'Poor') : 0.0,
    ('Tank', 'True', 'Fair') : 0.0,
    ('Tank', 'True', 'Good') : 0.0,
    ('Tank', 'True', 'Excellent') : 1.0,

    ('Eggshell', 'False', 'Poor') : 0.7,
    ('Eggshell', 'False', 'Fair') : 0.3,
    ('Eggshell', 'False', 'Good') : 0.0,
    ('Eggshell', 'False', 'Excellent') : 0.0,
    ('Football', 'False', 'Poor') : 0.1,
    ('Football', 'False', 'Fair') : 0.6,
    ('Football', 'False', 'Good') : 0.3,
    ('Football', 'False', 'Excellent') : 0.0,
    ('Tank', 'False', 'Poor') : 0.0,
    ('Tank', 'False', 'Fair') : 0.0,
    ('Tank', 'False', 'Good') : 0.7,
    ('Tank', 'False', 'Excellent') : 0.3,

})

net.P['Accident'] = pd.Series({
    #Antilock, Mileage, DQ, Acc 520 50 dom poor norm exce  none mild mod sev
    ('True','FiveThou', 'Poor', 'None') : 0.7,
    ('True','FiveThou', 'Poor', 'Mild') : 0.2,
    ('True','FiveThou', 'Poor', 'Moderate') : 0.07,
    ('True','FiveThou', 'Poor', 'Severe') : 0.03,
    ('False','FiveThou', 'Poor', 'None') : 0.6,
    ('False','FiveThou', 'Poor', 'Mild') : 0.2,
    ('False','FiveThou', 'Poor', 'Moderate') : 0.1,
    ('False','FiveThou', 'Poor', 'Severe') : 0.1,
    ('True','TwentyThou', 'Poor', 'None') : 0.4,
    ('True','TwentyThou', 'Poor', 'Mild') : 0.3,
    ('True','TwentyThou', 'Poor', 'Moderate') : 0.2,
    ('True','TwentyThou', 'Poor', 'Severe') : 0.1,
    ('False','TwentyThou', 'Poor', 'None') : 0.3,
    ('False','TwentyThou', 'Poor', 'Mild') : 0.2,
    ('False','TwentyThou', 'Poor', 'Moderate') : 0.2,
    ('False','TwentyThou', 'Poor', 'Severe') : 0.3,
    ('True','FiftyThou', 'Poor', 'None') : 0.3,
    ('True','FiftyThou', 'Poor', 'Mild') : 0.3,
    ('True','FiftyThou', 'Poor', 'Moderate') : 0.2,
    ('True','FiftyThou', 'Poor', 'Severe') : 0.2,
    ('False','FiftyThou', 'Poor', 'None') : 0.2,
    ('False','FiftyThou', 'Poor', 'Mild') : 0.2,
    ('False','FiftyThou', 'Poor', 'Moderate') : 0.2,
    ('False','FiftyThou', 'Poor', 'Severe') : 0.4,
    ('True','Domino', 'Poor', 'None') : 0.2,
    ('True','Domino', 'Poor', 'Mild') : 0.2,
    ('True','Domino', 'Poor', 'Moderate') : 0.3,
    ('True','Domino', 'Poor', 'Severe') : 0.3,
    ('False','Domino', 'Poor', 'None') : 0.1,
    ('False','Domino', 'Poor', 'Mild') : 0.1,
    ('False','Domino', 'Poor', 'Moderate') : 0.3,
    ('False','Domino', 'Poor', 'Severe') : 0.5,


    ('True','FiveThou', 'Normal', 'None') : 0.990,
    ('True','FiveThou', 'Normal', 'Mild') : 0.007,
    ('True','FiveThou', 'Normal', 'Moderate') : 0.002,
    ('True','FiveThou', 'Normal', 'Severe') : 0.001,
    ('False','FiveThou', 'Normal', 'None') : 0.980,
    ('False','FiveThou', 'Normal', 'Mild') : 0.01,
    ('False','FiveThou', 'Normal', 'Moderate') : 0.005,
    ('False','FiveThou', 'Normal', 'Severe') : 0.005,
    ('True','TwentyThou', 'Normal', 'None') : 0.980,
    ('True','TwentyThou', 'Normal', 'Mild') : 0.01,
    ('True','TwentyThou', 'Normal', 'Moderate') : 0.05,
    ('True','TwentyThou', 'Normal', 'Severe') : 0.05,
    ('False','TwentyThou', 'Normal', 'None') : 0.960,
    ('False','TwentyThou', 'Normal', 'Mild') : 0.020,
    ('False','TwentyThou', 'Normal', 'Moderate') : 0.015,
    ('False','TwentyThou', 'Normal', 'Severe') : 0.005,
    ('True','FiftyThou', 'Normal', 'None') : 0.970,
    ('True','FiftyThou', 'Normal', 'Mild') : 0.020,
    ('True','FiftyThou', 'Normal', 'Moderate') : 0.007,
    ('True','FiftyThou', 'Normal', 'Severe') : 0.003,
    ('False','FiftyThou', 'Normal', 'None') : 0.950,
    ('False','FiftyThou', 'Normal', 'Mild') : 0.030,
    ('False','FiftyThou', 'Normal', 'Moderate') : 0.015,
    ('False','FiftyThou', 'Normal', 'Severe') : 0.005,
    ('True','Domino', 'Normal', 'None') : 0.95,
    ('True','Domino', 'Normal', 'Mild') : 0.03,
    ('True','Domino', 'Normal', 'Moderate') : 0.01,
    ('True','Domino', 'Normal', 'Severe') : 0.01,
    ('False','Domino', 'Normal', 'None') : 0.94,
    ('False','Domino', 'Normal', 'Mild') : 0.03,
    ('False','Domino', 'Normal', 'Moderate') : 0.02,
    ('False','Domino', 'Normal', 'Severe') : 0.01,


    ('True','FiveThou', 'Excellent', 'None') : 0.999,
    ('True','FiveThou', 'Excellent', 'Mild') : 0.0007,
    ('True','FiveThou', 'Excellent', 'Moderate') : 0.0002,
    ('True','FiveThou', 'Excellent', 'Severe') : 0.0001,
    ('False','FiveThou', 'Excellent', 'None') : 0.995,
    ('False','FiveThou', 'Excellent', 'Mild') : 0.003,
    ('False','FiveThou', 'Excellent', 'Moderate') : 0.001,
    ('False','FiveThou', 'Excellent', 'Severe') : 0.001,
    ('True','TwentyThou', 'Excellent', 'None') : 0.995,
    ('True','TwentyThou', 'Excellent', 'Mild') : 0.003,
    ('True','TwentyThou', 'Excellent', 'Moderate') : 0.001,
    ('True','TwentyThou', 'Excellent', 'Severe') : 0.001,
    ('False','TwentyThou', 'Excellent', 'None') : 0.990,
    ('False','TwentyThou', 'Excellent', 'Mild') : 0.007,
    ('False','TwentyThou', 'Excellent', 'Moderate') : 0.002,
    ('False','TwentyThou', 'Excellent', 'Severe') : 0.001,
    ('True','FiftyThou', 'Excellent', 'None') : 0.990,
    ('True','FiftyThou', 'Excellent', 'Mild') : 0.007,
    ('True','FiftyThou', 'Excellent', 'Moderate') : 0.002,
    ('True','FiftyThou', 'Excellent', 'Severe') : 0.001,
    ('False','FiftyThou', 'Excellent', 'None') : 0.980,
    ('False','FiftyThou', 'Excellent', 'Mild') : 0.010,
    ('False','FiftyThou', 'Excellent', 'Moderate') : 0.005,
    ('False','FiftyThou', 'Excellent', 'Severe') : 0.005,
    ('True','Domino', 'Excellent', 'None') : 0.985,
    ('True','Domino', 'Excellent', 'Mild') : 0.010,
    ('True','Domino', 'Excellent', 'Moderate') : 0.003,
    ('True','Domino', 'Excellent', 'Severe') : 0.002,
    ('False','Domino', 'Excellent', 'None') : 0.980,
    ('False','Domino', 'Excellent', 'Mild') : 0.010,
    ('False','Domino', 'Excellent', 'Moderate') : 0.007,
    ('False','Domino', 'Excellent', 'Severe') : 0.003,
})

net.P['Theft'] = pd.Series({
    #AntiTheft, HB, CV,  #secure, city, suburb, rural 5 10 20 50 mil
    ('True', 'Secure', 'FiveThou', 'True') : 0.000001,
    ('True', 'Secure', 'FiveThou', 'False') : 0.999999,
    ('False', 'Secure', 'FiveThou', 'True') : 0.000001,
    ('False', 'Secure', 'FiveThou', 'False') : 0.999999,
    ('True', 'City', 'FiveThou', 'True') : 0.0005,
    ('True', 'City', 'FiveThou', 'False') : 0.9995,
    ('False', 'City', 'FiveThou', 'True') : 0.001,
    ('False', 'City', 'FiveThou', 'False') : 0.999,
    ('True', 'Suburb', 'FiveThou', 'True') : 0.00001,
    ('True', 'Suburb', 'FiveThou', 'False') : 0.99999,
    ('False', 'Suburb', 'FiveThou', 'True') : 0.00001,
    ('False', 'Suburb', 'FiveThou', 'False') : 0.99999,
    ('True', 'Rural', 'FiveThou', 'True') : 0.00001,
    ('True', 'Rural', 'FiveThou', 'False') : 0.99999,
    ('False', 'Rural', 'FiveThou', 'True') : 0.00001,
    ('False', 'Rural', 'FiveThou', 'False') : 0.99999,

    ('True', 'Secure', 'TenThou', 'True') : 0.000002,
    ('True', 'Secure', 'TenThou', 'False') : 0.999998,
    ('False', 'Secure', 'TenThou', 'True') : 0.000002,
    ('False', 'Secure', 'TenThou', 'False') : 0.999998,
    ('True', 'City', 'TenThou', 'True') : 0.002,
    ('True', 'City', 'TenThou', 'False') : 0.998,
    ('False', 'City', 'TenThou', 'True') : 0.005,
    ('False', 'City', 'TenThou', 'False') : 0.995,
    ('True', 'Suburb', 'TenThou', 'True') : 0.0001,
    ('True', 'Suburb', 'TenThou', 'False') : 0.9999,
    ('False', 'Suburb', 'TenThou', 'True') : 0.0002,
    ('False', 'Suburb', 'TenThou', 'False') : 0.9998,
    ('True', 'Rural', 'TenThou', 'True') : 0.00002,
    ('True', 'Rural', 'TenThou', 'False') : 0.99998,
    ('False', 'Rural', 'TenThou', 'True') : 0.0001,
    ('False', 'Rural', 'TenThou', 'False') : 0.9999,

    ('True', 'Secure', 'TwentyThou', 'True') : 0.000003,
    ('True', 'Secure', 'TwentyThou', 'False') : 0.999997,
    ('False', 'Secure', 'TwentyThou', 'True') : 0.000003,
    ('False', 'Secure', 'TwentyThou', 'False') : 0.999997,
    ('True', 'City', 'TwentyThou', 'True') : 0.005,
    ('True', 'City', 'TwentyThou', 'False') : 0.995,
    ('False', 'City', 'TwentyThou', 'True') : 0.01,
    ('False', 'City', 'TwentyThou', 'False') : 0.99,
    ('True', 'Suburb', 'TwentyThou', 'True') : 0.0003,
    ('True', 'Suburb', 'TwentyThou', 'False') : 0.9997,
    ('False', 'Suburb', 'TwentyThou', 'True') : 0.0005,
    ('False', 'Suburb', 'TwentyThou', 'False') : 0.9995,
    ('True', 'Rural', 'TwentyThou', 'True') : 0.00005,
    ('True', 'Rural', 'TwentyThou', 'False') : 0.99995,
    ('False', 'Rural', 'TwentyThou', 'True') : 0.0002,
    ('False', 'Rural', 'TwentyThou', 'False') : 0.9998,

    ('True', 'Secure', 'FiftyThou', 'True') : 0.000002,
    ('True', 'Secure', 'FiftyThou', 'False') : 0.999998,
    ('False', 'Secure', 'FiftyThou', 'True') : 0.000002,
    ('False', 'Secure', 'FiftyThou', 'False') : 0.999998,
    ('True', 'City', 'FiftyThou', 'True') : 0.005,
    ('True', 'City', 'FiftyThou', 'False') : 0.995,
    ('False', 'City', 'FiftyThou', 'True') : 0.01,
    ('False', 'City', 'FiftyThou', 'False') : 0.99,
    ('True', 'Suburb', 'FiftyThou', 'True') : 0.0003,
    ('True', 'Suburb', 'FiftyThou', 'False') : 0.9997,
    ('False', 'Suburb', 'FiftyThou', 'True') : 0.0005,
    ('False', 'Suburb', 'FiftyThou', 'False') : 0.9995,
    ('True', 'Rural', 'FiftyThou', 'True') : 0.00005,
    ('True', 'Rural', 'FiftyThou', 'False') : 0.99995,
    ('False', 'Rural', 'FiftyThou', 'True') : 0.0002,
    ('False', 'Rural', 'FiftyThou', 'False') : 0.9998,


    ('True', 'Secure', 'Million', 'True') : 0.000001,
    ('True', 'Secure', 'Million', 'False') : 0.999999,
    ('False', 'Secure', 'Million', 'True') : 0.000001,
    ('False', 'Secure', 'Million', 'False') : 0.999999,
    ('True', 'City', 'Million', 'True') : 0.000001,
    ('True', 'City', 'Million', 'False') : 0.999999,
    ('False', 'City', 'Million', 'True') : 0.000001,
    ('False', 'City', 'Million', 'False') : 0.999999,
    ('True', 'Suburb', 'Million', 'True') : 0.000001,
    ('True', 'Suburb', 'Million', 'False') : 0.999999,
    ('False', 'Suburb', 'Million', 'True') : 0.000001,
    ('False', 'Suburb', 'Million', 'False') : 0.999999,
    ('True', 'Rural', 'Million', 'True') : 0.000001,
    ('True', 'Rural', 'Million', 'False') : 0.999999,
    ('False', 'Rural', 'Million', 'True') : 0.000001,
    ('False', 'Rural', 'Million', 'False') : 0.999999,

})

net.P['OtherCarCost'] = pd.Series({
    # acc, rugged auto  es fb tank  none midl mod sev tenthou hundredthou mill
    ('None', 'EggShell', 'Thousand') : 1.0,
    ('None', 'EggShell', 'TenThou') : 0.0,
    ('None', 'EggShell', 'HundredThou') : 0.0,
    ('None', 'EggShell', 'Million') : 0.0,
    ('Mild', 'EggShell', 'Thousand') : 0.99000,
    ('Mild', 'EggShell', 'TenThou') : 0.00500,
    ('Mild', 'EggShell', 'HundredThou') : 0.00499,
    ('Mild', 'EggShell', 'Million') : 0.00001,
    ('Moderate', 'EggShell', 'Thousand') : 0.60000,
    ('Moderate', 'EggShell', 'TenThou') : 0.20000,
    ('Moderate', 'EggShell', 'HundredThou') : 0.19998,
    ('Moderate', 'EggShell', 'Million') : 0.00002,
    ('Severe', 'EggShell', 'Thousand') : 0.20000,
    ('Severe', 'EggShell', 'TenThou') : 0.40000,
    ('Severe', 'EggShell', 'HundredThou') : 0.39996,
    ('Severe', 'EggShell', 'Million') : 0.00004,

    ('None', 'Football', 'Thousand') : 1.0,
    ('None', 'Football', 'TenThou') : 0.0,
    ('None', 'Football', 'HundredThou') : 0.0,
    ('None', 'Football', 'Million') : 0.0,
    ('Mild', 'Football', 'Thousand') : 0.98,
    ('Mild', 'Football', 'TenThou') : 0.01,
    ('Mild', 'Football', 'HundredThou') : 0.01,
    ('Mild', 'Football', 'Million') : 0.0,
    ('Moderate', 'Football', 'Thousand') : 0.50000,
    ('Moderate', 'Football', 'TenThou') : 0.20000,
    ('Moderate', 'Football', 'HundredThou') : 0.29997,
    ('Moderate', 'Football', 'Million') : 0.00003,
    ('Severe', 'Football', 'Thousand') : 0.1,
    ('Severe', 'Football', 'TenThou') : 0.5,
    ('Severe', 'Football', 'HundredThou') : 0.39994,
    ('Severe', 'Football', 'Million') : 0.00006,

    ('None', 'Tank', 'Thousand') : 1.0,
    ('None', 'Tank', 'TenThou') : 0.0,
    ('None', 'Tank', 'HundredThou') : 0.0,
    ('None', 'Tank', 'Million') : 0.0,
    ('Mild', 'Tank', 'Thousand') : 0.95000,
    ('Mild', 'Tank', 'TenThou') : 0.03,
    ('Mild', 'Tank', 'HundredThou') : 0.01998,
    ('Mild', 'Tank', 'Million') : 0.00002,
    ('Moderate', 'Tank', 'Thousand') : 0.40000,
    ('Moderate', 'Tank', 'TenThou') : 0.30000,
    ('Moderate', 'Tank', 'HundredThou') : 0.29996,
    ('Moderate', 'Tank', 'Million') : 0.00004,
    ('Severe', 'Tank', 'Thousand') : 0.0050,
    ('Severe', 'Tank', 'TenThou') : 0.5500,
    ('Severe', 'Tank', 'HundredThou') : 0.4449,
    ('Severe', 'Tank', 'Million') : 0.0001,
})


net.P['ThisCarDam'] = pd.Series({
    # Acc, RuggedAutoo,
    ('None', 'EggShell', 'None') : 1.0,
    ('None', 'EggShell', 'Mild') : 0.0,
    ('None', 'EggShell', 'Moderate') : 0.0,
    ('None', 'EggShell', 'Severe') : 0.0,
    ('Mild', 'EggShell', 'None') : 0.001,
    ('Mild', 'EggShell', 'Mild') : 0.900,
    ('Mild', 'EggShell', 'Moderate') : 0.098,
    ('Mild', 'EggShell', 'Severe') : 0.001,
    ('Moderate', 'EggShell', 'None') : 0.000001,
    ('Moderate', 'EggShell', 'Mild') : 0.000999,
    ('Moderate', 'EggShell', 'Moderate') : 0.700000,
    ('Moderate', 'EggShell', 'Severe') : 0.299000,
    ('Severe', 'EggShell', 'None') : 0.000001,
    ('Severe', 'EggShell', 'Mild') : 0.000999,
    ('Severe', 'EggShell', 'Moderate') : 0.700000,
    ('Severe', 'EggShell', 'Severe') : 0.299000,

    ('None', 'Football', 'None') : 1.0,
    ('None', 'Football', 'Mild') : 0.0,
    ('None', 'Football', 'Moderate') : 0.0,
    ('None', 'Football', 'Severe') : 0.0,
    ('Mild', 'Football', 'None') : 0.200000,
    ('Mild', 'Football', 'Mild') : 0.750000,
    ('Mild', 'Football', 'Moderate') : 0.049999,
    ('Mild', 'Football', 'Severe') : 0.000001,
    ('Moderate', 'Football', 'None') : 0.001,
    ('Moderate', 'Football', 'Mild') : 0.099,
    ('Moderate', 'Football', 'Moderate') : 0.800,
    ('Moderate', 'Football', 'Severe') : 0.100,
    ('Severe', 'Football', 'None') : 0.000001,
    ('Severe', 'Football', 'Mild') : 0.000999,
    ('Severe', 'Football', 'Moderate') : 0.009000,
    ('Severe', 'Football', 'Severe') : 0.990000,

    ('None', 'Tank', 'None') : 1.0,
    ('None', 'Tank', 'Mild') : 0.0,
    ('None', 'Tank', 'Moderate') : 0.0,
    ('None', 'Tank', 'Severe') : 0.0,
    ('Mild', 'Tank', 'None') : 0.700000,
    ('Mild', 'Tank', 'Mild') : 0.290000,
    ('Mild', 'Tank', 'Moderate') : 0.009999,
    ('Mild', 'Tank', 'Severe') : 0.000001,
    ('Moderate', 'Tank', 'None') : 0.05,
    ('Moderate', 'Tank', 'Mild') : 0.6,
    ('Moderate', 'Tank', 'Moderate') : 0.3,
    ('Moderate', 'Tank', 'Severe') : 0.05,
    ('Severe', 'Tank', 'None') : 0.05,
    ('Severe', 'Tank', 'Mild') : 0.2,
    ('Severe', 'Tank', 'Moderate') : 0.2,
    ('Severe', 'Tank', 'Severe') : 0.55,
})

net.P['ThisCarCost'] = pd.Series({
    #ThisCarDam, CarVal, Theft, Cost
    ('None', 'FiveThou', 'True', 'Thousand') : 0.2,
    ('None', 'FiveThou', 'True', 'TenThou') : 0.8,
    ('None', 'FiveThou', 'True', 'HundredThou') : 0.0,
    ('None', 'FiveThou', 'True', 'Million') : 0.0,
    ('Mild', 'FiveThou', 'True', 'Thousand') : 0.15,
    ('Mild', 'FiveThou', 'True', 'TenThou') : 0.85,
    ('Mild', 'FiveThou', 'True', 'HundredThou') : 0.0,
    ('Mild', 'FiveThou', 'True', 'Million') : 0.0,
    ('Moderate', 'FiveThou', 'True', 'Thousand') : 0.05,
    ('Moderate', 'FiveThou', 'True', 'TenThou') : 0.95,
    ('Moderate', 'FiveThou', 'True', 'HundredThou') : 0.0,
    ('Moderate', 'FiveThou', 'True', 'Million') : 0.0,
    ('Severe', 'FiveThou', 'True', 'Thousand') : 0.03,
    ('Severe', 'FiveThou', 'True', 'TenThou') : 0.97,
    ('Severe', 'FiveThou', 'True', 'HundredThou') : 0.0,
    ('Severe', 'FiveThou', 'True', 'Million') : 0.0,
    ('None', 'TenThou', 'True', 'Thousand') : 0.05,
    ('None', 'TenThou', 'True', 'TenThou') : 0.95,
    ('None', 'TenThou', 'True', 'HundredThou') : 0.0,
    ('None', 'TenThou', 'True', 'Million') : 0.0,
    ('Mild', 'TenThou', 'True', 'Thousand') : 0.03,
    ('Mild', 'TenThou', 'True', 'TenThou') : 0.97,
    ('Mild', 'TenThou', 'True', 'HundredThou') : 0.0,
    ('Mild', 'TenThou', 'True', 'Million') : 0.0,
    ('Moderate', 'TenThou', 'True', 'Thousand') : 0.01,
    ('Moderate', 'TenThou', 'True', 'TenThou') : 0.99,
    ('Moderate', 'TenThou', 'True', 'HundredThou') : 0.0,
    ('Moderate', 'TenThou', 'True', 'Million') : 0.0,
    ('Severe', 'TenThou', 'True', 'Thousand') : 0.000001,
    ('Severe', 'TenThou', 'True', 'TenThou') : 0.999999,
    ('Severe', 'TenThou', 'True', 'HundredThou') : 0.0,
    ('Severe', 'TenThou', 'True', 'Million') : 0.0,
    ('None', 'TwentyThou', 'True', 'Thousand') : 0.04,
    ('None', 'TwentyThou', 'True', 'TenThou') : 0.01,
    ('None', 'TwentyThou', 'True', 'HundredThou') : 0.95,
    ('None', 'TwentyThou', 'True', 'Million') : 0.0,
    ('Mild', 'TwentyThou', 'True', 'Thousand') : 0.03,
    ('Mild', 'TwentyThou', 'True', 'TenThou') : 0.02,
    ('Mild', 'TwentyThou', 'True', 'HundredThou') : 0.95,
    ('Mild', 'TwentyThou', 'True', 'Million') : 0.0,
    ('Moderate', 'TwentyThou', 'True', 'Thousand') : 0.001,
    ('Moderate', 'TwentyThou', 'True', 'TenThou') : 0.001,
    ('Moderate', 'TwentyThou', 'True', 'HundredThou') : 0.998,
    ('Moderate', 'TwentyThou', 'True', 'Million') : 0.0,
    ('Severe', 'TwentyThou', 'True', 'Thousand') : 0.000001,
    ('Severe', 'TwentyThou', 'True', 'TenThou') : 0.000001,
    ('Severe', 'TwentyThou', 'True', 'HundredThou') : 0.999998,
    ('Severe', 'TwentyThou', 'True', 'Million') : 0.0,
    ('None', 'FiftyThou', 'True', 'Thousand') : 0.04,
    ('None', 'FiftyThou', 'True', 'TenThou') : 0.01,
    ('None', 'FiftyThou', 'True', 'HundredThou') : 0.95,
    ('None', 'FiftyThou', 'True', 'Million') : 0.0,
    ('Mild', 'FiftyThou', 'True', 'Thousand') : 0.03,
    ('Mild', 'FiftyThou', 'True', 'TenThou') : 0.02,
    ('Mild', 'FiftyThou', 'True', 'HundredThou') : 0.95,
    ('Mild', 'FiftyThou', 'True', 'Million') : 0.0,
    ('Moderate', 'FiftyThou', 'True', 'Thousand') : 0.001,
    ('Moderate', 'FiftyThou', 'True', 'TenThou') : 0.001,
    ('Moderate', 'FiftyThou', 'True', 'HundredThou') : 0.998,
    ('Moderate', 'FiftyThou', 'True', 'Million') : 0.0,
    ('Severe', 'FiftyThou', 'True', 'Thousand') : 0.000001,
    ('Severe', 'FiftyThou', 'True', 'TenThou') : 0.000001,
    ('Severe', 'FiftyThou', 'True', 'HundredThou') : 0.999998,
    ('Severe', 'FiftyThou', 'True', 'Million') : 0.0,
    ('None', 'Million', 'True', 'Thousand') : 0.04,
    ('None', 'Million', 'True', 'TenThou') : 0.01,
    ('None', 'Million', 'True', 'HundredThou') : 0.2,
    ('None', 'Million', 'True', 'Million') : 0.75,
    ('Mild', 'Million', 'True', 'Thousand') : 0.02,
    ('Mild', 'Million', 'True', 'TenThou') : 0.03,
    ('Mild', 'Million', 'True', 'HundredThou') : 0.25,
    ('Mild', 'Million', 'True', 'Million') : 0.7,
    ('Moderate', 'Million', 'True', 'Thousand') : 0.001,
    ('Moderate', 'Million', 'True', 'TenThou') : 0.001,
    ('Moderate', 'Million', 'True', 'HundredThou') : 0.018,
    ('Moderate', 'Million', 'True', 'Million') : 0.980,
    ('Severe', 'Million', 'True', 'Thousand') : 0.000001,
    ('Severe', 'Million', 'True', 'TenThou') : 0.000001,
    ('Severe', 'Million', 'True', 'HundredThou') : 0.009998,
    ('Severe', 'Million', 'True', 'Million') : 0.990000,

    ############
    ('None', 'FiveThou', 'False', 'Thousand') : 1.0,
    ('None', 'FiveThou', 'False', 'TenThou') : 0.0,
    ('None', 'FiveThou', 'False', 'HundredThou') : 0.0,
    ('None', 'FiveThou', 'False', 'Million') : 0.0,
    ('Mild', 'FiveThou', 'False', 'Thousand') : 0.95,
    ('Mild', 'FiveThou', 'False', 'TenThou') : 0.05,
    ('Mild', 'FiveThou', 'False', 'HundredThou') : 0.0,
    ('Mild', 'FiveThou', 'False', 'Million') : 0.0,
    ('Moderate', 'FiveThou', 'False', 'Thousand') : 0.25,
    ('Moderate', 'FiveThou', 'False', 'TenThou') : 0.75,
    ('Moderate', 'FiveThou', 'False', 'HundredThou') : 0.0,
    ('Moderate', 'FiveThou', 'False', 'Million') : 0.0,
    ('Severe', 'FiveThou', 'False', 'Thousand') : 0.05,
    ('Severe', 'FiveThou', 'False', 'TenThou') : 0.95,
    ('Severe', 'FiveThou', 'False', 'HundredThou') : 0.0,
    ('Severe', 'FiveThou', 'False', 'Million') : 0.0,
    ('None', 'TenThou', 'False', 'Thousand') : 1.0,
    ('None', 'TenThou', 'False', 'TenThou') : 0.0,
    ('None', 'TenThou', 'False', 'HundredThou') : 0.0,
    ('None', 'TenThou', 'False', 'Million') : 0.0,
    ('Mild', 'TenThou', 'False', 'Thousand') : 0.95,
    ('Mild', 'TenThou', 'False', 'TenThou') : 0.05,
    ('Mild', 'TenThou', 'False', 'HundredThou') : 0.0,
    ('Mild', 'TenThou', 'False', 'Million') : 0.0,
    ('Moderate', 'TenThou', 'False', 'Thousand') : 0.15,
    ('Moderate', 'TenThou', 'False', 'TenThou') : 0.85,
    ('Moderate', 'TenThou', 'False', 'HundredThou') : 0.0,
    ('Moderate', 'TenThou', 'False', 'Million') : 0.0,
    ('Severe', 'TenThou', 'False', 'Thousand') : 0.01,
    ('Severe', 'TenThou', 'False', 'TenThou') : 0.99,
    ('Severe', 'TenThou', 'False', 'HundredThou') : 0.0,
    ('Severe', 'TenThou', 'False', 'Million') : 0.0,
    ('None', 'TwentyThou', 'False', 'Thousand') : 1.0,
    ('None', 'TwentyThou', 'False', 'TenThou') : 0.0,
    ('None', 'TwentyThou', 'False', 'HundredThou') : 0.0,
    ('None', 'TwentyThou', 'False', 'Million') : 0.0,
    ('Mild', 'TwentyThou', 'False', 'Thousand') : 0.99,
    ('Mild', 'TwentyThou', 'False', 'TenThou') : 0.01,
    ('Mild', 'TwentyThou', 'False', 'HundredThou') : 0.0,
    ('Mild', 'TwentyThou', 'False', 'Million') : 0.0,
    ('Moderate', 'TwentyThou', 'False', 'Thousand') : 0.01,
    ('Moderate', 'TwentyThou', 'False', 'TenThou') : 0.01,
    ('Moderate', 'TwentyThou', 'False', 'HundredThou') : 0.98,
    ('Moderate', 'TwentyThou', 'False', 'Million') : 0.0,
    ('Severe', 'TwentyThou', 'False', 'Thousand') : 0.005,
    ('Severe', 'TwentyThou', 'False', 'TenThou') : 0.005,
    ('Severe', 'TwentyThou', 'False', 'HundredThou') : 0.990,
    ('Severe', 'TwentyThou', 'False', 'Million') : 0.0,
    ('None', 'FiftyThou', 'False', 'Thousand') : 1.0,
    ('None', 'FiftyThou', 'False', 'TenThou') : 0.0,
    ('None', 'FiftyThou', 'False', 'HundredThou') : 0.0,
    ('None', 'FiftyThou', 'False', 'Million') : 0.0,
    ('Mild', 'FiftyThou', 'False', 'Thousand') : 0.99,
    ('Mild', 'FiftyThou', 'False', 'TenThou') : 0.01,
    ('Mild', 'FiftyThou', 'False', 'HundredThou') : 0.0,
    ('Mild', 'FiftyThou', 'False', 'Million') : 0.0,
    ('Moderate', 'FiftyThou', 'False', 'Thousand') : 0.005,
    ('Moderate', 'FiftyThou', 'False', 'TenThou') : 0.005,
    ('Moderate', 'FiftyThou', 'False', 'HundredThou') : 0.990,
    ('Moderate', 'FiftyThou', 'False', 'Million') : 0.0,
    ('Severe', 'FiftyThou', 'False', 'Thousand') : 0.001,
    ('Severe', 'FiftyThou', 'False', 'TenThou') : 0.001,
    ('Severe', 'FiftyThou', 'False', 'HundredThou') : 0.998,
    ('Severe', 'FiftyThou', 'False', 'Million') : 0.0,
    ('None', 'Million', 'False', 'Thousand') : 1.0,
    ('None', 'Million', 'False', 'TenThou') : 0.0,
    ('None', 'Million', 'False', 'HundredThou') : 0.0,
    ('None', 'Million', 'False', 'Million') : 0.0,
    ('Mild', 'Million', 'False', 'Thousand') : 0.98,
    ('Mild', 'Million', 'False', 'TenThou') : 0.01,
    ('Mild', 'Million', 'False', 'HundredThou') : 0.01,
    ('Mild', 'Million', 'False', 'Million') : 0.0,
    ('Moderate', 'Million', 'False', 'Thousand') : 0.003,
    ('Moderate', 'Million', 'False', 'TenThou') : 0.003,
    ('Moderate', 'Million', 'False', 'HundredThou') : 0.044,
    ('Moderate', 'Million', 'False', 'Million') : 0.950,
    ('Severe', 'Million', 'False', 'Thousand') : 0.000001,
    ('Severe', 'Million', 'False', 'TenThou') : 0.000001,
    ('Severe', 'Million', 'False', 'HundredThou') : 0.029998,
    ('Severe', 'Million', 'False', 'Million') : 0.970000,

})


net.P['PropCost'] = pd.Series({
    # OTherCarCost, THisCarCost, PropCost
    ('Thousand', 'Thousand', 'Thousand'): 0.7,
    ('Thousand', 'Thousand', 'TenThou'): 0.3,
    ('Thousand', 'Thousand', 'HundredThou'): 0.0,
    ('Thousand', 'Thousand', 'Million'): 0.0,
    ('TenThou', 'Thousand', 'Thousand'): 0.0,
    ('TenThou', 'Thousand', 'TenThou'): 0.95,
    ('TenThou', 'Thousand', 'HundredThou'): 0.05,
    ('TenThou', 'Thousand', 'Million'): 0.0,
    ('HundredThou', 'Thousand', 'Thousand'): 0.0,
    ('HundredThou', 'Thousand', 'TenThou'): 0.0,
    ('HundredThou', 'Thousand', 'HundredThou'): 0.98,
    ('HundredThou', 'Thousand', 'Million'): 0.02,
    ('Million', 'Thousand', 'Thousand'): 0.0,
    ('Million', 'Thousand', 'TenThou'): 0.0,
    ('Million', 'Thousand', 'HundredThou'): 0.0,
    ('Million', 'Thousand', 'Million'): 1.0,

    ('Thousand', 'TenThou', 'Thousand'): 0.0,
    ('Thousand', 'TenThou', 'TenThou'): 0.95,
    ('Thousand', 'TenThou', 'HundredThou'): 0.05,
    ('Thousand', 'TenThou', 'Million'): 0.0,
    ('TenThou', 'TenThou', 'Thousand'): 0.0,
    ('TenThou', 'TenThou', 'TenThou'): 0.6,
    ('TenThou', 'TenThou', 'HundredThou'): 0.4,
    ('TenThou', 'TenThou', 'Million'): 0.0,
    ('HundredThou', 'TenThou', 'Thousand'): 0.0,
    ('HundredThou', 'TenThou', 'TenThou'): 0.0,
    ('HundredThou', 'TenThou', 'HundredThou'): 0.8,
    ('HundredThou', 'TenThou', 'Million'): 0.2,
    ('Million', 'TenThou', 'Thousand'): 0.0,
    ('Million', 'TenThou', 'TenThou'): 0.0,
    ('Million', 'TenThou', 'HundredThou'): 0.0,
    ('Million', 'TenThou', 'Million'): 1.0,

    ('Thousand', 'HundredThou', 'Thousand'): 0.0,
    ('Thousand', 'HundredThou', 'TenThou'): 0.0,
    ('Thousand', 'HundredThou', 'HundredThou'): 0.98,
    ('Thousand', 'HundredThou', 'Million'): 0.02,
    ('TenThou', 'HundredThou', 'Thousand'): 0.0,
    ('TenThou', 'HundredThou', 'TenThou'): 0.0,
    ('TenThou', 'HundredThou', 'HundredThou'): 0.95,
    ('TenThou', 'HundredThou', 'Million'): 0.05,
    ('HundredThou', 'HundredThou', 'Thousand'): 0.0,
    ('HundredThou', 'HundredThou', 'TenThou'): 0.0,
    ('HundredThou', 'HundredThou', 'HundredThou'): 0.6,
    ('HundredThou', 'HundredThou', 'Million'): 0.4,
    ('Million', 'HundredThou', 'Thousand'): 0.0,
    ('Million', 'HundredThou', 'TenThou'): 0.0,
    ('Million', 'HundredThou', 'HundredThou'): 0.0,
    ('Million', 'HundredThou', 'Million'): 1.0,

    ('Thousand', 'Million', 'Thousand'): 0.0,
    ('Thousand', 'Million', 'TenThou'): 0.0,
    ('Thousand', 'Million', 'HundredThou'): 0.0,
    ('Thousand', 'Million', 'Million'): 1.0,
    ('TenThou', 'Million', 'Thousand'): 0.0,
    ('TenThou', 'Million', 'TenThou'): 0.0,
    ('TenThou', 'Million', 'HundredThou'): 0.0,
    ('TenThou', 'Million', 'Million'): 1.0,
    ('HundredThou', 'Million', 'Thousand'): 0.0,
    ('HundredThou', 'Million', 'TenThou'): 0.0,
    ('HundredThou', 'Million', 'HundredThou'): 0.0,
    ('HundredThou', 'Million', 'Million'): 1.0,
    ('Million', 'Million', 'Thousand'): 0.0,
    ('Million', 'Million', 'TenThou'): 0.0,
    ('Million', 'Million', 'HundredThou'): 0.0,
    ('Million', 'Million', 'Million'): 1.0,
})

net.P['MedCost'] = pd.Series({
    #Accident, Age, Cushioning
    ('None', 'Adolescent', 'Poor', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Poor', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Poor', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Poor', 'Thousand'): 0.96,
    ('Mild', 'Adolescent', 'Poor', 'TenThou'): 0.03,
    ('Mild', 'Adolescent', 'Poor', 'HundredThou'): 0.009,
    ('Mild', 'Adolescent', 'Poor', 'Million'): 0.001,
    ('Moderate', 'Adolescent', 'Poor', 'Thousand'): 0.5,
    ('Moderate', 'Adolescent', 'Poor', 'TenThou'): 0.2,
    ('Moderate', 'Adolescent', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Adolescent', 'Poor', 'Million'): 0.1,
    ('Severe', 'Adolescent', 'Poor', 'Thousand'): 0.3,
    ('Severe', 'Adolescent', 'Poor', 'TenThou'): 0.3,
    ('Severe', 'Adolescent', 'Poor', 'HundredThou'): 0.2,
    ('Severe', 'Adolescent', 'Poor', 'Million'): 0.2,
    ('None', 'Adult', 'Poor', 'Thousand'): 1.0,
    ('None', 'Adult', 'Poor', 'TenThou'): 0.0,
    ('None', 'Adult', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Poor', 'Million'): 0.0,
    ('Mild', 'Adult', 'Poor', 'Thousand'): 0.96,
    ('Mild', 'Adult', 'Poor', 'TenThou'): 0.03,
    ('Mild', 'Adult', 'Poor', 'HundredThou'): 0.009,
    ('Mild', 'Adult', 'Poor', 'Million'): 0.001,
    ('Moderate', 'Adult', 'Poor', 'Thousand'): 0.5,
    ('Moderate', 'Adult', 'Poor', 'TenThou'): 0.2,
    ('Moderate', 'Adult', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Adult', 'Poor', 'Million'): 0.1,
    ('Severe', 'Adult', 'Poor', 'Thousand'): 0.3,
    ('Severe', 'Adult', 'Poor', 'TenThou'): 0.3,
    ('Severe', 'Adult', 'Poor', 'HundredThou'): 0.2,
    ('Severe', 'Adult', 'Poor', 'Million'): 0.2,
    ('None', 'Senior', 'Poor', 'Thousand'): 1.0,
    ('None', 'Senior', 'Poor', 'TenThou'): 0.0,
    ('None', 'Senior', 'Poor', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Poor', 'Million'): 0.0,
    ('Mild', 'Senior', 'Poor', 'Thousand'): 0.9,
    ('Mild', 'Senior', 'Poor', 'TenThou'): 0.07,
    ('Mild', 'Senior', 'Poor', 'HundredThou'): 0.02,
    ('Mild', 'Senior', 'Poor', 'Million'): 0.01,
    ('Moderate', 'Senior', 'Poor', 'Thousand'): 0.3,
    ('Moderate', 'Senior', 'Poor', 'TenThou'): 0.3,
    ('Moderate', 'Senior', 'Poor', 'HundredThou'): 0.2,
    ('Moderate', 'Senior', 'Poor', 'Million'): 0.2,
    ('Severe', 'Senior', 'Poor', 'Thousand'): 0.2,
    ('Severe', 'Senior', 'Poor', 'TenThou'): 0.2,
    ('Severe', 'Senior', 'Poor', 'HundredThou'): 0.3,
    ('Severe', 'Senior', 'Poor', 'Million'): 0.3,


    ('None', 'Adolescent', 'Wealthy', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Wealthy', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Wealthy', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Wealthy', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Wealthy', 'Thousand'): 0.999000,
    ('Mild', 'Adolescent', 'Wealthy', 'TenThou'): 0.00099,
    ('Mild', 'Adolescent', 'Wealthy', 'HundredThou'): 0.000009,
    ('Mild', 'Adolescent', 'Wealthy', 'Million'): 0.000001,
    ('Moderate', 'Adolescent', 'Wealthy', 'Thousand'): 0.990,
    ('Moderate', 'Adolescent', 'Wealthy', 'TenThou'): 0.007,
    ('Moderate', 'Adolescent', 'Wealthy', 'HundredThou'): 0.002,
    ('Moderate', 'Adolescent', 'Wealthy', 'Million'): 0.001,
    ('Severe', 'Adolescent', 'Wealthy', 'Thousand'): 0.95,
    ('Severe', 'Adolescent', 'Wealthy', 'TenThou'): 0.03,
    ('Severe', 'Adolescent', 'Wealthy', 'HundredThou'): 0.01,
    ('Severe', 'Adolescent', 'Wealthy', 'Million'): 0.01,
    ('None', 'Adult', 'Wealthy', 'Thousand'): 1.0,
    ('None', 'Adult', 'Wealthy', 'TenThou'): 0.0,
    ('None', 'Adult', 'Wealthy', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Wealthy', 'Million'): 0.0,
    ('Mild', 'Adult', 'Wealthy', 'Thousand'): 0.999000,
    ('Mild', 'Adult', 'Wealthy', 'TenThou'): 0.000990,
    ('Mild', 'Adult', 'Wealthy', 'HundredThou'): 0.000009,
    ('Mild', 'Adult', 'Wealthy', 'Million'): 0.000001,
    ('Moderate', 'Adult', 'Wealthy', 'Thousand'): 0.990,
    ('Moderate', 'Adult', 'Wealthy', 'TenThou'): 0.007,
    ('Moderate', 'Adult', 'Wealthy', 'HundredThou'): 0.002,
    ('Moderate', 'Adult', 'Wealthy', 'Million'): 0.001,
    ('Severe', 'Adult', 'Wealthy', 'Thousand'): 0.95,
    ('Severe', 'Adult', 'Wealthy', 'TenThou'): 0.03,
    ('Severe', 'Adult', 'Wealthy', 'HundredThou'): 0.01,
    ('Severe', 'Adult', 'Wealthy', 'Million'): 0.01,
    ('None', 'Senior', 'Wealthy', 'Thousand'): 1.0,
    ('None', 'Senior', 'Wealthy', 'TenThou'): 0.0,
    ('None', 'Senior', 'Wealthy', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Wealthy', 'Million'): 0.0,
    ('Mild', 'Senior', 'Wealthy', 'Thousand'): 0.99,
    ('Mild', 'Senior', 'Wealthy', 'TenThou'): 0.007,
    ('Mild', 'Senior', 'Wealthy', 'HundredThou'): 0.002,
    ('Mild', 'Senior', 'Wealthy', 'Million'): 0.001,
    ('Moderate', 'Senior', 'Wealthy', 'Thousand'): 0.95,
    ('Moderate', 'Senior', 'Wealthy', 'TenThou'): 0.03,
    ('Moderate', 'Senior', 'Wealthy', 'HundredThou'): 0.01,
    ('Moderate', 'Senior', 'Wealthy', 'Million'): 0.01,
    ('Severe', 'Senior', 'Wealthy', 'Thousand'): 0.90,
    ('Severe', 'Senior', 'Wealthy', 'TenThou'): 0.05,
    ('Severe', 'Senior', 'Wealthy', 'HundredThou'): 0.03,
    ('Severe', 'Senior', 'Wealthy', 'Million'): 0.02,

    ('None', 'Adolescent', 'Middle', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'Middle', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'Middle', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'Middle', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'Middle', 'Thousand'): 0.98,
    ('Mild', 'Adolescent', 'Middle', 'TenThou'): 0.019,
    ('Mild', 'Adolescent', 'Middle', 'HundredThou'): 0.0009,
    ('Mild', 'Adolescent', 'Middle', 'Million'): 0.0001,
    ('Moderate', 'Adolescent', 'Middle', 'Thousand'): 0.80,
    ('Moderate', 'Adolescent', 'Middle', 'TenThou'): 0.15,
    ('Moderate', 'Adolescent', 'Middle', 'HundredThou'): 0.03,
    ('Moderate', 'Adolescent', 'Middle', 'Million'): 0.02,
    ('Severe', 'Adolescent', 'Middle', 'Thousand'): 0.5,
    ('Severe', 'Adolescent', 'Middle', 'TenThou'): 0.2,
    ('Severe', 'Adolescent', 'Middle', 'HundredThou'): 0.2,
    ('Severe', 'Adolescent', 'Middle', 'Million'): 0.1,
    ('None', 'Adult', 'Middle', 'Thousand'): 1.0,
    ('None', 'Adult', 'Middle', 'TenThou'): 0.0,
    ('None', 'Adult', 'Middle', 'HundredThou'): 0.0,
    ('None', 'Adult', 'Middle', 'Million'): 0.0,
    ('Mild', 'Adult', 'Middle', 'Thousand'): 0.98,
    ('Mild', 'Adult', 'Middle', 'TenThou'): 0.019,
    ('Mild', 'Adult', 'Middle', 'HundredThou'): 0.0009,
    ('Mild', 'Adult', 'Middle', 'Million'): 0.0001,
    ('Moderate', 'Adult', 'Middle', 'Thousand'): 0.8,
    ('Moderate', 'Adult', 'Middle', 'TenThou'): 0.15,
    ('Moderate', 'Adult', 'Middle', 'HundredThou'): 0.03,
    ('Moderate', 'Adult', 'Middle', 'Million'): 0.02,
    ('Severe', 'Adult', 'Middle', 'Thousand'): 0.5,
    ('Severe', 'Adult', 'Middle', 'TenThou'): 0.2,
    ('Severe', 'Adult', 'Middle', 'HundredThou'): 0.2,
    ('Severe', 'Adult', 'Middle', 'Million'): 0.1,
    ('None', 'Senior', 'Middle', 'Thousand'): 1.0,
    ('None', 'Senior', 'Middle', 'TenThou'): 0.0,
    ('None', 'Senior', 'Middle', 'HundredThou'): 0.0,
    ('None', 'Senior', 'Middle', 'Million'): 0.0,
    ('Mild', 'Senior', 'Middle', 'Thousand'): 0.950,
    ('Mild', 'Senior', 'Middle', 'TenThou'): 0.040,
    ('Mild', 'Senior', 'Middle', 'HundredThou'): 0.0007,
    ('Mild', 'Senior', 'Middle', 'Million'): 0.003,
    ('Moderate', 'Senior', 'Middle', 'Thousand'): 0.5,
    ('Moderate', 'Senior', 'Middle', 'TenThou'): 0.2,
    ('Moderate', 'Senior', 'Middle', 'HundredThou'): 0.2,
    ('Moderate', 'Senior', 'Middle', 'Million'): 0.1,
    ('Severe', 'Senior', 'Middle', 'Thousand'): 0.3,
    ('Severe', 'Senior', 'Middle', 'TenThou'): 0.3,
    ('Severe', 'Senior', 'Middle', 'HundredThou'): 0.2,
    ('Severe', 'Senior', 'Middle', 'Million'): 0.2,

    ('None', 'Adolescent', 'UpperMiddle', 'Thousand'): 1.0,
    ('None', 'Adolescent', 'UpperMiddle', 'TenThou'): 0.0,
    ('None', 'Adolescent', 'UpperMiddle', 'HundredThou'): 0.0,
    ('None', 'Adolescent', 'UpperMiddle', 'Million'): 0.0,
    ('Mild', 'Adolescent', 'UpperMiddle', 'Thousand'): 0.99,
    ('Mild', 'Adolescent', 'UpperMiddle', 'TenThou'): 0.0099,
    ('Mild', 'Adolescent', 'UpperMiddle', 'HundredThou'): 0.00009,
    ('Mild', 'Adolescent', 'UpperMiddle', 'Million'): 0.00001,
    ('Moderate', 'Adolescent', 'UpperMiddle', 'Thousand'): 0.95,
    ('Moderate', 'Adolescent', 'UpperMiddle', 'TenThou'): 0.02,
    ('Moderate', 'Adolescent', 'UpperMiddle', 'HundredThou'): 0.02,
    ('Moderate', 'Adolescent', 'UpperMiddle', 'Million'): 0.01,
    ('Severe', 'Adolescent', 'UpperMiddle', 'Thousand'): 0.9,
    ('Severe', 'Adolescent', 'UpperMiddle', 'TenThou'): 0.07,
    ('Severe', 'Adolescent', 'UpperMiddle', 'HundredThou'): 0.02,
    ('Severe', 'Adolescent', 'UpperMiddle', 'Million'): 0.01,
    ('None', 'Adult', 'UpperMiddle', 'Thousand'): 1.0,
    ('None', 'Adult', 'UpperMiddle', 'TenThou'): 0.0,
    ('None', 'Adult', 'UpperMiddle', 'HundredThou'): 0.0,
    ('None', 'Adult', 'UpperMiddle', 'Million'): 0.0,
    ('Mild', 'Adult', 'UpperMiddle', 'Thousand'): 0.99,
    ('Mild', 'Adult', 'UpperMiddle', 'TenThou'): 0.0099,
    ('Mild', 'Adult', 'UpperMiddle', 'HundredThou'): 0.00009,
    ('Mild', 'Adult', 'UpperMiddle', 'Million'): 0.00001,
    ('Moderate', 'Adult', 'UpperMiddle', 'Thousand'): 0.95,
    ('Moderate', 'Adult', 'UpperMiddle', 'TenThou'): 0.02,
    ('Moderate', 'Adult', 'UpperMiddle', 'HundredThou'): 0.02,
    ('Moderate', 'Adult', 'UpperMiddle', 'Million'): 0.01,
    ('Severe', 'Adult', 'UpperMiddle', 'Thousand'): 0.9,
    ('Severe', 'Adult', 'UpperMiddle', 'TenThou'): 0.07,
    ('Severe', 'Adult', 'UpperMiddle', 'HundredThou'): 0.02,
    ('Severe', 'Adult', 'UpperMiddle', 'Million'): 0.01,
    ('None', 'Senior', 'UpperMiddle', 'Thousand'): 1.0,
    ('None', 'Senior', 'UpperMiddle', 'TenThou'): 0.0,
    ('None', 'Senior', 'UpperMiddle', 'HundredThou'): 0.0,
    ('None', 'Senior', 'UpperMiddle', 'Million'): 0.0,
    ('Mild', 'Senior', 'UpperMiddle', 'Thousand'): 0.97,
    ('Mild', 'Senior', 'UpperMiddle', 'TenThou'): 0.025,
    ('Mild', 'Senior', 'UpperMiddle', 'HundredThou'): 0.003,
    ('Mild', 'Senior', 'UpperMiddle', 'Million'): 0.002,
    ('Moderate', 'Senior', 'UpperMiddle', 'Thousand'): 0.9,
    ('Moderate', 'Senior', 'UpperMiddle', 'TenThou'): 0.07,
    ('Moderate', 'Senior', 'UpperMiddle', 'HundredThou'): 0.02,
    ('Moderate', 'Senior', 'UpperMiddle', 'Million'): 0.01,
    ('Severe', 'Senior', 'UpperMiddle', 'Thousand'): 0.6,
    ('Severe', 'Senior', 'UpperMiddle', 'TenThou'): 0.3,
    ('Severe', 'Senior', 'UpperMiddle', 'HundredThou'): 0.07,
    ('Severe', 'Senior', 'UpperMiddle', 'Million'): 0.03,
})

net.P['ILiCost'] = pd.Series({
    # acc, Ili
    ('None', 'Thousand'): 1.0,
    ('None', 'TenThou'): 0.0,
    ('None', 'HundredThou'): 0.0,
    ('None', 'Million'): 0.0,

    ('Mild', 'Thousand'): 0.999000,
    ('Mild', 'TenThou'): 0.000998,
    ('Mild', 'HundredThou'): 0.000001,
    ('Mild', 'Million'): 0.000001,

    ('Moderate', 'Thousand'): 0.9,
    ('Moderate', 'TenThou'): 0.05,
    ('Moderate', 'HundredThou'): 0.03,
    ('Moderate', 'Million'): 0.02,

    ('Severe', 'Thousand'): 0.8,
    ('Severe', 'TenThou'): 0.1,
    ('Severe', 'HundredThou'): 0.06,
    ('Severe', 'Million'): 0.04,

})

net.P['DrivHist'] = pd.Series({
    #Skill, RA, DH
    ('Substandard', 'Psychopath', 'Zero'): 0.001,
    ('Substandard', 'Psychopath', 'One'): 0.0004,
    ('Substandard', 'Psychopath', 'Many'): 0.995,
    ('Normal', 'Psychopath', 'Zero'): 0.1,
    ('Normal', 'Psychopath', 'One'): 0.3,
    ('Normal', 'Psychopath', 'Many'): 0.6,
    ('Expert', 'Psychopath', 'Zero'): 0.3,
    ('Expert', 'Psychopath', 'One'): 0.3,
    ('Expert', 'Psychopath', 'Many'): 0.4,

    ('Substandard', 'Adventurous', 'Zero'): 0.002,
    ('Substandard', 'Adventurous', 'One'): 0.008,
    ('Substandard', 'Adventurous', 'Many'): 0.990,
    ('Normal', 'Adventurous', 'Zero'): 0.5,
    ('Normal', 'Adventurous', 'One'): 0.3,
    ('Normal', 'Adventurous', 'Many'): 0.2,
    ('Expert', 'Adventurous', 'Zero'): 0.6,
    ('Expert', 'Adventurous', 'One'): 0.3,
    ('Expert', 'Adventurous', 'Many'): 0.1,

    ('Substandard', 'Normal', 'Zero'): 0.03,
    ('Substandard', 'Normal', 'One'): 0.15,
    ('Substandard', 'Normal', 'Many'): 0.82,
    ('Normal', 'Normal', 'Zero'): 0.9,
    ('Normal', 'Normal', 'One'): 0.07,
    ('Normal', 'Normal', 'Many'): 0.03,
    ('Expert', 'Normal', 'Zero'): 0.990000,
    ('Expert', 'Normal', 'One'): 0.009999,
    ('Expert', 'Normal', 'Many'): 0.000001,

    ('Substandard', 'Cautious', 'Zero'): 0.3,
    ('Substandard', 'Cautious', 'One'): 0.3,
    ('Substandard', 'Cautious', 'Many'): 0.4,
    ('Normal', 'Cautious', 'Zero'): 0.95,
    ('Normal', 'Cautious', 'One'): 0.04,
    ('Normal', 'Cautious', 'Many'): 0.01,
    ('Expert', 'Cautious', 'Zero'): 0.999998,
    ('Expert', 'Cautious', 'One'): 0.000001,
    ('Expert', 'Cautious', 'Many'): 0.000001,
})


Insurance_Network = net